### PR TITLE
Edits for debugging the logging system test issues.

### PR DESCRIPTION
**Pull request by dhermes**
The "assignees" are just to loop people in on these builds, so we can (hopefully) see where it's stalling.

#3237 is the relevant bug

### CODE REVIEW

**Comment by dhermes** [comment]
Hello Heisenbug! No issues on the [push build][1] for the `GoogleCloudPlatform/logging-systest-stall` branch.

[1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1431

**Comment by dhermes** [comment]
OK a `master` [push build][1] also just succeeded. Maybe it was an intermittent service issue?

[1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1425

**Comment by dhermes** [comment]
OK I re-ran the build in this PR with `error_reporting` put back in and it [succeeded without issue][1].

@lukesneeringer Are we good to just close #3237 and forget about this? (If yes, that means it's time to cut `error_reporting==0.23.3` for @DizzeePascall)

[1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1434

**Comment by lukesneeringer** [comment]
Yes, but let's merge #3244 so it is a little easier to view what is up if it recurs.

**Pull request closed without merging**
