### PR TITLE
BigTable:  Separate mutations into a standalone package

### PR DESCRIPTION
**Pull request by zakons**
In order to provide row mutations in a Beam environment, which is highly distributed, partition the mutation code away from an interface coupled with DirectRow. This package allows MutateRowRequest's to be created and sent to the BigTable service without first materializing the rows in the table in memory.  Instead, instances of Mutation requests are created in memory and then sent to the service, without first reading an existing row.

This PR is built on top of the GAPIC API pull request, which has been merged into this pull request.

Also, Retry is used to provide retry at the granularity of an Entry, which is composed of a row_key and a list of mutations. The Retry code will attempt to retry the mutations for each Entry that does not succeed the first time.

### CODE REVIEW

**Comment by zakons** [comment]
@jonparrott Please review this new PR for mutations.

**Comment by sduskis** [comment]
I was chatting with @zakons this morning.  We should probably merge #4693, which this PR is based on, and rebase this branch before this PR is reviewed.

**Comment by jonparrott** [comment]
Good plan

**Comment by zakons** [comment]
@jonparrott Please merge this PR after merging BigTable: Integration of GAPIC #5178.

**Comment by jonparrott** [comment]
This doesn't seem totally rebased - seems some of the old _generated files are seeping through.

**Comment by zakons** [comment]
Closing this PR as the replacement for this is built entirely on the new GAPIC code merged with master on #5178.

**Pull request closed without merging**
