### PR TITLE
Sprinkle majyk retry fairy dust.

### LINKED ISSUE #3510: Pub / Sub snapshot system test has started failing
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2166
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2168
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2193

@tseaver Do you mind looking into this?

### PR DESCRIPTION
**Pull request by tseaver**
Closes #3510 

/cc @bjwatson

### CODE REVIEW

**Comment by tseaver** [comment]
I initially pushed this branch to my own fork, but then pushed it here to get system tests to run.  Anybody know how I get the PR to point at the local branch?

**Comment by dhermes** [comment]
How do you mean? What is not as you expect? I see

> @tseaver wants to merge 1 commit into `GoogleCloudPlatform:master` from `tseaver:3510-pubsub-flaky-snapshot-systest`

**Comment by tseaver** [comment]
Funny, I feel the same way about `mock.patch`. :)

**Comment by tseaver** [comment]
I wanted to switch the PR to be "from" the branch in this repo, instead of the one in my fork.  Github [allows switching the base branch](https://github.com/blog/2224-change-the-base-branch-of-a-pull-request) but not the other.

**Pull request merged**
