### PR TITLE
Cutting release 0.22.1 of datastore.

### PR DESCRIPTION
**Pull request by dhermes**

### CODE REVIEW

**Comment by dhermes** [comment]
This release is per @bjwatson request (via email). There have only been 2 relevant commits since the last release (and a 3rd commit in this PR):

```
$ git log datastore-0.22.0..cut-datastore-0.22.1 -- datastore/
commit 292b49d0052995d84ce60ddc19a9e3a8ebfd384b
Author: Danny Hermes <daniel.j.hermes@gmail.com>
Date:   Fri Dec 30 13:44:12 2016 -0800

    Cutting release 0.22.1 of datastore.

commit 33eb51285b73d907cb4e9d5c968ce385a3879535
Author: Danny Hermes <daniel.j.hermes@gmail.com>
Date:   Thu Dec 15 13:32:01 2016 -0800

    Using `gapic-google-cloud-datastore-v1` instead of `datastore._generated`.
    
    This does fully switch over to using the GAPIC client, but at least
    gets rid of **all** references to the generated code.

commit 2c42b7cc8bd7ae7f30df3888213345a5aa568c58
Author: Danny Hermes <daniel.j.hermes@gmail.com>
Date:   Wed Dec 14 23:43:05 2016 -0800

    Manually creating Client._connection in subclasses.
```

They are in PRs #2870 and #2876. The change in #2870 is just part of removing `Connection` and has no bearing on users (the `Connection` class was already made non-public).

Then change in #2876 is also (mostly) opaque to users. It swaps our hand generated `pb2` and `grpc` files out for the `gapic-google-cloud-datastore-v1` package.

**Comment by dhermes** [comment]
@daspecster @jonparrott @tseaver Due to #2870, we may need a release of core. The only `core` changes are in #2870:

```
$ git log core-0.22.1..cut-datastore-0.22.1 --pretty=%H -- core/
2c42b7cc8bd7ae7f30df3888213345a5aa568c58
ae2d90c49335d185468893841cd3828afc5fe3ef
```

but they have some definite implications on **all** dependent packages (i.e. this release of `core` needs a full version bump, and I'd like to finish the `Connection` deprecation before doing that release).

----

Given that, it may make sense to create a release branch for `datastore-0.22.1` and just cherry-pick #2876.

WDYT all?

/cc @bjwatson

**Comment by daspecster** [comment]
If we can finish the `Connection` removal first I think that would be a much cleaner path.

@dhermes, I can take a stab at that over the weekend if you can tell me roughly everything that needs to be done. (My life is boring and I don't have much for NYE plans. haha)

If it's kind of an urgent matter then cherry picking the commits is probably the only way to go.

**Comment by dhermes** [comment]
@daspecster The `Connection` **was** our core transport, so it's not a weekend project to get rid of it. We should make a `core` release **some time**, but I don't think it should block this one.

@bjwatson asked that this release go out in 2016.

**Comment by tseaver** [comment]
+1 for cherry-picking only the relevant changes w/o a `core` release.

**Comment by dhermes** [comment]
OK. @tseaver and @daspecster WDYT of me just running:

```
$ git checkout datastore-0.22.1-release-branch
$ git tag datastore-0.22.1
$ git push official datastore-0.22.1  # my GoogleCloudPlatform remote
```

This PR should still be merged but the tag won't be created from `master`.

-----

PS I am **not at all** a fan of the "cherry-pick release branch", but it's small scope here and is a "business need" for some reason I don't totally recall right now. If it starts to become a habit we should push back and rethink the process.

**Comment by daspecster** [comment]
SGTM, and I agree with keeping an eye out for this in the future.

**Comment by dhermes** [comment]
Pushed tag: https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/datastore-0.22.1
Build started: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/643

**Comment by dhermes** [comment]
This still needs to be merged to make sure `HEAD` reflects that latest version of `datastore`. I'm merging now, LMK if that's problematic.

**Pull request merged**
