### PR TITLE
Do not show Trace documentation.

### LINKED ISSUE #3717: Stackdriver Trace API should not yet be surfaced in documentation
https://google-cloud-python.readthedocs.io/en/latest/trace/index.html

Should not yet be there. We are not yet exposing gapic-only clients to users. This library was added to support a separate stackdriver tracing library and not intended for direct consumption by users.

### PR DESCRIPTION
**Pull request by lukesneeringer**
Fixes #3717.

@dhermes, can you merge this and manually update docs?

### CODE REVIEW

**Comment by tseaver** [comment]
@lukesneeringer Just removing it from the TOX breaks the docs build, because we run with `-W`, converting the "not included file" warning to an error.  We need to remove `docs/trace` as well.

**Comment by jonparrott** [comment]
We can either remove `docs/trace` or add the `:orphan:` marker to its index.

**Comment by lukesneeringer** [comment]
Any preference between those?

**Comment by jonparrott** [comment]
preference for orphan, as it still makes sure those pages build without error.

**Comment by dhermes** [comment]
But @jonparrott they will still show up in the docs if someone knows the URL / path

**Comment by jonparrott** [comment]
I'm okay with that for the time being.

**Comment by dhermes** [comment]
OK cool. (I just realized it was you and not @lukesneeringer that filed #3717.)

**Comment by lukesneeringer** [comment]
Okay, this should fix the build. Also noticed Speech was still alpha in `README.rst`, so I sent that up along with it.

**Pull request merged**
