### PR TITLE
Release bigquery 1.1.0

### PR DESCRIPTION
**Pull request by crwilcox**
This pull request was generated using releasetool.

### CODE REVIEW

**Comment by tseaver** [comment]
Looks like the merge of PR #5206 didn't create a PyPI release for the abortive `bigquery-1.0.1` tag (or did somebody remove it?)  The tag, at lease, still exists [here](https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/bigquery-1.0.1).

**Comment by crwilcox** [comment]
I was trying to do a targeted patch, but our tooling doesn't really support this. The previous release was just wrong because of that so I am retagging with a the proper semver. Plus the previous failed to build on circle so I had to rebuild anyway :)

**Comment by tswast** [comment]
I'm surprised we still don't see the actual test names in the CircleCI output. I'd very much like to know which test is stalling.

**Comment by crwilcox** [comment]
Release is at https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/bigquery-1.1.0.

**Comment by crwilcox** [comment]
manually published to pypi

**Comment by tswast** [comment]
Thanks @crwilcox.

With the CI failure, I think a manual docs push may be needed, too. I'm only seeing 1.0 in the changelog there.

**Comment by crwilcox** [comment]
@tswast sure. I am not familiar with how push docs manually. Do you know or @jonparrott perhaps?

**Comment by tswast** [comment]
`nox -s docs` from root dir and overwrite the "latest" directory in the gh-pages branch. https://github.com/GoogleCloudPlatform/google-cloud-python/tree/gh-pages

**Pull request merged**
