### PR TITLE
Add scope for trace client

### PR DESCRIPTION
**Pull request by liyanhui1228**
Adding the scope needed when setting credentials file via `$GOOGLE_APPLICATION_CREDENTIALS`.

### CODE REVIEW

**Comment by liyanhui1228** [comment]
@dhermes Could you please do a release for the trace package? Thanks!

**Comment by dhermes** [comment]
@liyanhui1228 Can you draft some release notes, in the style of https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/storage-1.3.0?

You can run

```
$ git log -1 --pretty=%H 
c0bbf6d24bf43d8ca68f0af9c615734cd7607b89
$ git log trace-0.15.4..HEAD -- trace/
```

to decide what should go in the release notes

----

I'm not sure a release will be easy, `google-cloud-core` may confuse things. Let's hope not.

**Comment by liyanhui1228** [comment]
@dhermes The release notes can just be empty like what we did in last release :)
What problem will be caused by `google-cloud-core`?

**Comment by jonparrott** [comment]
We should always publish release notes when we make releases, even if the changes are trivial.

**Comment by liyanhui1228** [comment]
@jonparrott Thanks! I drafted the release note like below,

## Notable Implementation Changes

- Add scope for trace client, which fixes the issue when setting credentials file via `$GOOGLE_APPLICATION_CREDENTIALS`. (#4158)

## Dependencies

- Avoiding `grpcio==1.6.0` in deps. (#4096)
- Removing `googleapis-common-protos` from deps in non-`core` packages. (#4098)

**Comment by dhermes** [comment]
@liyanhui1228 I'd be fine leaving the deps changes out of the release notes. What about #3922? (It looks like @lukesneeringer intended there to be a `0.15.5` release but never managed one.)

**Comment by liyanhui1228** [comment]
@dhermes OK! I removed the dependencies notes, and added packaging note.

**Comment by liyanhui1228** [comment]
Friendly ping.

**Comment by dhermes** [comment]
I made https://github.com/GoogleCloudPlatform/google-cloud-python/tree/trace-cherry-pick to avoid being gated on `google-cloud-core`. In particular:

```diff
commit 863d293f16f7df1962a4a367b8bf913daefe02fe
Author: Danny Hermes <daniel.j.hermes@gmail.com>
Date:   Fri Oct 13 15:33:01 2017 -0700

    Rolling back the dependency update for trace.
    
    This is so that an "off-master" release can be done
    without being gated on a `google-cloud-core` release.

diff --git a/trace/setup.py b/trace/setup.py
index c14fbbe..8072778 100644
--- a/trace/setup.py
+++ b/trace/setup.py
@@ -9,7 +9,8 @@ from setuptools import setup, find_packages
 
 install_requires = [
     'google-gax>=0.15.7, <0.16dev',
-    'google-cloud-core[grpc] >= 0.27.1, < 0.28dev',
+    'googleapis-common-protos[grpc]>=1.5.2, <2.0dev',
+    'google-cloud-core >= 0.27.0, < 0.28dev',
 ]
 
 setup(
```

**Comment by liyanhui1228** [comment]
Thanks! So this release will be based on the `trace-cherry-pick` branch? Can we release it today?

**Comment by dhermes** [comment]
The branch is now deleted and immortalized as https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/trace-0.15.5.

This build (https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3757) should push to PyPI.

**Pull request merged**
