### PR TITLE
for streaming sample should have "stream=" param

### PR DESCRIPTION
**Pull request by yogeshg**
Sample class can take in content, source_uri or stream, should be stream here.
```
    :type content: bytes
    :param content: (Optional) Bytes containing audio data.

    :type stream: file
    :param stream: (Optional) File like object to stream.
```
the type is deduced using:
```sources = [content is not None, source_uri is not None, stream is not None]```

### CODE REVIEW

**Comment by yogeshg** [comment]
I signed it!
```
I signed it!
```

**Comment by yogeshg** [comment]
I signed it!

**Comment by dhermes** [comment]
LGTM. @daspecster LGTY?

**Comment by daspecster** [comment]
@dhermes yup!
Thanks @yogeshg!

**Comment by yogeshg** [comment]
@dhermes, @daspecster  my pleasure!
I also added an example for this use case in the samples repo. I was not sure how to write the test script for it though. You can help/advise me here:
https://github.com/GoogleCloudPlatform/python-docs-samples/pull/826

**Pull request merged**
