### PR TITLE
BQ: rename XJob.name to XJob.job_id.

### PR DESCRIPTION
**Pull request by tswast**
To go with all our other renames.

### CODE REVIEW

**Comment by tswast** [comment]
System tests running at https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3265

**Comment by lukesneeringer** [comment]
Let me know if you need/want an assist on that system test failure.

**Comment by tswast** [comment]
I think some of the failures are a few system tests got missed in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3959. I pushed a fix.

**Comment by tswast** [comment]
System tests will be available at https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3296

**Comment by tswast** [comment]
I still can't get the logs to load for the system tests, but they pass locally. Merging.

**Pull request merged**
