### PR TITLE
Remove orphaned _fixtures.py.

### PR DESCRIPTION
**Pull request by daspecster**
@dhermes, sorry I missed this. It slipped by me in one of the PRs when I was rebasing from the rename/moving tests.

### CODE REVIEW

**Comment by tseaver** [comment]
LGTM

**Comment by dhermes** [comment]
May also want to remove it from `run_pylint`:
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/d3e28ce8ae5bee1a637a11d11227d294cfa8302c/scripts/run_pylint.py#L41

**Comment by daspecster** [comment]
@dhermes, I just removed reference in `run_pylint.py`.

**Comment by dhermes** [comment]
LGTM to merge

**Pull request merged**
