### PR TITLE
Spanner: System test partial range

### PR DESCRIPTION
**Pull request by chemelnucfin**
Merge #4618 first.  I still need to test this.

### CODE REVIEW

**Comment by chemelnucfin** [comment]
Ugh, I wrote tests in a loop style before and it was not allowed.

**Comment by dhermes** [comment]
> Ugh, I wrote tests in a loop style before and it was not allowed.

Sorry to hear that. I am OK with it.

**Comment by tseaver** [comment]
FWIW, the reason I asked @chemelnucfin to remove them elsewhere is that the loops introduce a lot of noise, and make debugging failures harder:  those tests are "speed bumps" for readers.

**Comment by chemelnucfin** [comment]
I don't have a preference for either style.  I can see merits and drawbacks in both.

**Comment by dhermes** [comment]
@tseaver I somewhat agree with you, but the copy-pasta creates other issues.

I am 100% for switching to `pytest` style, then we can use `pytest.mark.parameterize` to have one test but multiple data.

**Pull request merged**
