### PR TITLE
Update auth.rst

### PR DESCRIPTION
**Pull request by thelostscientist**
I followed the documentation and this addition worked for me

### CODE REVIEW

**Comment by thelostscientist** [comment]
I signed it!

On Nov 12, 2017, at 3:49 PM, googlebot <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for your pull request. It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://cla.developers.google.com/ to sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

________________________________

  *   If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data<https://cla.developers.google.com/clas> and verify that your email is set on your git commits<https://help.github.com/articles/setting-your-email-in-git/>.
  *   If your company signed a CLA, they designated a Point of Contact who decides which employees are authorized to participate. You may need to contact the Point of Contact for your company and ask to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the project maintainer to go/cla#troubleshoot.
  *   In order to pass this check, please resolve this problem and have the pull request author add another comment and the bot will run again.

**Comment by dhermes** [comment]
@thelostscientist I think this may reflect an out-of-date install of some part of the tooling, not really something we want to document.

Can you point to something that explains why this is needed?

**Comment by thelostscientist** [comment]
@dhermes This was the only way I got the client to connect. Also, passing the path explicitly didn't work either.

**Comment by dhermes** [comment]
@thelostscientist Can you share the output of `gcloud version` and run `pip freeze | grep google`?

**Comment by thelostscientist** [comment]
@dhermes, I don't actually have the sdk (sdk), its not a requirement? Hence the comment
Here is the output of `pip freeze | grep google`
gapic-google-cloud-datastore-v1==0.15.3
gapic-google-cloud-error-reporting-v1beta1==0.15.3
gapic-google-cloud-logging-v2==0.91.3
gapic-google-cloud-pubsub-v1==0.15.4
gapic-google-cloud-spanner-admin-database-v1==0.15.3
gapic-google-cloud-spanner-admin-instance-v1==0.15.3
gapic-google-cloud-spanner-v1==0.15.3
google-auth==1.1.1
google-cloud==0.27.0
google-cloud-bigquery==0.26.0
google-cloud-bigtable==0.26.0
google-cloud-core==0.26.0
google-cloud-datastore==1.2.0
google-cloud-dns==0.26.0
google-cloud-error-reporting==0.26.0
google-cloud-language==0.27.0
google-cloud-logging==1.2.0
google-cloud-monitoring==0.26.0
google-cloud-pubsub==0.27.0
google-cloud-resource-manager==0.26.0
google-cloud-runtimeconfig==0.26.0
google-cloud-spanner==0.26.0
google-cloud-speech==0.28.0
google-cloud-storage==1.3.2
google-cloud-translate==1.1.0
google-cloud-videointelligence==0.25.0
google-cloud-vision==0.26.0
google-gax==0.15.15
google-resumable-media==0.2.3
googleapis-common-protos==1.5.3
grpc-google-iam-v1==0.11.4
proto-google-cloud-datastore-v1==0.90.4
proto-google-cloud-error-reporting-v1beta1==0.15.3
proto-google-cloud-logging-v2==0.91.3
proto-google-cloud-pubsub-v1==0.15.4
proto-google-cloud-spanner-admin-database-v1==0.15.3
proto-google-cloud-spanner-admin-instance-v1==0.15.3
proto-google-cloud-spanner-v1==0.15.3

**Comment by dhermes** [comment]
> I don't actually have the sdk (gcloud)

I see. If that's the case you definitely shouldn't be putting files in `~/.config/gcloud` (and we don't want to recommend that either).

Can you run `python -c 'import os; print(os.environ.get("GOOGLE_APPLICATION_CREDENTIALS"))'` to verify that the environment variable has been set correctly?

**Comment by thelostscientist** [comment]
/home/zd111111/google_project/PublicData-b8248066d7bc.json

**Comment by dhermes** [comment]
@thelostscientist Then it's unclear why `google.auth.default()` doesn't detect it. Can you show me a Python interpreter where you show `os.environ.get` succeeds but `google.auth.default()` fails?

At this point, I'm happy to help you debug why the env. variable doesn't work, but I want to close this PR. The advice in it is not something we actually want to give to users. (Though it works, it is a hack that uses hard-coded paths specific to the `gcloud` CLI.)

**Comment by thelostscientist** [comment]
cool, thanks!

**Pull request closed without merging**
