### PR TITLE
Release bigquery 1.5.0

### PR DESCRIPTION
**Pull request by tswast**
This pull request was generated using releasetool.

Close #5735

### CODE REVIEW

**Comment by tseaver** [comment]
@tswast I don't see the `bigquery-1.5.0` tag, nor an entry on the release page.

**Comment by tseaver** [comment]
Note that the PyPI release won't be done by CI without making / pushing the tag.

**Comment by tswast** [comment]
That's because the test hadn't finished running yet. It just failed. :-( https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/7549

Assigning to @crwilcox to cut the release manually.

**Comment by tseaver** [comment]
@tswast That CI run was against `master` (following the merge of this PR).  We *also* need to get a tag made and pushed, which will kick of another CI run for the tag:  *that* one will publish the release to PyPI (if it succeeds).  We also need to [create a Github release](https://github.com/GoogleCloudPlatform/google-cloud-python/releases/new) from the tag, and copy over the `1.5.0` changelog to it.

**Pull request merged**
