### PR TITLE
Release bigquery 1.4.0

### PR DESCRIPTION
**Pull request by tswast**
This pull request was generated using releasetool.

### CODE REVIEW

**Comment by tseaver** [comment]
LGTM.  The failure on `master` after the merge of #5602 is Bigtable-related (#5593).

**Comment by tswast** [comment]
Capitalization and imperative mode done in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5604/commits/505b1ec1a00586067236ea9144151dd2e80b3d9d

**Comment by tseaver** [comment]
@tswast AFAICT, the `bigquery-1.4.0` tag did not get created, nor was a release made here.  `1.4.0` *is* the current release on PyPI.  Did you push it to PyPI manually?

ISTM that the b022ca9d2176411c1d0a528da9ba820d24f0630e hash is correct for that tag.

**Comment by tswast** [comment]
@crwilcox Made the release manually, yes.

**Comment by tseaver** [comment]
OK, I tagged b022ca9 as `bigquery-1.4.0` locally, pushed the tag here, and [made the release](https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/bigquery-1.4.0).

**Pull request merged**
