### PR TITLE
Loading AVRO files from local filesystem.

### PR DESCRIPTION
**Pull request by tswast**
Adds an integration test for loading AVRO files.

Don't set the schema if none is provided ([patch](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3416#issuecomment-301537784)).

Closes https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3416.

### CODE REVIEW

**Comment by tseaver** [comment]
@tswast Can you push your branch to this repository, so that the system test actually gets run by the CI before we merge?

**Comment by dhermes** [comment]
@tswast If you don't have `push` privileges one of us can do it

**Comment by tseaver** [comment]
Also,  @tweeter0830 [reported](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3416#issuecomment-301586728) that the patch did not fix the issue with uploading AVRO data.

**Comment by tswast** [comment]
I saw that, but I was not able to reproduce the issue after the patch.

**Comment by tswast** [comment]
Hmm, I see that this change made the Avro load test pass, but now the CSV load test fails.
https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1920

**Comment by tseaver** [comment]
@tswast That is weird, as the testcase clearly sets the schema on the table:  it should be passing the schema along.

**Comment by tswast** [comment]
We missed the "fields" property of the schema object in the patch. Seems to be running fine now. https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1922

**Comment by tseaver** [comment]
I've pushed the branch here (as `tswast-bq-3146`) to get the system tests running under CI before merging.

**Comment by tseaver** [comment]
BQ system tests are [green on Circle CI](https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1925?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

**Pull request merged**
