### PR TITLE
Cut 0.20.1 datastore release.

### PR DESCRIPTION
**Pull request by dhermes**
/cc @jonparrott 

Note we still don't have an automated story for `twine` uploads (and can't really get one until we straighten out tags)

### CODE REVIEW

**Comment by dhermes** [comment]
@tseaver Not sure what the right move is for getting the release note content. Looking at the history for the `datastore/` root dir:

https://github.com/GoogleCloudPlatform/google-cloud-python/commits/master/datastore

it seems like #2423 and #2496 are the only relevant changes.

From the CLI:

```
$ git log umbrella-0.20.0.. datastore/
```

it indicates #2423 was already in the `0.20.0` release. ([Confirmed][1].)

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/umbrella-0.20.0/datastore/google/cloud/datastore/connection.py#L318-L321

**Comment by tseaver** [comment]
*Draft of release note:*

## Datastore 0.20.1

- Map gRPC errors in `datastore.connection.Connection.run_query` onto `google.cloud.exceptions`. (#2496)

**Comment by tseaver** [comment]
LGTM

**Comment by dhermes** [comment]
@tseaver What tag should I push?

**Comment by dhermes** [comment]
I just pushed https://pypi.python.org/pypi/google-cloud-datastore/0.20.1 via

```
$ git worktree add ../do-release origin/master
$ cd ../do-release/datastore
$ python setup.py sdist bdist_wheel
$ twine upload dist/*
```

**Comment by tseaver** [comment]
@dhermes I guess `0.20.1-datastore`?

**Comment by tseaver** [comment]
@dhermes `0.20.1-datastore`, I guess?  I would prefer `datastore-0.20.1`.  Maybe we could tag it twice, once for "real" semantics and once to make RTD happy?

**Comment by dhermes** [comment]
@tseaver both are PEP420 invalid. The "best" valid choice is `'0.20.1+datastore'`.

```python
>>> from packaging.version import Version
>>> v = Version('0.20.1-datastore')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/packaging/version.py", line 202, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
packaging.version.InvalidVersion: Invalid version: '0.20.1-datastore'
>>> v = Version('datastore-0.20.1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/packaging/version.py", line 202, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
packaging.version.InvalidVersion: Invalid version: 'datastore-0.20.1'
```

-----

I am pretty :-1: on tagging twice just for name aliasing. However, I was under the impression that in #2462 we said we might ignore the `stable` for non `google-cloud-core` releases?

**Comment by tseaver** [comment]
If we tag the umbrella project with PEP-420 compatible tags at "appropriate" points, that would let us trigger RTD rebuilds for `stable`.  We could even have a page listing the latest releases of the sub-projects.

**Comment by dhermes** [comment]
Not sure what you mean here. We can only tag one project / GitHub repo. It seems like you're suggesting having docs only tags separate from release only tags (on our `git` repo), yes?

**Comment by tseaver** [comment]
If we tag sub-project releases in a way that doesn't cause RTD to rebuild `stable`, we can still generate tags which *do* trigger a `stable` rebuild on RTD for the "umbrella" package.

**Comment by dhermes** [comment]
So you're saying `stable` would only be built for releases of `google-cloud`? Is this "incorrect" in the sense that a bound like `datastore >= 0.20.0` means that both `0.20.0` and `0.20.1` are valid in the `stable` docs (and so we should have the latest one released)?

**Pull request merged**
