### PR TITLE
Video Intelligence v0.27.0

### PR DESCRIPTION
**Pull request by lukesneeringer**
This PR is an amalgamation of:

  * [x] Removal of the outdated auto-gen surface (#3975)
  * [x] Addition of the new auto-gen surface (#3976)
  * [x] Addition of v1beta2 (#3978)
  * [x] Change of default version to v1beta2 (#3979)
  * [x] Version number bump to 0.27.0 (#3980)

### CODE REVIEW

**Comment by dhermes** [comment]
@lukesneeringer all commits into the `video-intelligence` branch have already been reviewed?

**Comment by lukesneeringer** [comment]
Thus far, but the three unchecked items have not been done/reviewed yet. Working on them now.

**Comment by lukesneeringer** [comment]
@dhermes I now intend to merge this once CI passes.

**Comment by dhermes** [comment]
:+1: :tada:

**Pull request merged**
