### PR TITLE
Audio Logging and Recognition Metadata.

### PR DESCRIPTION
**Pull request by lukesneeringer**

### CODE REVIEW

**Comment by lukesneeringer** [comment]
Do not merge until March 30. Tagging as such.

**Comment by lukesneeringer** [comment]
This has a backwards incompatible change (in Python only), which is that `google.cloud.speech_v1p1beta1.proto.speech_pb2.SpeechStub` is gone. It is in `google.cloud.speech_v1p1beta1.proto.speech_pb2_grpc` now.

This is in a beta module so we are okay; we will need to determine what our path is when it bleeds into GA modules (it is a back-incompat change in protoc itself).

**Comment by chemelnucfin** [comment]
@lukesneeringer ok to merge now?  It's after March 30th.

**Comment by danoscarmike** [comment]
@chemelnucfin please do not merge this one.  I will update by end of week.

**Comment by chemelnucfin** [comment]
@danoscarmike got it.

**Comment by danoscarmike** [comment]
@chemelnucfin @lukesneeringer we're approved to merge.

**Pull request merged**
