### PR TITLE
Updating all affected packages after google-cloud-core update.

### PR DESCRIPTION
**Pull request by dhermes**

### CODE REVIEW

**Comment by dhermes** [comment]
## `google-cloud-bigquery==0.26.0`

Filler

## `google-cloud-bigtable==0.26.0`

Filler

## `google-cloud-core==0.26.0`

Filler

## `google-cloud-datastore==1.2.0`

Filler

## `google-cloud-dns==0.26.0`

Filler

## `google-cloud-error-reporting==0.26.0`

Filler

## `google-cloud-language==0.27.0`

Filler

## `google-cloud-logging==1.2.0`

Filler

## `google-cloud-monitoring==0.26.0`

Filler

## `google-cloud-pubsub==0.27.0`

Filler

## `google-cloud-resource-manager==0.26.0`

Filler

## `google-cloud-runtimeconfig==0.26.0`

Filler

## `google-cloud-spanner==0.26.0`

Filler

## `google-cloud-speech==0.28.0`

Filler

## `google-cloud-storage==1.3.0`

Filler

## `google-cloud-translate==1.1.0`

Filler

## `google-cloud-vision==0.26.0`

Filler

## `google-cloud==0.27.0`

Feature releases for to the following packages:

- [`google-cloud-core==0.26.0`][1]

Dependency-only / user-invisible changes to the following packages:

- [`google-cloud-bigquery==0.26.0`][2]
- [`google-cloud-bigtable==0.26.0`][3]
- [`google-cloud-datastore==1.2.0`][4]
- [`google-cloud-dns==0.26.0`][5]
- [`google-cloud-error-reporting==0.26.0`][6]
- [`google-cloud-language==0.27.0`][7]
- [`google-cloud-logging==1.2.0`][8]
- [`google-cloud-monitoring==0.26.0`][9]
- [`google-cloud-pubsub==0.27.0`][10]
- [`google-cloud-resource-manager==0.26.0`][11]
- [`google-cloud-runtimeconfig==0.26.0`][12]
- [`google-cloud-spanner==0.26.0`][13]
- [`google-cloud-speech==0.28.0`][14]
- [`google-cloud-storage==1.3.0`][15]
- [`google-cloud-translate==1.1.0`][16]
- [`google-cloud-vision==0.26.0`][17]

PyPI: https://pypi.org/project/google-cloud/0.27.0/

[1]: https://pypi.org/project/google-cloud/0.27.0/


[1]: https://pypi.org/project/google-cloud-core/0.26.0/
[2]: https://pypi.org/project/google-cloud-bigquery/0.26.0/
[3]: https://pypi.org/project/google-cloud-bigtable/0.26.0/
[4]: https://pypi.org/project/google-cloud-datastore/1.2.0/
[5]: https://pypi.org/project/google-cloud-dns/0.26.0/
[6]: https://pypi.org/project/google-cloud-error-reporting/0.26.0/
[7]: https://pypi.org/project/google-cloud-language/0.27.0/
[8]: https://pypi.org/project/google-cloud-logging/1.2.0/
[9]: https://pypi.org/project/google-cloud-monitoring/0.26.0/
[10]: https://pypi.org/project/google-cloud-pubsub/0.27.0/
[11]: https://pypi.org/project/google-cloud-resource-manager/0.26.0/
[12]: https://pypi.org/project/google-cloud-runtimeconfig/0.26.0/
[13]: https://pypi.org/project/google-cloud-spanner/0.26.0/
[14]: https://pypi.org/project/google-cloud-speech/0.28.0/
[15]: https://pypi.org/project/google-cloud-storage/1.3.0/
[16]: https://pypi.org/project/google-cloud-translate/1.1.0/
[17]: https://pypi.org/project/google-cloud-vision/0.26.0/

**Comment by dhermes** [comment]
@tseaver Can you update the [Spanner release][1]? It seemed a bit too daunting.

@tswast Ditto on [BigQuery][2]

```
$ git log bigquery-0.25.0..bigquery-0.26.0 --reverse -- bigquery/
$ git log spanner-0.25.0..spanner-0.26.0 --reverse -- spanner/
```

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/spanner-0.26.0
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/bigquery-0.26.0

**Comment by tswast** [comment]
I've updated the [release notes for BigQuery](https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/bigquery-0.26.0).

**Comment by dhermes** [comment]
Thanks a lot Tim! You the best!

**Pull request merged**
