### PR TITLE
Cut version 0.22.1 of translation API.

### PR DESCRIPTION
**Pull request by daspecster**
This releases the branding update for Google Cloud Translation from #2863.

```
git log translate-0.22.0..HEAD translate
```
produced

```
2f75184 Update Translation API branding.
```

### CODE REVIEW

**Comment by dhermes** [comment]
@daspecster I cut #2866 because @omaray asked me too. I am big time :-1: on trigger-happy releasing from just a single PR. Is there a reason for this release to happen now rather than after the "usual cadence"?

**Comment by daspecster** [comment]
@dhermes I wasn't prompted. I just thought the `blocking beta` label in the issue would be a reason to get this out.

I'm good with closing this unless otherwise prompted to release it.

**Comment by dhermes** [comment]
Ha good call. I forgot about the scary red label. @danoscarmike WDYT?

**Comment by dhermes** [comment]
@daspecster Let's not block on @danoscarmike any longer. Go ahead and cut your release (or close this PR).

**Comment by daspecster** [comment]
@dhermes ok, I'm going to close it since Translate hasn't been brought up as being full on beta yet AFAIK. So might as well let this go with the next release, unless someone says otherwise.

**Pull request closed without merging**
