### PR TITLE
Add spanner system tests:

### PR DESCRIPTION
**Pull request by tseaver**
- Bind timestamp.
- Bind string array.
- Bind empty string array.
- Bind string to null.
- Query returning array of -Inf, +Inf, NaN.

Toward #4364.

### CODE REVIEW

**Comment by tseaver** [comment]
@dhermes I split the "transfinite" cases out into a separate method.  Code is otherwise unchanged:  I will merge when Circle is green.

**Comment by tseaver** [comment]
Rebased to pick up hardening from merged #4374.

**Comment by dhermes** [comment]
> Also, may I suggest to use origin (your own) for branching instead of upstream (gcp) to keep branches tidy?

This was intentional by @tseaver. When we push to the upstream remote, the system tests get run (they get skipped on PR builds otherwise).

But good advice otherwise!

**Comment by chemelnucfin** [comment]
@dhermes wait, so if I make a PR the system tests don't run on CI?

**Comment by dhermes** [comment]
@chemelnucfin That's correct. It's a security concern, since **anyone** can send a PR. Check out one of your builds, it'll say "skipped" by the system tests.

**Pull request merged**
