### PR TITLE
Storage: Relax project id regex due to issue

### LINKED ISSUE #4447: Storage: This doesn't match our existing project ID: hello-rightscale002
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/4b107613b0fcf139569504e9d44fa4a0793b4fd0/storage/google/cloud/storage/notification.py#L31

### PR DESCRIPTION
**Pull request by chemelnucfin**
Closes #4447

### CODE REVIEW

**Comment by dhermes** [comment]
@chemelnucfin Can you provide a link to documentation which specifies what an ID should look like? This doesn't seem generic enough.

**Comment by chemelnucfin** [comment]
I haven't been able to find it yet.  This was just to solve the issue for
the user instead of having them wait.  Maybe I can open another more
generic issue while I look.

**Comment by dhermes** [comment]
> just to solve the issue for the user instead of having them wait

It doesn't make sense to do that without understanding the fix. For that particular user, we can just recommend a monkey patch:

```python
import re

from google.cloud.storage import notification


notification._PROJECT_PATTERN = r'(?P<project>[a-z]+-[a-z]+\d+)'
notification._TOPIC_REF_PATTERN = notification._TOPIC_REF_FMT.format(
    notification._PROJECT_PATTERN,
    notification._TOPIC_NAME_PATTERN)
notification._TOPIC_REF_RE = re.compile(notification._TOPIC_REF_PATTERN)
```

**Comment by chemelnucfin** [comment]
got it.  I'll see if I can find the project-id somewhere.

**Pull request closed without merging**
