### PR TITLE
Revert PR 2336 and upgrade to google-gax>=0.14.1

### PR DESCRIPTION
**Pull request by dhermes**
FYI @geigerj and @bjwatson

### CODE REVIEW

**Comment by daspecster** [comment]
Is `GrcpRendezvous` used somewhere else that would prevent the removal of that class from `exceptions.py`? (there are some pylint overrides around it's definition.)

**Comment by dhermes** [comment]
@daspecster I'm not sure what you're asking. You want the alias removed? Or you'd like the alias in another location? Are you up to speed on the discussion in #2156?

**Comment by tseaver** [comment]
LGTM

**Comment by daspecster** [comment]
@dhermes, yeah I was asking if the [alias](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/6b5223d738e0193e3a31dbebbfcaddd5600205d8/google/cloud/exceptions.py#L35) could be removed.

**Comment by tseaver** [comment]
Hmmm, we are still using the alias:

```bash
$ git grep GrpcRendezvous
oogle/cloud/bigtable/row_data.py:    :type response_iterator: :class:`~google.cloud.exceptions.GrpcRendezvous`
google/cloud/bigtable/table.py:        :rtype: :class:`~google.cloud.exceptions.GrpcRendezvous`
google/cloud/datastore/connection.py:from google.cloud.exceptions import GrpcRendezvous
google/cloud/datastore/connection.py:        except GrpcRendezvous as exc:
google/cloud/exceptions.py:GrpcRendezvous = _Rendezvous
system_tests/bigtable.py:    from google.cloud.exceptions import GrpcRendezvous
system_tests/bigtable.py:        retry = RetryErrors(GrpcRendezvous,
unit_tests/_testing.py:        from google.cloud.exceptions import GrpcRendezvous
unit_tests/_testing.py:        return GrpcRendezvous(exc_state, None, None, None)
unit_tests/datastore/test_connection.py:        from google.cloud.exceptions import GrpcRendezvous
unit_tests/datastore/test_connection.py:        exc = GrpcRendezvous(exc_state, None, None, None)
unit_tests/datastore/test_connection.py:        from google.cloud.exceptions import GrpcRendezvous
unit_tests/datastore/test_connection.py:        exc = GrpcRendezvous(exc_state, None, None, None)
unit_tests/datastore/test_connection.py:        self._commit_failure_helper(exc, GrpcRendezvous)
```

**Comment by daspecster** [comment]
Thanks @tseaver I should have grepped that.

Those would be candidates for this change as well right?

**Comment by tseaver** [comment]
datastore and bigtable don't use GAX.

**Comment by dhermes** [comment]
What @tseaver said. The alias is still "required" in the sense that we still need to catch a `_Rendezvous` in the Bigtable and Datastore implementations.

**Pull request merged**
