### PR TITLE
Firestore: Allow document get to be error free

### PR DESCRIPTION
**Pull request by chemelnucfin**
@dhermes ?

### CODE REVIEW

**Comment by dhermes** [comment]
@chemelnucfin I added a "do not merge" label since this is for discussion.

PS Don't forget to label PRs (i.e. "Firestore" here).

**Comment by dhermes** [comment]
A few very high-level comments:

- I **very much** don't like the `raise_error` keyword. I would prefer always raise or never raise, not this "both are OK" approach
- It didn't occur to me how easy it'd be to return a non-existent `DocumentSnapshot`
- I'm still not sure it's broke, so "if it ain't broke, don't fix it", might still apply

I'd like to see what @jonparrott thinks as far as "idiomatic"-ness

**Comment by jonparrott** [comment]
Agreed that it should be either or and not both, from zen of Python:

> There should be one-- and preferably only one --obvious way to do it.

This really just boils down to one question:

It is a common thing in Firestore to get an empty/nonexistent document and not care? If yes, then we should return a empty `DocumentSnapshot`, if no, then we should raise an exception.

**Comment by dhermes** [comment]
@jonparrott For context #4530 is the issue where this is being discussed (see @chemelnucfin's branch name).

**Comment by dhermes** [comment]
@chemelnucfin Just noticed "Declare target packages" in your build picked up all the packages. This means your PR is behind `master`. Builds will be much faster if you stay rebased against the latest version of `master`.

**Comment by chemelnucfin** [comment]
Seems like there's not much interest in carrying this forward.

**Pull request closed without merging**
