### PR TITLE
Moving bytes signing helpers from `core` to `storage`.

### PR DESCRIPTION
**Pull request by dhermes**
This is part of `@jonparrott`'s effort to slim down / stabilize `core`.

-----

Temporarily labeled "do not merge" so we can discuss "churn" first.

### CODE REVIEW

**Comment by tseaver** [comment]
Wouldn't it make more sense to base this on #3667?  For instance, at that point, you could entirely remove the `credentials` module from `core`.

**Comment by dhermes** [comment]
@tseaver I'm trying to reduce burden on reviewers by making the PR small.

**Comment by tseaver** [comment]
Yeah, but then we have to review a *third* PR which just removes that module?  The only thing gonna be left in it after these two are merged is the copyright comment.

**Comment by dhermes** [comment]
@tseaver I plan on rebasing the one that gets merged 2nd.

**Pull request merged**
