### PR TITLE
Prep storage-1.11.0 release.

### LINKED ISSUE #5855: Request to release GCS Python library
Hi,

Is it possible to release the Storage client library for Python?

I'd like the new method `get_service_account_email` to be available. Unless there exist concerns.

### PR DESCRIPTION
**Pull request by tseaver**
Closes #5855.

### CODE REVIEW

**Comment by tseaver** [comment]
@crwilcox [Test failures here](https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/7818) due to #5852.

**Comment by frankyn** [comment]
Recommendation: release after this is resolved.

**Comment by tseaver** [comment]
Rebased and updated changelog after landing #5860.  Fingers crossed.

**Comment by tseaver** [comment]
[Release is created](https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/storage-1.11.0).

**Comment by frankyn** [comment]
Thanks @tseaver!

**Comment by tseaver** [comment]
[Distributions pushed to PyPI](https://pypi.org/project/google-cloud-storage/1.11.0/)

**Pull request merged**
