### PR TITLE
Spanner: minor typo 

### PR DESCRIPTION
**Pull request by chemelnucfin**
- switched positive and negative infinities maintaining order [-inf, +inf, NaN]

### CODE REVIEW

**Comment by dhermes** [comment]
1. I'll defer to @tseaver for review here
1. Please use more descriptive "subject" lines for your PRs (adding `Spanner` doesn't help)
1. This doesn't seem **that** minor, you are actually changing the code ("minor typo" seems to me like it'd be "persom" -> "person")

**Comment by chemelnucfin** [comment]
@dhermes
2.  Noted.
3.  It actually was just a change from the comment +inf to -inf and vice
versa, but I switched the order.  So the diff seemed like it changed the
code..

**Comment by dhermes** [comment]
> So the diff seemed like it changed the code

My apologies

**Comment by chemelnucfin** [comment]
@dhermes no worries!  I appreciate all your comments.

**Pull request merged**
