### PR TITLE
Running restricted set of unit tests on Travis PR.

### PR DESCRIPTION
**Pull request by dhermes**
**NOTE**: Has #2475 as diffbase.

### CODE REVIEW

**Comment by daspecster** [comment]
@dhermes this has a conflict too. Otherwise LGTM.

**Comment by dhermes** [comment]
@daspecster I just rebased and it seemed to fix itself?

**Comment by dhermes** [comment]
Build time down from 20 minutes to about 7.5 minutes. But it used to be consistently under 4, so I still have work to do.

**Comment by tseaver** [comment]
I don't see any special handling for changes in `core/` -- because it is a dependency for everything else, should we be falling back to running all tests when any change happens there?

**Comment by dhermes** [comment]
@tseaver I've got a change coming down the pipe which computes a package dependency graph and then follows the tree to populate a more-full list of changes. Thanks for being heads up!

**Pull request merged**
