### PR TITLE
Bump core version number

### PR DESCRIPTION
**Pull request by lukesneeringer**

### CODE REVIEW

**Comment by lukesneeringer** [comment]
Emergency due to Pub/Sub. Skipping approval.

**Comment by dhermes** [comment]
LGTM

**Comment by dhermes** [comment]
Still LGTM

**Comment by dhermes** [comment]
"Previous" tags 

- `0.27.0`
- `bigquery-0.26.0`
- `bigtable-0.26.0`
- `datastore-1.2.0`
- `dns-0.26.0`
- `error-reporting-0.26.0`
- `language-0.27.0`
- `logging-1.2.0`
- `monitoring-0.26.0`
- `resource-manager-0.26.0`
- `runtimeconfig-0.26.0`
- `spanner-0.26.0`
- `speech-0.28.0`
- `storage-1.3.2`
- `translate-1.1.0`
- `videointelligence-0.25.0`
- `vision-0.26.0`

This guys is b0rken:

- `pubsub-0.28.0`

**Pull request merged**
