### PR TITLE
Making base connection module non-public and making connection attribute non-public

### PR DESCRIPTION
**Pull request by dhermes**
I have held off on renaming `google.cloud.${PACKAGE}.connection` to `_http` for the 5 packages in #2690, but I can do that in this PR if desired. The PR is already pretty large though.

### CODE REVIEW

**Comment by dhermes** [comment]
@tseaver PTAL?

**Comment by tseaver** [comment]
Hmm, I thought we'd approved this already.

**Comment by dhermes** [comment]
You're probably thinking about #2690. Shall I merge then?

**Comment by tseaver** [comment]
Yes.

**Pull request merged**
