### PR TITLE
BigTable: add "end_inclusive" flag to yield_rows

### PR DESCRIPTION
**Pull request by tomp-raycatch**
Modify the signature of "yield_rows" to match "read_rows".

### CODE REVIEW

**Comment by tomp-raycatch** [comment]
I signed it!

**Comment by tseaver** [comment]
@tomp-raycatch Thanks for the patch!  In order to merge, the PR also needs to add / update unit tests in order to exercise passing the `end_inclusive` parameter to `yield_rows`.

**Comment by tomp-raycatch** [comment]
@tseaver 

There is no existing test to update for `yield_rows` (at least not that is mocking out the call to `_create_row_request` in order to assert it's arguments)

I've spent a few hours trying to add one, based on `test_read_rows`. It's not simple, and I think it's outside the scope of this PR.

BTW coverage is still at 100%

**Comment by sduskis** [comment]
Our team is going to expand the capabilities of yield rows as it relates to row key/range selection.  I would like to hold off on merging this PR so that we can develop an API that implements a wider variety of cases.

**Comment by tomp-raycatch** [comment]
Okay.
So I'm closing this pull request.

For reference in case somebody is stuck at my situation - what I've ended up doing is this:
```python
    partial_rows_data = table.read_rows(
            start_key=start_key,
            end_key=end_key,
            limit=limit,
            filter_=filter_,
            end_inclusive = end_inclusive
    )
    for row in partial_rows_data._generator.read_rows():
        yield ( row.row_key, row )
```

`partial_rows_data._generator` is a `YieldRowsData` so besides the access to the 'private' attribute, it's pretty much the same as `yield_rows()`.

**Pull request closed without merging**
