### PR TITLE
Adding new Travis key.

### PR DESCRIPTION
**Pull request by dhermes**
PR #2288 broke the Travis build since the key stored (from 2014) didn't have the project ID as a value.

Also adding better instructing about the encrypted file.

### CODE REVIEW

**Comment by dhermes** [comment]
I've also deleted the old and no longer used file encryption env. vars:

- `encrypted_a1b222e8c14d_key`
- `encrypted_a1b222e8c14d_iv`
- `encrypted_d4f2fba7a94f_key`
- `encrypted_d4f2fba7a94f_iv`

**Comment by dhermes** [comment]
Merging now to stop the permanent state of b0rken-ness. @tseaver and @daspecster please LMK if the "emergency" merge was problematic.

**Comment by dhermes** [comment]
Was ready to say "Yay we're green!" but then:
https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/158880190

It's just #2080.

**Comment by tseaver** [comment]
We could merge #2248 to make that one go away. ;)

**Pull request merged**
