### PR TITLE
Python GAPIC: Bigquerydatatransfer v1

### PR DESCRIPTION
**Pull request by ethanbao**

### CODE REVIEW

**Comment by ethanbao** [comment]
Gently ping

**Comment by dhermes** [comment]
@ethanbao Who is the ping intended for? It's unclear to me who a reviewer would be here.

**Comment by ethanbao** [comment]
I meant @lukesneeringer

**Comment by lukesneeringer** [comment]
@landrito is tackling this one to prove out the playbook, and intends to go from scratch.

**Pull request closed without merging**
