### PR TITLE
clarify that modify_ack_deadline resets the deadline

### PR DESCRIPTION
**Pull request by opyate**
[source request](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4648#issuecomment-362427757)

### CODE REVIEW

**Comment by opyate** [comment]
CLA signed.

**Comment by jonparrott** [comment]
@kir-titievsky do you mind taking a look to see if this satisfies your request?

**Comment by kir-titievsky** [comment]
@jonparrott: lgtm.
@opyate Thank you!

**Comment by opyate** [comment]
@googlebot yes, I consent.

**Pull request merged**
