### PR TITLE
Fixes typo

### PR DESCRIPTION
**Pull request by mlissner**
Noticed this in the docs. Small, but every bit helps.

### CODE REVIEW

**Comment by daspecster** [comment]
@mlissner thanks!
This looks good to me. I'll merge once the CLA is signed.

**Comment by mlissner** [comment]
Well, I should have seen that coming! Anyway, I can't sign this because the CLA server is failing:

screenshot from 2016-10-25 07-42-16

Dunno what to tell you. I'm running Firefox Nightly, but that's *rarely* an issue.

**Comment by mlissner** [comment]
> CLAs look good, thanks!

Weird, it never once submitted successfully.

**Comment by tseaver** [comment]
@daspecster We can ignore the Circle CI failures for now (I've asked @dhermes if we can disable it until its config is fixed).

**Pull request merged**
