### PR TITLE
Fix doc build by swapping install order

### PR DESCRIPTION
**Pull request by jonparrott**

### CODE REVIEW

**Comment by dhermes** [comment]
This is a lose-lose, sadly. @lukesneeringer fixed this previously, but I undid it in #3730.

The reason: if our source tree depends on packages that are not yet on PyPI, the build won't work.

**Comment by jonparrott** [comment]
I see - ideally we should just stop installing the umbrella package for docs.

**Comment by dhermes** [comment]
Yeah great point. It's not necessary? Or maybe `docs/conf.py` checks the version of `google-cloud` via `pkg_resources`?

**Comment by jonparrott** [comment]
`docs/conf.py` checks the version via pkg_resources. We could use the core version instead.

**Comment by dhermes** [comment]
That seems like the "least worst" strategy. The version used in the user agent comes from `google-cloud-core`.

**Comment by jonparrott** [comment]
I have a day of meetings - if you're willing (and able) to do that today I'll review.

**Comment by dhermes** [comment]
On it

**Pull request merged**
