### PR TITLE
Regenerate gapic for Speech API, remove deprecated manual layer

### PR DESCRIPTION
**Pull request by lukesneeringer**
* Removes the deprecated manual layer.
  * Institutes new timeouts.
  * Removes gax.

### CODE REVIEW

**Comment by jonparrott** [comment]
Didn't speech have a small partial gapic for streaming recognize?

**Comment by chemelnucfin** [comment]
@lukesneeringer, what was confusing to me yesterday was that there are two `SpeechClients`, one was in `speech/google/cloud/gapic` and one was in `speech/speech_v1` which imports the gapic one, which @jonparrott cleared up for me.

This still seems to have two, except that `speech/google/cloud/gapic` has been moved to `speech/google/cloud/speech_v1/gapic`, which can possibly be even more confusing.  I could be wrong though.

**Comment by lukesneeringer** [comment]
> Didn't speech have a small partial gapic for streaming recognize?

speech_v1/helpers.py

**Comment by jonparrott** [comment]
Cool, LGTM

**Comment by lukesneeringer** [comment]
> This still seems to have two

Yeah, that is fine. It is an unusual situation but the docs make pretty clear what to use.
Also, they are essentially identical outside of streaming.

**Comment by lukesneeringer** [comment]
Tagging `do not merge` based on a last-minute request from the API team.

**Comment by lukesneeringer** [comment]
Reverted the config; waiting on CI.

**Pull request merged**
