### PR TITLE
Python GAPIC: Dlp v2beta1

### PR DESCRIPTION
**Pull request by ethanbao**

### CODE REVIEW

**Comment by ethanbao** [comment]
Gently ping.

**Comment by ethanbao** [comment]
@lukesneeringer

**Comment by lukesneeringer** [comment]
This already exists.

**Comment by ethanbao** [comment]
Just to confirm. I know DLP v2beta1 exists, but could be built using old protos. Can you confirm that DLP python now uses the latest proto and yamls from googleapis/googleapis repo?

**Pull request closed without merging**
