### PR TITLE
BigQuery add default location to client

### LINKED ISSUE #5148: BigQuery: Add default location to Client
It is potentially quite cumbersome to pass in a `location` parameter to nearly every API request method. It would be nice to set a default `location` when you create a client to be used when creating datasets or jobs.

### PR DESCRIPTION
**Pull request by tseaver**
Plumb it through as the default-default for all `Client` methods taking an optional `location`.

Closes #5148.

### CODE REVIEW

**Comment by tseaver** [comment]
@tswast Two questions:

- Should `DatasetReference` grow location support?  It looks like the `location` field is present in [`datasets.list` responses](https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets/list#datasets.location), for instance.  It seems the natural point to inject `location`, e.g.:

```python
ds_ref = client.dataset(dataset_id, location='EU')
dataset = client.create_dataset(ds_ref)
```

where the client would use its own location as the default-default.

- While poking at that question, I looked `Table.location`:  ISTM that `Table` should *not* allow assignment to `location`:  the field is marked as read-only in the [API docs](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#location).

**Comment by tswast** [comment]
> Should DatasetReference grow location support?

It does feel like the natural place for location, although for legacy reasons the actual [REST resource](https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets) doesn't put location in the `DatasetReference` type. I hesitate to have extra info floating around in the Python DatasetReference class that doesn't correspond to the actual API resource.

I'll ask the BigQuery product eng folks if they plan to add a location parameter to other operations such as [Dataset GET](https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets/get) if so, let's move ahead with adding it to DatasetReference.

> ISTM that Table should not allow assignment to location: the field is marked as read-only in the API docs.

Correct. Table inherits the location from the dataset it belongs to and cannot be overridden.

**Comment by tseaver** [comment]
> I'll ask the BigQuery product eng folks if they plan to add a location parameter to other operations such as Dataset GET if so, let's move ahead with adding it to DatasetReference.

Hmm, `location` is [already documented](https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets#location) as a member of the `Dataset` resource, returned by `datasets.get`.

> Such a change is unlikely to happen because `project.dataset` is a globally-unique identifier. Let's just populate the default location at `create_dataset()` time, as that is the only operation that requires a location for Datasets.

Wilco.

> Table inherits the location from the dataset it belongs to and cannot be overridden.

Tracked in #5686.

**Comment by tswast** [comment]
> Hmm, location is already documented as a member of the Dataset resource, returned by datasets.get

That's true. What I mean is that dataset.get doesn't have a location URL parameter, as was recently added to jobs.get.

**Comment by tseaver** [comment]
@dpebot Please merge on green.

**Pull request merged**
