### PR TITLE
Cutting google-cloud-core==0.23.0.

### PR DESCRIPTION
**Pull request by dhermes**
/fyi @lukesneeringer @bjwatson 

Working on release notes now

### CODE REVIEW

**Comment by dhermes** [comment]
```
$ git log --pretty=%H -1 cut-core-0.23.0
eb86509da018137efe6790975fee1890084b4b45
$ # 15 new commits to core
$ git log --pretty=%H core-0.22.1..cut-core-0.23.0 -- core/ | wc
15
```

Actual PRs that made changes to core: #2952, (#2870, #2968 and #2970), #2907, #2946, #2939, #2944 

-   #2952: moving in a shared helper from Bigtable (though in the non-public `google.cloud._helpers`, was also non-public in Bigtable before the move)
-   #2944: updated user facing documentation (worth noting, but not a code change)
-   #2939: test-only change
-   #2946: code hygiene 
-   #2968: Rename `JSONClient` to `ClientWithProject`, but class is not part of public interface (i.e. `google.cloud._http` is non-public)
-   #2907: `extra_options` kwarg added to `make_secure_channel()` to allow Bigtable to receive larger payloads (the options are gRPC "headers")
-   #2870 and #2970: Remove most of the responsiblity of `Connection` classes (though these are non-public, i.e. in `google.cloud._http`).
    - #2970: Made it so that `Connection` no longer holds state (it's old properties are just proxies to state held on the `Client()` now).
    - #2870: Made it so that `Connection()` instances are created in `Client()` subclasses rather than in the base class. This way, implementations can re-factor the way transports (HTTP and gRPC) are created without impacting other packages.

**Comment by lukesneeringer** [comment]
@dhermes Thank you for doing this.

**Comment by dhermes** [comment]
@lukesneeringer Is that "Thank you" equal to "LGTM"?

**Comment by lukesneeringer** [comment]
Yes. LGTM.

**Comment by dhermes** [comment]
See release notes: https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/core-0.23.0
This build will be pushing to PyPI: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/841

ISTM this release should spawn at least a few releases of packages. BigTable definitely comes to mind.

@tseaver @daspecster @lukesneeringer any other packages that have been "blocked" on release waiting for `core`? Or if not blocked, just packages that could use a release? (Note that the major version bump in `google-cloud-core` means we can't bump the umbrella `google-cloud` package until all packages have gotten a major release with the updated dependency.)

**Comment by daspecster** [comment]
Nothing that I know of. I would like to get vision and speech cut once the outstanding PRs are merged and possible a couple more.

**Comment by tseaver** [comment]
We've had a long-pending request for a release of one package (I thought `google-cloud-logging` but can't find the issue).

**Comment by dhermes** [comment]
@tseaver Maybe you're thinking of the comments at the end of #2880

**Comment by tseaver** [comment]
Yeah, that looks like it.  For some reason, I had @Fkawala associated with the "when can we have a release?" question, but I couldn't find any issue he had opened which was blocked on a release.

**Comment by Fkawala** [comment]
@tseaver It is #2860 (it adds a  timestamp parameter to the logger) !

**Comment by tseaver** [comment]
@Fkawala thanks for the reminder!  @dhermes any reason we shouldn't release a `logging-0.23`?

**Comment by Fkawala** [comment]
@dhermes #2860 had been merged on 15 Dec 2016, would be great to have it released !

**Comment by lukesneeringer** [comment]
:+1:

**Comment by Fkawala** [comment]
@dhermes @lukesneeringer @tseaver would be cool to have finally have #2860! Is there anything that blocks the release? If not why wait any longer ?

**Comment by dhermes** [comment]
@Fkawala I plan on doing a release for **all** packages, but currently #3035 blocks this.

**Pull request merged**
