### PR TITLE
Monitoring: move aligner and reducer links from timeSeries.list to alertPolicies

### LINKED ISSUE #5010: Monitoring TimeSeries.Query docs: broken links
Today (9 March), I received a notice from a link checker that the file at [http://gcloud-python.readthedocs.io/en/latest/monitoring/query.html](http://gcloud-python.readthedocs.io/en/latest/monitoring/query.html) had two bad links to the Stackdriver Monitoring API reference.

Here are two warnings I found:

W,https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list#Aligner,http://gcloud-python.readthedocs.io/en/latest/monitoring/query.html,Anchor: Aligner not found.
W,https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list#Reducer,http://gcloud-python.readthedocs.io/en/latest/monitoring/query.html,Anchor: Reducer not found.

The Aligner and Reducer tags are no longer in the monitoring/api/ref_v3/rest/v3/projects.timeSeries/list.html file. This is a generated file, and in the most recent regeneration of the API (published on 8 March), these two tags and the content associated with them was moved (by the generating tool) to monitoring/api/ref_v3/rest/v3/projects.alertPolicies.html. 
Here's the [alertPolicies](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies) page.

I apologize for this. I was able to pre-emptively fix the links in my own docs that this change would break, but I had no way to know from where else these anchors might be linked to. And I cannot "fix" this with the usual URL redirects mechanism we use when pages move. This is content in a page.

I have filed a bug against the generator for this behavior.

### PR DESCRIPTION
**Pull request by chemelnucfin**
Closes #5010 

@dpebot merge on green

### CODE REVIEW

**Comment by mtabasko** [comment]
Thank you!!

**Comment by mtabasko** [comment]
How long does it take for these changes to propagate out? I'm still seeing these bad links in my docs-tracker reports, I'm afraid:

W,https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list#Aligner,http://gcloud-python.readthedocs.io/en/latest/monitoring/query.html,Anchor: Aligner not found.
W,https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list#Reducer,http://gcloud-python.readthedocs.io/en/latest/monitoring/query.html,Anchor: Reducer not found.

**Comment by tseaver** [comment]
@mtabasko Maybe there is an old version cached, either by your browser or on RTD?  Looking at it right now after a "Shift-reload", the links look correct:

- http://google-cloud.readthedocs.io/en/latest/monitoring/query.html#google.cloud.monitoring.query.Query.align
- http://google-cloud.readthedocs.io/en/latest/monitoring/query.html#google.cloud.monitoring.query.Query.reduce

**Comment by mtabasko** [comment]
OK, thanks for confirming. I've looked at the page source, and it looked right to me, but this notice is generated by an automated tool that runs each night, and I wasn't sure if there was some propagation period on these changes. (I would hope this tool wouldn't be using some cached site; that kind of defeats the purpose, but I don't have much control over it.) Thanks again! Sorry for the aggravation.

**Pull request merged**
