### PR TITLE
Spanner Beta

### PR DESCRIPTION
**Pull request by lukesneeringer**
This shall be the "root" PR for getting Spanner to beta. Multiple PRs are going to be made using it as a base.

The remaining to-do items are:

  * [x] Re-generate the autogen libraries for the data and admin APIs.
      * [x] Spanner Admin Database (#4029)
      * [x] Spanner Admin Instance (#4030)
      * [x] Regular ol' Spanner, yo (#4033)
  * [x] ~Update documentation to include autogen API reference.~ (superceded by #4033)
  * [x] Bit flip `setup.py` and appropriate documentation to claim beta status. (#4034)
  * [x] ~Pin gRPC to < 1.6~ (superceded by #4029)

### CODE REVIEW

**Comment by tseaver** [comment]
From #4027, which this PR supersedes:

---

Draft release notes:

## google-cloud-spanner 0.27.1

- Pin dependency  `google-auth >= 1.1.0` to fix use of `google.cloud.spanner` on GCE. (PR #3950, issue #3933)
- Fix merge of partial timestamp and date field values. (PR #4015, issue #3981, #3998)
- Restart streaming iterators from `read` / `execute_sql` operations after resumable error (PR #4016, issue #3775).

---

Internal housekeeping not included in release notes:

- Suppress instance creation tests by default on CI (PR #3951)

**Comment by bjwatson** [comment]
@lukesneeringer @jonparrott We also want a quick review of the API Reference docs to make sure it's reasonably in sync with the client library.

**Comment by jonparrott** [comment]
@lukesneeringer is this ready for me to review the docs?

**Comment by lukesneeringer** [comment]
@jonparrott Yes.

**Comment by bjwatson** [comment]
Thanks @lukesneeringer, @tseaver, and @jonparrott.

**Comment by jonparrott** [comment]
Non-documentation issues/concerns

1. `google.cloud.spanner` is *not* just an alias to `google.cloud.spanner_v1`. This is inconsistent with the approach we took with `pubsub`.

Documentation issues (these may be deferred by moving them into their own bugs):

1. The landing page is... not useful:

screen shot 2017-09-22 at 2 06 58 pm

1. http://temp.theadora.io/google-cloud-spanner/spanner/instance-usage.html#instance-configurations says that `list_instance_configs` and `list_instances` returns a token, but these return iterators.
2. http://temp.theadora.io/google-cloud-spanner/spanner/instance-usage.html#check-on-current-instance-operation references the old operation interface, there is no `finished()` in the new one. It should just reference `result()`.
3. http://temp.theadora.io/google-cloud-spanner/spanner/database-usage.html#create-a-new-database Spanner does not have its own Operation class.
4. http://temp.theadora.io/google-cloud-spanner/spanner/database-usage.html#check-on-current-database-operation similar to (2)
5. http://temp.theadora.io/google-cloud-spanner/spanner/database-usage.html#configuring-a-session-pool-for-a-database the sample here has a typo (and seems to be formatted strangely)
6. The sidebar for spanner is totally whack.  The low-level gapic stuff is mixed in with the high-level wrappers, and one page's sub-titles are treated as separate pages.
7. The page titles mostly end with "API" which is totally weird and overloaded in this context.

**Comment by bjwatson** [comment]
Thanks for your detailed review @jonparrott!

@lukesneeringer is the "Non-documentation issues/concern" a breaking change to fix later. I'm assuming consistency is important here; what do you think?

@tseaver It seems like documentation items 2-6 (shown as 1-5 due to the graphic) should be fixed before the Beta release. The other presentation and organizational concerns can be fixed before GA. Do you agree @jonparrott and @lukesneeringer?

FYI @vkedia

**Comment by jonparrott** [comment]
#6 should really be fixed ASAP.

**Comment by bjwatson** [comment]
@jonparrott I see what you're saying with that. The [Python API Reference](https://googlecloudplatform.github.io/google-cloud-python/latest/spanner/usage.html) combines manual and GAPIC at the same level, whereas [the Ruby docs](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-spanner/v0.23.2/google/cloud/spanner) (and those for other languages) puts it another level below under `v1`.

@lukesneeringer Is this particularly difficult to fix with the current docs setup? I don't think we want to create a lot of work to finalize docs for Beta, but I do see the usability concern that Jon is raising.

**Comment by lukesneeringer** [comment]
Putting in PRs for these.

**Comment by lukesneeringer** [comment]
Okay, I fixed all of these except the `spanner` alias (the item without a PR number in the comment above is waiting on #4054 to be approved, because it needs it as a baseline).

@jonparrott, I am having trouble deciding what to do about the `spanner_v1` thing. I actually considered moving it, and decided against it because doing so would break people in a few cases (e.g. anyone who typed `from google.cloud.spanner.client import Client`, which the documentation previously recommended in one spot, now corrected).

With Pub/Sub, we were breaking everyone _anyway_, so it was an obvious decision. Additionally, since Pub/Sub was a thin client, it was quite necessary to do this.

I am willing to do it here also, but due to the potential customer randomization, it is less clear to me that it is the correct path. Please advise. :-)

**Comment by jonparrott** [comment]
I think we need to make a firm decision on the api -> api_{version} going forwards - either it's a direct alias or it adds functionality. Either spanner or pubsub will need to change. I strongly think we should follow what pubsub did - spanner is transitioning into beta so breaking is allowed (although less than ideal, sure).

**Comment by jonparrott** [comment]
fwiw, the pubsub samples use `google.cloud.pubsub_v1` explicitly.

**Comment by lukesneeringer** [comment]
Okay, I am happy to change it then. :-)

**Comment by bjwatson** [comment]
Thanks, @lukesneeringer for fixing just about everything. I agree that I'm happier with all the `API` suffixes in a post-[4054](https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4054) world, too.

What's the PR for the alias fix?

**Comment by lukesneeringer** [comment]
> What's the PR for the alias fix?

There is not one yet. I had wall-to-wall meetings followed by lunch. :-)

**Comment by bjwatson** [comment]
Understood. Must be Monday. Lots of meetings.

**Comment by lukesneeringer** [comment]
@jonparrott @bjwatson Okay, #4064 exists.

This is probably a breaking change at the margins. In other words, most users will not be affected, but some might be. In particular, we did have at least one doc that told users to `from google.cloud.spanner.client import Client`, and that will break.

Do we need any kind of migration guide?

**Comment by bjwatson** [comment]
@lukesneeringer We should at least have release notes that explain this breaking change.

**Comment by lukesneeringer** [comment]
@bjwatson We will have release notes either way. :-)

**Comment by bjwatson** [comment]
Woo hoo! Great job @lukesneeringer, @tseaver, and @jonparrott!

**Pull request merged**
