### PR TITLE
CI Rehash

### PR DESCRIPTION
**Pull request by lukesneeringer**
This is a continuation of #3135. It is moved to `google-cloud-python:ci` (from my personal branch) because system tests do not run from personal branches.

-------------------------------------------------

This is an attempt to fix the CI situation on this repository. In particular, this will hit the following goals:

  * ~Move to parallel builds on a per-API basis.~ Superceded by not running unnecessary APIs.
  * Move system tests into the individual API packages.
  * Eliminate Travis, move CircleCI to 2.0

In doing this, I made several changes:

  * Move from tox to nox (Python-based configuration is really useful for the multi-project situation)
  * Move from pylint to flake8 (pylint does not work on Python 3.6, has multiple difficult-to-silence false positives)

**This is not done.** In particular, several things need to be put back into place:

  * [x] Automatic docs build.
      * Note to self: Move docs into individual packages (not part of this PR).
  * [x] Automatic PyPI releasing on appropriate tags.
  * [x] Only testing APIs that have changed files.

### CODE REVIEW

**Comment by tseaver** [comment]
@lukesneeringer I tagged this one "do not merge" because you are still iterating rapidly.

**Comment by lukesneeringer** [comment]
This should be almost ready. Because this commit moves literally everything, it triggers all the system tests now, so they need to pass before it is.

Once it is ready, I will rebase into a smaller number of commits so it is reviewable on a per-commit basis. Once approved, we will still squash. The rebase will be for review's sake.

**Comment by lukesneeringer** [comment]
Hey @tseaver -- Do you happen to know off hand what [this failure][1] is about? Is it that the test (or backend) is flaky, or is there something else I should be investigating?

No need to do a ton of research; this is mostly a lazy if-you-know-off-the-top-of-your-head thing.

  [1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1222

**Comment by tseaver** [comment]
@lukesneeringer I'm not seeing the error detail show up on Circle CI today:  just spinning arrows.  I do have a pending Spaner flaky-unit-test fix (#3147), which I'm about to merge.

**Comment by lukesneeringer** [comment]
@tseaver This one is actually a system test; here is the failure:

```
nox > Running session system_tests(python_version='2.7')
nox > virtualenv /var/code/gcp/.nox/system_tests-python_version-2-7 -p python2.7
nox > chdir /var/code/gcp/spanner
nox > pip install --upgrade mock pytest ../core/ ../test_utils/
nox > pip install --upgrade .
nox > py.test --quiet tests/system.py
.............F.
=================================== FAILURES ===================================
____ TestSessionAPI.test_transaction_read_and_insert_or_update_then_commit _____

self = <tests.system.TestSessionAPI testMethod=test_transaction_read_and_insert_or_update_then_commit>

    def test_transaction_read_and_insert_or_update_then_commit(self):
        from google.cloud.spanner import KeySet
        keyset = KeySet(all_=True)
    
        retry = RetryInstanceState(_has_all_ddl)
        retry(self._db.reload)()
    
        session = self._db.session()
        session.create()
        self.to_delete.append(session)
    
        with session.batch() as batch:
            batch.delete(self.TABLE, keyset)
    
        with session.transaction() as transaction:
            rows = list(transaction.read(self.TABLE, self.COLUMNS, keyset))
            self.assertEqual(rows, [])
    
            transaction.insert_or_update(
                self.TABLE, self.COLUMNS, self.ROW_DATA)
    
            # Inserted rows can't be read until after commit.
>           rows = list(transaction.read(self.TABLE, self.COLUMNS, keyset))

tests/system.py:364: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../.nox/system_tests-python_version-2-7/lib/python2.7/site-packages/google/cloud/spanner/streamed.py:159: in __iter__
    self.consume_next()  # raises StopIteration
../.nox/system_tests-python_version-2-7/lib/python2.7/site-packages/google/cloud/spanner/streamed.py:128: in consume_next
    response = six.next(self._response_iterator)
../.nox/system_tests-python_version-2-7/lib/python2.7/site-packages/grpc/_channel.py:367: in next
    return self._next()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_Rendezvous of RPC that terminated with (StatusCode.ABORTED, Transaction was aborted.)>

    def _next(self):
        with self._state.condition:
            if self._state.code is None:
                event_handler = _event_handler(self._state, self._call,
                                               self._response_deserializer)
                self._call.start_client_batch(
                    cygrpc.Operations(
                        (cygrpc.operation_receive_message(_EMPTY_FLAGS),)),
                    event_handler)
                self._state.due.add(cygrpc.OperationType.receive_message)
            elif self._state.code is grpc.StatusCode.OK:
                raise StopIteration()
            else:
                raise self
            while True:
                self._state.condition.wait()
                if self._state.response is not None:
                    response = self._state.response
                    self._state.response = None
                    return response
                elif cygrpc.OperationType.receive_message not in self._state.due:
                    if self._state.code is grpc.StatusCode.OK:
                        raise StopIteration()
                    elif self._state.code is not None:
>                       raise self
E                       _Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.ABORTED, Transaction was aborted.)>

../.nox/system_tests-python_version-2-7/lib/python2.7/site-packages/grpc/_channel.py:358: _Rendezvous
1 failed, 14 passed in 84.28 seconds
nox > Command py.test --quiet tests/system.py failed with exit code 1
nox > Session system_tests(python_version='2.7') failed. :(
nox > Running session system_tests(python_version='3.6')
nox > virtualenv /var/code/gcp/.nox/system_tests-python_version-3-6 -p python3.6
nox > chdir /var/code/gcp/spanner
nox > pip install --upgrade mock pytest ../core/ ../test_utils/
nox > pip install --upgrade .
nox > py.test --quiet tests/system.py
......F........
=================================== FAILURES ===================================
________________ TestDatabaseAdminAPI.test_update_database_ddl _________________

self = <tests.system.TestDatabaseAdminAPI testMethod=test_update_database_ddl>

    def test_update_database_ddl(self):
        pool = BurstyPool()
        temp_db_id = 'temp_db'
        temp_db = Config.INSTANCE.database(temp_db_id, pool=pool)
        create_op = temp_db.create()
        self.to_delete.append(temp_db)
    
        # We want to make sure the operation completes.
        create_op.result(60)  # raises on failure / timeout.
    
        operation = temp_db.update_ddl(DDL_STATEMENTS)
    
        # We want to make sure the operation completes.
>       operation.result(30)  # raises on failure / timeout.

tests/system.py:224: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../.nox/system_tests-python_version-3-6/lib/python3.6/site-packages/google/gax/__init__.py:588: in result
    if not self._poll(timeout).HasField('response'):
../.nox/system_tests-python_version-3-6/lib/python3.6/site-packages/google/gax/__init__.py:699: in _poll
    return retryable_done_check()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = (), delay = 30000
exc = RetryError('Retry total timeout exceeded with exception',)
timeout = -8.942752122879028

    def inner(*args):
        """Equivalent to ``a_func``, but retries upon transient failure.
    
            Retrying is done through an exponential backoff algorithm configured
            by the options in ``retry``.
            """
        delay = retry_options.backoff_settings.initial_retry_delay_millis
        exc = errors.RetryError('Retry total timeout exceeded before any'
                                'response was received')
        if has_timeout_settings:
            timeout = (
                retry_options.backoff_settings.initial_rpc_timeout_millis /
                _MILLIS_PER_SECOND)
    
            now = time.time()
            deadline = now + total_timeout
        else:
            timeout = None
            deadline = None
    
        while deadline is None or now < deadline:
            try:
                to_call = add_timeout_arg(a_func, timeout, **kwargs)
                return to_call(*args)
            except Exception as exception:  # pylint: disable=broad-except
                code = config.exc_to_code(exception)
                if code not in retry_options.retry_codes:
                    raise errors.RetryError(
                        'Exception occurred in retry method that was not'
                        ' classified as transient', exception)
    
                # pylint: disable=redefined-variable-type
                exc = errors.RetryError(
                    'Retry total timeout exceeded with exception', exception)
    
                # Sleep a random number which will, on average, equal the
                # expected delay.
                to_sleep = random.uniform(0, delay * 2)
                time.sleep(to_sleep / _MILLIS_PER_SECOND)
                delay = min(delay * delay_mult, max_delay_millis)
    
                if has_timeout_settings:
                    now = time.time()
                    timeout = min(
                        timeout * timeout_mult, max_timeout, deadline - now)
    
>       raise exc
E       google.gax.errors.RetryError: GaxError(Retry total timeout exceeded with exception, caused by Deadline Exceeded)

../.nox/system_tests-python_version-3-6/lib/python3.6/site-packages/google/gax/retry.py:143: RetryError
1 failed, 14 passed in 99.72 seconds
```

**Comment by lukesneeringer** [comment]
I now have CircleCI's build passing...sometimes. We have some system tests that are still flaky and we need to weed out. That said, this is probably close to ready, and still an improvement over where we were.

I will rebase tomorrow so that the PR is parse-able and reviewable.

**Comment by lukesneeringer** [comment]
Also, the total _serial_ test run-time is down to 40 minutes.

**Comment by lukesneeringer** [comment]
I am still iterating on AppVeyor, but this is ready for review/discussion other than that. Since this is a big PR, it is probably helpful to look at the notes on the top and explore the code, rather than the changelist. The changes are consistent throughout.

  * Unit tests run on Python 2.7, 3.4, 3.5, and 3.6.
  * System tests are moved into their individual packages and run on Python 2.7 and 3.6.
  * Coverage is collected at the end.
  * It should ostensibly only run tests for packages that change, but this is only mildly tested. It can be changed later if we find issues.
  * Common test code is moved into `test_utils`, a package installed at test time by the other packages.
  * The docs and release processes are moved wholesale, but the files are moved. Docs will be shifted into separate packages in a future PR.

**Comment by lukesneeringer** [comment]
@jonparrott Any thoughts on [this Appveyor failure][1]? It seems to be that Windows does not handle importing `nox` in a file named `nox.py` all that well.

If you have an idea, I can go with that. Otherwise, I suppose I could rename them all `noxfile.py`?

This is the last thing I need to do pre-merge.

  [1]: https://ci.appveyor.com/project/GoogleCloudPlatform/google-cloud-python/build/1.0.1200.ci

**Comment by jonparrott** [comment]
> It seems to be that Windows does not handle importing nox in a file named nox.py all that well.

Hmm, it should be able to. Nox was tested on windows up until very recently. You can change them all to noxfile.py until we can find the cause. (File a bug on nox?)

**Comment by lukesneeringer** [comment]
It is easy enough to test and see if that is the cause. Changing bigquery only (the top one on the list) to see what happens.

**Comment by lukesneeringer** [comment]
Random thought as I just restarted the build over a speech LRO that timed out: Maybe for system tests, it might actually be sufficient to require that the LRO _be initialized_, rather than complete. At the point that you get a LRO, you know you made a valid request (and furthermore the ML nature of these APIs means that the response is not completely deterministic anyway).

**Comment by daspecster** [comment]
@lukesneeringer the only thing with that, is that I would like to make sure that all the DTO's populate from the data that's returned in the response. If it doesn't then it kind of defeats the purpose of the system tests because you wouldn't know if this library works with that service's responses, just that this library works with LRO. Right?

**Comment by lukesneeringer** [comment]
> @lukesneeringer the only thing with that, is that I would like to make sure that all the DTO's populate from the data that's returned in the response. If it doesn't then it kind of defeats the purpose of the system tests because you wouldn't know if this library works with that service's responses, just that this library works with LRO. Right?

How long do LROs stick around? Could we take an _existing_ LRO and test it over and over?

**Comment by daspecster** [comment]
@lukesneeringer ah interesting. We could save the result and then reuse it. But I don't think it sticks around long upstream after it's done and you get the result. I'm not sure off hand though.

**Comment by lukesneeringer** [comment]
It is not an urgent issue right now and I do not think it blocks merge on this PR. It is just something we need to think about as we try to eliminate flaky tests.

**Comment by lukesneeringer** [comment]
Caught a new system test bug on merge; filed https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3193

**Comment by lukesneeringer** [comment]
The previous build passed on AppVeyor; this one should pass now that #3193 is fixed. Assuming both pass without incident, will squash and merge.

**Comment by lukesneeringer** [comment]
I finally have a green build. Squashing and merging.

**Comment by dhermes** [comment]
@lukesneeringer Why the merge without review?

**Comment by lukesneeringer** [comment]
It has already gone through a non-trivial amount of review, by everyone here. The only "unreviewed" work was the AppVeyor thrashing.

**Comment by csilvers** [comment]
It looks like CONTRIBUTING.rst still talks about running tox.  Possibly other documentation does too.  Can you fix it to show how to run tests in the new world?  I can't figure out how to even install nox, much less run it.

**Comment by csilvers** [comment]
Ah, I see, this is still open in #3205

**Pull request merged**
