### PR TITLE
Reloading BigQuery table in system test before fetching data.

### PR DESCRIPTION
**Pull request by dhermes**
e.g. https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2065

Error introduced in #3426.

/cc @liyanhui1228

### CODE REVIEW

**Comment by dhermes** [comment]
The [build][1] has already passed the b0rken test case, so fingers crossed here.

[1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2069

**Comment by tseaver** [comment]
It is clearly a good fix.

**Comment by tseaver** [comment]
When I merged #3426, we were in the midst of a spate of logging system test failures, which meant we didn't notice the new error it introduced.

**Comment by dhermes** [comment]
:+1: Thanks @tseaver

**Pull request merged**
