### PR TITLE
Release dataproc 0.1.2

### PR DESCRIPTION
**Pull request by crwilcox**

### CODE REVIEW

**Comment by tseaver** [comment]
Hmm, this PR isn't running tests on CircleCI. @crwilcox Any idea why?

**Comment by tseaver** [comment]
[CircleCI is down](https://status.circleci.com/incidents/yj497xcsqxxf).

**Comment by crwilcox** [comment]
circle went down for a bit. probably that.

**Comment by crwilcox** [comment]
Release is at https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/dataproc-0.1.2

**Comment by tseaver** [comment]
@crwilcox You may need to retrigger the build, or else upload the wheel manually.

**Pull request merged**
