### PR TITLE
BigTable: Add split keys on create table

### PR DESCRIPTION
**Pull request by aneepct**
Add ability to create initial splits during creation of a table. This feature branch is a fork from the GAPIC integration branch (PR #5178).

### CODE REVIEW

**Comment by jonparrott** [comment]
This also seems to need to be rebased.

**Comment by sduskis** [comment]
Why are there app_profile changes here?  Can you please remove them?

**Comment by sduskis** [comment]
Also, please rebase on master.  There are 90 commits here, and I doubt they are related to your change.

**Comment by sduskis** [comment]
Can you please rebase this PR?

**Comment by aneepct** [comment]
@sduskis I created new PR #5370 to prevent few merge conflicts going to close this PR

**Pull request closed without merging**
