### PR TITLE
Show how to create credentials object

### PR DESCRIPTION
**Pull request by ricardolui**
Show how to create credentials object on python sdk

### CODE REVIEW

**Comment by dhermes** [comment]
@jonparrott WDYT? Probably worth looking at all of http://google-cloud-python.readthedocs.io/en/latest/google-cloud-auth.html to see how this fits in

**Comment by jonparrott** [comment]
This is good in theory, but the sentence preceding this talks about "credentials for your specific environment". @ricardolui how would you feel about just cross-linking to http://google-auth.readthedocs.io/en/latest/user-guide.html#compute-engine-container-engine-and-the-app-engine-flexible-environment

**Comment by ricardolui** [comment]
@jonparrott Good, I actually would not mind linking to Service account private key files section from the document you pointed out.  I  think we should also see how to update https://cloud.google.com/docs/authentication to make it more like http://google-auth.readthedocs.io/en/latest/user-guide.html#compute-engine-container-engine-and-the-app-engine-flexible-environment, and give example in our programming languages. What do you think? I thought it was too hard to find the code sample to do a simple thing. My ldap is gricardo@

**Comment by jonparrott** [comment]
@ricardolui I'm working with the tech writing team right now to completely re-do cloud.google.com/docs/authentication.

**Comment by ricardolui** [comment]
@jonparrott Great!!! :) That will be awesome!! Many customers complaining about it ;) About this specific commit, if you could link the Credentials creation to  http://google-auth.readthedocs.io/en/latest/user-guide.html#compute-engine-container-engine-and-the-app-engine-flexible-environment, it would be great!

**Comment by jonparrott** [comment]
@ricardolui it's your PR, feel free to update it (and I'll review and merge).

**Pull request merged**
