### PR TITLE
Cut release of vision API.

### PR DESCRIPTION
**Pull request by dhermes**
~~Also bumping the version on the uber-package.~~

### CODE REVIEW

**Comment by dhermes** [comment]
I'm starting release notes from:

```
$ git log vision-0.25.0..HEAD --pretty=%H -- vision/
987dc826fe1ff16e4b3f06909ae9d9870a2faba2
14e570a3f435f8904ed9fa52d545a35ba5868ad1
3d9461b91963fcc6e6a864f6f0eacad3d92bbf2d
da3a7bbe8c7770540c2149fabfc6f74db89f7ce4
bc7b0fdb9fd99b2c86de9830a25cfaaa295b1c45
b9cb6d17236528ddce982c3e802af3221de80880
39feb3e23d451963ca31b383d8b395afcf7ab817
8ab1afec399b51a1114b7dc223cd2b4e386a3314
```

**Comment by dhermes** [comment]
Not in release:

- This PR: https://github.com/GoogleCloudPlatform/google-cloud-python/commit/987dc826fe1ff16e4b3f06909ae9d9870a2faba2
- PyPI links change: https://github.com/GoogleCloudPlatform/google-cloud-python/commit/14e570a3f435f8904ed9fa52d545a35ba5868ad1
- Author change in `setup.py`: https://github.com/GoogleCloudPlatform/google-cloud-python/commit/da3a7bbe8c7770540c2149fabfc6f74db89f7ce4
- `nox` change: https://github.com/GoogleCloudPlatform/google-cloud-python/commit/bc7b0fdb9fd99b2c86de9830a25cfaaa295b1c45
- `nox` change: https://github.com/GoogleCloudPlatform/google-cloud-python/commit/b9cb6d17236528ddce982c3e802af3221de80880
- LICENSE header change: https://github.com/GoogleCloudPlatform/google-cloud-python/commit/39feb3e23d451963ca31b383d8b395afcf7ab817

Release notes:

- Fixing broken links after docs rename (#3631)
- Add the ability to specify `AnnotateImageRequest` items in single-feature methods. (#3554)

**Comment by dhermes** [comment]
After @lukesneeringer and I realized https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/vision-0.25.0 contained #3373, this has been downgraded to a micro release.

**Comment by tseaver** [comment]
LGTM

**Comment by dhermes** [comment]
- Tag Build: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2591
- Release: https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/vision-0.25.1

**Comment by dhermes** [comment]
The build failed so I had to manually push to PyPI, but release is done: https://pypi.org/project/google-cloud-vision/0.25.1/

**Pull request merged**
