### PR TITLE
Updating Firestore encrypted key.

### PR DESCRIPTION
**Pull request by dhermes**
Generated password / passphrase via:

```
$ openssl rand -base64 48
```

Then used it to encrypt the keyfile via:

```
$ rm -f firestore/tests/credentials.json.enc
$ openssl aes-256-cbc -salt -a \
>   -in path/to/keyfile.json \
>   -out firestore/tests/credentials.json.enc
```

### CODE REVIEW

**Comment by dhermes** [comment]
Need this to go in, currently causing a failure because I updated the env. variables:

https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3601

**Comment by tseaver** [comment]
LGTM

**Comment by dhermes** [comment]
**NOTE**: This [failed][1] on first run. I am going to change the value of `FIRESTORE_APPLICATION_CREDENTIALS` from `firestore/tests/credentials.json` to `/var/code/gcp/firestore/tests/credentials.json` and re-run.

[1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3602

**Comment by dhermes** [comment]
Fingers crossed on the re-build: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3603

**Pull request merged**
