### PR TITLE
Making new Pub / Sub and API core releases.

### PR DESCRIPTION
**Pull request by dhermes**

### CODE REVIEW

**Comment by jonparrott** [comment]
Lgtm

**Comment by dhermes** [comment]
I am going to merge since `api_core` changes spin off a "build every package" build, which takes way too long.

**Comment by dhermes** [comment]
Reason I am OK with that merge: this PR had virtually zero code changes (other than `setup.py` changes).

New tag pushed for `api_core` and [build][1] in progress. Once on PyPI I'll push a tag for `pubsub`

[1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/4669

**Comment by dhermes** [comment]
I just realized I missed 4 PRs in `api_core`: #4339, #4336, #4367, #4399

@jonparrott Would you mind upgrading the [release notes][1] with a summary? (I'm assuming you will have better knowledge of those PRs and can write a better summary than I can, but if not, punt back to me.)

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/api-core-0.1.2

**Comment by dhermes** [comment]
Here is the Pub / Sub [build][1] that will push to PyPI.

[1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/4670

**Pull request merged**
