### PR TITLE
Release pubsub 0.34.0

### PR DESCRIPTION
**Pull request by jonparrott**
This pull request was generated using releasetool.

### CODE REVIEW

**Comment by tseaver** [comment]
Should the changelog mention #5256?  Or is that a fix to unreleased code?

**Comment by jonparrott** [comment]
> Should the changelog mention #5256? Or is that a fix to unreleased code?

Its in the one big note that references a lot of PRs.

**Comment by tseaver** [comment]
Got it. LGTM

**Comment by jonparrott** [comment]
Release is at https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/pubsub-0.34.0

**Pull request merged**
