### PR TITLE
Add 'QueryJob.referenced_tables' property.

### PR DESCRIPTION
**Pull request by tseaver**
~~Uses #3800 as a base.~~

Cherry-picked / fixed up from PR #3721.

### CODE REVIEW

**Comment by tseaver** [comment]
@tswast This version incorporates your [research about overriding the dataset project](https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3721#discussion_r131240287), and therefore doesn't require the `Client._clone` method.

**Comment by tseaver** [comment]
Rebased after merging #3800 to the `bigquery-b2` branch, with only the final commit.  I will merge once the CircleCI build passes the `bigquery` test section.

**Comment by tseaver** [comment]
Hmm, I have no idea why the CircleCI tests are not running.  @dhermes, @lukesneeringer any clue?

**Comment by dhermes** [comment]
Web-scale? Occasionally the webhooks get dropped. It's possible to see in the settings for this repo, I just don't have access to those anymore.

**Comment by dhermes** [comment]
From https://status.github.com/

screenshot from 2017-09-07 15-16-52

**Pull request merged**
