### PR TITLE
Release Speech 0.31.1

### PR DESCRIPTION
**Pull request by jonparrott**

### CODE REVIEW

**Comment by jonparrott** [comment]
don't merge, something weird is going on

**Comment by chemelnucfin** [comment]
the releases and setup changes are needed anyway, right?

**Comment by jonparrott** [comment]
Yeah, I was just thrown off because there were no release notes for 0.31.0. I've fixed that, this is mergeable.

**Comment by gokul-gokz** [comment]
How to install speech 0.31.1 ?
I tried using sudo pip install google-cloud-speech==0.31.1
But i got an error message stating that version 0.31.1 is not available

**Comment by jonparrott** [comment]
@gokul-gokz apologizes, it seems I didn't quite do this release correctly. It's been fixed and I verified that `0.31.1` is available on PyPI here: https://pypi.org/project/google-cloud-speech/

**Pull request merged**
