### PR TITLE
Isolating Connection objects in _http modules (where relevant).

### PR DESCRIPTION
**Pull request by dhermes**
This is a work-in-progress for now, but `vision` and `speech` are done. Will also be doing `logging`, `pubsub` and **maybe** `error_reporting`.

FWIW, this is a result of me working on #2746.

### CODE REVIEW

**Comment by dhermes** [comment]
@daspecster Thanks but you are bit quick on the draw. The work-in-progress bit means more changes will be coming.

**Comment by daspecster** [comment]
Sorry, I thought that meant this was one PR of n-PRs.

**Comment by dhermes** [comment]
Holding off on `logging` and `pubsub` in this PR since it would un-necessarily create 3 connections (since there are 3 services created in either case). What we really care about is `connection.api_request` ([here][1] and [here][2]), which just relies on **CLASS** attributes, the credentials (known on the client) and the inputs. So it can wait until a larger refactor.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/d4d0abcab27b3f1aba9b56db4d643d5692230bd5/logging/google/cloud/logging/_http.py#L65
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/d4d0abcab27b3f1aba9b56db4d643d5692230bd5/pubsub/google/cloud/pubsub/_http.py#L112

**Comment by dhermes** [comment]
@daspecster @lukesneeringer PTAL this is ready for review

**Comment by daspecster** [comment]
This LGTM.

**Pull request merged**
