### PR TITLE
Simplifying usage of Client classes in Spanner and Bigtable

### PR DESCRIPTION
**Pull request by dhermes**
As a follow-up commit, also simplifying the Client classes.

I am "throwing this up" as a half-finished PR so @jonparrott can take the wheel.

### CODE REVIEW

**Comment by jonparrott** [comment]
I'm gonna close this for now. This is helpful because it's revealed just how much refactoring will need to happen to use a new client superclass. With the move to google.api.core, I will introduce the new base classes, switch these to that, then drop `core.client`.

**Comment by dhermes** [comment]
@jonparrott At the very least the first commit should go in (just to push all of the warts into one place)

**Comment by dhermes** [comment]
I just force-pushed this branch with one fewer commit.

**Comment by dhermes** [comment]
And the force-push made it impossible to "Reopen and comment"

**Pull request closed without merging**
