### PR TITLE
Update storage to 1.3.2.

### PR DESCRIPTION
**Pull request by dhermes**
Did this to update the lower bound on the `requests` dependency (see #3736).

### CODE REVIEW

**Comment by dhermes** [comment]
Blerg! #3770 means a `core` release would be needed for `storage` and #3737 means this should probably be a `1.4.x` release.

:cry:

**Comment by jonparrott** [comment]
Ugh, I was worried about this.

We have two options:

1. Keep revving core (& all dependent packages) every time we need a release until I'm done. (My ETA is ~1 month)
2. Cherry-pick into a release branch and release from there.

@lukesneeringer WDYT?

**Comment by jonparrott** [comment]
Alternatively I can hold on off making any more breaking changes in core (basically don't remove any google.cloud packages and cut over depend usage until the very end).

**Comment by dhermes** [comment]
> Cherry-pick into a release branch and release from there.

My preference

**Comment by lukesneeringer** [comment]
I have no preference. Whichever you two prefer since you are the ones doing the work.

**Pull request closed without merging**
