### PR TITLE
Cutting release google-cloud-core==0.26.0.

### PR DESCRIPTION
**Pull request by dhermes**

### CODE REVIEW

**Comment by dhermes** [comment]
Sifting through `git log core-0.25.0..cut-core-0.26.0 -- core/` right now, release notes forthcoming.

**Comment by dhermes** [comment]
Included in release (I am going to edit these in place, this is just copy-paste at the start):

- Update doc reference for setting up a service account (#3578)
- Fixing references to "dead" docs links. (#3631)
- Add base future package to google.cloud (#3616)
- Add operation future (#3618)
- Split polling future into its own module (#3662)
- Removing vendored in google.cloud.streaming. (#3654)
- Correctly url-encode list parameters (#3657)
- Moving bytes signing helpers from `core` to `storage`. (#3668)
- Removing `get_credentials()` from `core`. (#3667)
- Remove httplib2, replace with Requests (#3674)
- Add a function to complain about obselete packages. (#3724)

----

Not included in release:

- Fix inclusion of tests in manifest.in (#3552)
- Making all LICENSE headers "uniform". (#3563)
- Shorten nox virtualenv names to avoid hashing. (#3585)
- Updating author_email in all setup.py. (#3598)
- Changing all pypi.python.org links to warehouse links. (#3641)
- Fix pylint for the main package (#3658)
- Re-enable flake8 for core package and tests (#3664)

**Comment by jonparrott** [comment]
please include

```
* Fix inclusion of tests in manifest.in (#3552)
* Updating author_email in all setup.py. (#3598)
```

Since in impacts the distribution package.

**Comment by dhermes** [comment]
Merging, despite the very much broken-ness (the `core` version is invalid for the upper bounds in all the downstream packages, so they pull from PyPI).

**Pull request merged**
