### PR TITLE
Fix packaging of resources and tests

### PR DESCRIPTION
**Pull request by jonparrott**
* Don't include tests in the binary (wheel) distribution.
* Include tests in the source distribution.
* Include only .json and .proto package resources.
* Include a LICENSE with every package (extremely important for downstream packagers).

### CODE REVIEW

**Comment by jonparrott** [comment]
Related: https://github.com/googleapis/gax-python/pull/174

**Comment by dhermes** [comment]
@jonparrott Can you do me a teeny favor? Can you make all the `LICENSE` additions in a standalone commit so I can actually view the rest in a commit diff?

**Comment by jonparrott** [comment]
I will tomorrow. The changes for each package is identical. Literally "git
apply".

**Comment by lukesneeringer** [comment]
Additionally, can you do this change against the `ci` branch, so I do not have to double-do it?

**Comment by jonparrott** [comment]
Closing this so I can re-target the `ci` branch.

**Pull request closed without merging**
