### PR TITLE
Upgrading number of PyLint jobs from 1 to 10.

### PR DESCRIPTION
**Pull request by dhermes**
Marked "don't merge" for now because I want to actually time the difference on the entire codebase. Working on it now.

### CODE REVIEW

**Comment by tseaver** [comment]
LGTM

**Comment by dhermes** [comment]
@tseaver May not be worth it.

At the current `HEAD` in `master` (or it was current until #2400 was merged)

```
$ git log -1 --pretty=%H
64353b5639a03ce9d2538eaf5fc112ea9019662e
$ rm -fr .tox/lint
$ time tox -e lint
...
real    3m17.283s
user    3m7.844s
sys     0m8.716s
```

at the `HEAD` in this PR

```
$ git log -1 --pretty=%H
dad810adf293f06dea50a459095a0e60924eb26f
$ rm -fr .tox/lint
$ tox -e lint --recreate --notest
$ time tox -e lint
...
real    3m26.578s
user    3m15.860s
sys     0m18.952s
$ time tox -e lint
...
real    3m21.792s
user    3m11.124s
sys     0m18.400s
```

So the extra jobs either

- Add overhead without adding speed
- Don't actually get set unless I do something else

**Comment by dhermes** [comment]
https://github.com/PyCQA/pylint/issues/479

**Comment by tseaver** [comment]
That PyCQA issue is supposed to be long-ago fixed.

**Comment by dhermes** [comment]
@tseaver I'm pretty sure we don't get the speed-up because of the [changes][1] introduced in #1974 (I was on paternity leave at the time so didn't fully understand the change). In particular, the fact that we run Pylint on each file separately.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/4a299fe0a2f45e99dc9816e093e00471109d6cfa/scripts/run_pylint.py#L181-L187

**Comment by dhermes** [comment]
Will revisit this some other time.

**Pull request closed without merging**
