### PR TITLE
Move error reporting code into a subpackage

### PR DESCRIPTION
**Pull request by dhermes**
This PR was created via: https://gist.github.com/dhermes/e239691aa584bd56a5352e34aad27cf3

```
export PROJECT_DIR="${HOME}/google-cloud-python"
export READMES_DIR="${HOME}/i-wrote-some-readmes-for-2357"
cd ${PROJECT_DIR}
git worktree add -b make-error_reporting-subpackage ../hotfix official/master
python make_commits.py \
  --git-root "${PROJECT_DIR}/../hotfix" \
  --package error-reporting \
  --package-name "Stackdriver Error Reporting" \
  --readme "${READMES_DIR}/error_reporting/README.rst"
```

NOTE: A new commit was added to the script to handle the `-`/`_` switch for multi-name packages.

NOTE: Error reporting depends on `logging`. @waprin is this intended?

### CODE REVIEW

**Comment by waprin** [comment]
It is intended but also intended to be changed. You can report events to Error Reporting by writing to Logging API in a certain format, but for tracking quota/resource usage we'd prefer to just use Error Reporting directly, it's just that before the API wasn't 100% ready.

**Comment by dhermes** [comment]
> also intended to be changed

@waprin Is there a tracking bug outlining these intentions?

**Comment by waprin** [comment]
We have an internal one, I don't think there's any intention to hit Error Reporting through http, VTK grpc client will be the main one and we can keep the existing one as a fallback.

**Comment by dhermes** [comment]
I missed a part with the rename where `.travis.yml` was doing `cd error-reporting` instead of `cd error_reporting`. I [fixed up][1] the script, re-ran it against `master` and cherry-picked the 3rd commit. After (`git diff origin/make-error_reporting-subpackage`):

```diff
diff --git a/.travis.yml b/.travis.yml
index 4bd9194..114bbc1 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -15,7 +15,7 @@ script:
   - (cd logging && tox -e py27)
   - (cd dns && tox -e py27)
   - (cd language && tox -e py27)
-  - (cd error-reporting && tox -e py27)
+  - (cd error_reporting && tox -e py27)
   - tox -e py34
   - (cd core && tox -e py34)
   - (cd bigtable && tox -e py34)
@@ -26,7 +26,7 @@ script:
   - (cd logging && tox -e py34)
   - (cd dns && tox -e py34)
   - (cd language && tox -e py34)
-  - (cd error-reporting && tox -e py34)
+  - (cd error_reporting && tox -e py34)
   - tox -e lint
   - tox -e cover
   - (cd core && tox -e cover)
@@ -38,7 +38,7 @@ script:
   - (cd logging && tox -e cover)
   - (cd dns && tox -e cover)
   - (cd language && tox -e cover)
-  - (cd error-reporting && tox -e cover)
+  - (cd error_reporting && tox -e cover)
   - tox -e system-tests
   - tox -e system-tests3
   - scripts/update_docs.sh
```

and `cd error_reporting; tox` gives

```
$ tox
GLOB sdist-make: .../hotfix/error_reporting/setup.py
py27 inst-nodeps: .../hotfix/error_reporting/.tox/dist/google-cloud-error-reporting-0.20.0.dev0.zip
py27 installed: enum34==1.1.6,future==0.15.2,futures==3.0.5,gapic-google-logging-v2==0.9.3,google-cloud-core==0.20.0.dev0,google-cloud-error-re
porting==0.20.0.dev0,google-cloud-logging==0.20.0.dev0,google-gax==0.14.1,googleapis-common-protos==1.3.4,grpc-google-logging-v2==0.9.3,grpcio=
=1.0.0,httplib2==0.9.2,oauth2client==2.2.0,ply==3.8,protobuf==3.0.0,py==1.4.31,pyasn1==0.1.9,pyasn1-modules==0.0.8,pytest==3.0.2,rsa==3.4.2,six
==1.10.0
py27 runtests: PYTHONHASHSEED='3088020416'
py27 runtests: commands[0] | py.test --quiet unit_tests
.....
5 passed in 0.13 seconds
py34 inst-nodeps: .../hotfix/error_reporting/.tox/dist/google-cloud-error-reporting-0.20.0.dev0.zip
py34 installed: enum34==1.1.6,future==0.15.2,futures==3.0.5,gapic-google-logging-v2==0.9.3,google-cloud-core==0.20.0.dev0,google-cloud-error-re
porting==0.20.0.dev0,google-cloud-logging==0.20.0.dev0,google-gax==0.14.1,googleapis-common-protos==1.3.4,grpc-google-logging-v2==0.9.3,grpcio=
=1.0.0,httplib2==0.9.2,oauth2client==2.2.0,ply==3.8,protobuf==3.0.0,py==1.4.31,pyasn1==0.1.9,pyasn1-modules==0.0.8,pytest==3.0.2,rsa==3.4.2,six==1.10.0
py34 runtests: PYTHONHASHSEED='3088020416'
py34 runtests: commands[0] | py.test --quiet unit_tests
.....
5 passed in 0.20 seconds
py35 inst-nodeps: .../hotfix/error_reporting/.tox/dist/google-cloud-error-reporting-0.20.0.dev0.zip
py35 installed: enum34==1.1.6,future==0.15.2,futures==3.0.5,gapic-google-logging-v2==0.9.3,google-cloud-core==0.20.0.dev0,google-cloud-error-reporting==0.20.0.dev0,google-cloud-logging==0.20.0.dev0,google-gax==0.14.1,googleapis-common-protos==1.3.4,grpc-google-logging-v2==0.9.3,grpcio==1.0.0,httplib2==0.9.2,oauth2client==2.2.0,ply==3.8,protobuf==3.0.0,py==1.4.31,pyasn1==0.1.9,pyasn1-modules==0.0.8,pytest==3.0.2,rsa==3.4.2,six==1.10.0
py35 runtests: PYTHONHASHSEED='3088020416'
py35 runtests: commands[0] | py.test --quiet unit_tests
.....
5 passed in 0.19 seconds
cover inst-nodeps: .../hotfix/error_reporting/.tox/dist/google-cloud-error-reporting-0.20.0.dev0.zip
cover installed: coverage==4.2,enum34==1.1.6,future==0.15.2,futures==3.0.5,gapic-google-logging-v2==0.9.3,google-cloud-core==0.20.0.dev0,google-cloud-error-reporting==0.20.0.dev0,google-cloud-logging==0.20.0.dev0,google-gax==0.14.1,googleapis-common-protos==1.3.4,grpc-google-logging-v2==0.9.3,grpcio==1.0.0,httplib2==0.9.2,oauth2client==2.2.0,ply==3.8,protobuf==3.0.0,py==1.4.31,pyasn1==0.1.9,pyasn1-modules==0.0.8,pytest==3.0.2,pytest-cov==2.3.1,rsa==3.4.2,six==1.10.0
cover runtests: PYTHONHASHSEED='3088020416'
cover runtests: commands[0] | py.test --quiet --cov=google.cloud.error-reporting --cov=unit_tests --cov-config .../hotfix/error_reporting/.coveragerc unit_tests
.....Coverage.py warning: Module google.cloud.error-reporting was never imported.


---------- coverage: platform linux2, python 2.7.12-final-0 ----------
Name                        Stmts   Miss Branch BrPart  Cover   Missing
-----------------------------------------------------------------------
unit_tests/__init__.py          0      0      0      0   100%
unit_tests/test_client.py      82      0      6      0   100%
-----------------------------------------------------------------------
TOTAL                          82      0      6      0   100%

5 passed in 0.21 seconds
___________________________________________________________________ summary ___________________________________________________________________
  py27: commands succeeded
  py34: commands succeeded
  py35: commands succeeded
  cover: commands succeeded
  congratulations :)
```

[1]: https://gist.github.com/dhermes/e239691aa584bd56a5352e34aad27cf3/revisions

**Pull request merged**
