### PR TITLE
Support parsing DATE columns from Standard SQL tables

### PR DESCRIPTION
**Pull request by thejens**
Change-Id: I158b48b6470ff44ff006e18d5eb8e3540749670b

### CODE REVIEW

**Comment by thejens** [comment]
... guess I couldn't quite figure out how to unit test the _date_from_json as I couldn't find where the other _X_from_json functions were tested

**Comment by tseaver** [comment]
Tests for the `bigquery._helpers` module are [here](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/unit_tests/bigquery/test__helpers.py).

**Comment by tseaver** [comment]
Thanks for the patch, BTW!

**Comment by thejens** [comment]
@tseaver Ty, I did find the tests module, but as the function I added had several similar functions I wanted to test it consistently, and I guess I couldn't find the tests for the others;

Ex. I added **_date_from_json** and "**_float_from_json**" already existed hence I want to test it in the same manner, but can't see where that happens

**Comment by tseaver** [comment]
@thejens Hmmm, I see what you mean.  Those helpers are being covered indirectly through the tests for `query` and `table`.  They should probably have their own coverage in `test__helpers.py`, though.

**Comment by tseaver** [comment]
@thejens I landed more comprehensive tests for `google.cloud.bigquery._helpers` in #2272.  They should serve as a model for your tests of `_date_from_json`.

**Comment by thejens** [comment]
@tseaver Thanks for putting those tests there; seems they and the one I added passed

**Comment by tseaver** [comment]
@thejens Thanks again!

**Pull request merged**
