### PR TITLE
Removing google-cloud-core dependency in test_utils package.

### PR DESCRIPTION
**Pull request by dhermes**
@lukesneeringer Why is this a dependency in the `test_utils` package?

### CODE REVIEW

**Comment by tseaver** [comment]
@dhermes enviornment variables:

```bash
$ git grep "from google.cloud" test_utils/ 
test_utils/scripts/run_emulator.py:from google.cloud.environment_vars import BIGTABLE_EMULATOR
test_utils/scripts/run_emulator.py:from google.cloud.environment_vars import GCD_DATASET
test_utils/scripts/run_emulator.py:from google.cloud.environment_vars import GCD_HOST
test_utils/scripts/run_emulator.py:from google.cloud.environment_vars import PUBSUB_EMULATOR
```

**Comment by dhermes** [comment]
Ha. Lame.

I'm going to leave this un-merged for at least 12 hours. I want to see if @lukesneeringer has anything to chime in with.

**Comment by jonparrott** [comment]
weird that test_utils is its own package. Couldn't we just roll it into google-cloud-core? `google.cloud._internal.testing`?

**Comment by dhermes** [comment]
I disagree. It's weird to put testing helpers in code that users have installed on their machines.

**Comment by jonparrott** [comment]
I mostly agree, but lesser of two evils - google-cloud-core is an "infrastructure" package (like gax), so I am not morally opposed to it having helpers for both creating packages and tests for those packages.

**Comment by tseaver** [comment]
FWIW, We actually to have `google.cloud._testing` in core.

**Comment by dhermes** [comment]
@tseaver Yes I'm aware, and would love to see that module either removed (due to better usage of `mock`) or put outside of source that is shipped to users.

**Comment by lukesneeringer** [comment]
> weird that test_utils is its own package. Couldn't we just roll it into google-cloud-core? `google.cloud._internal.testing`?

I did this originally and @dhermes made me change it. I would still prefer that.

**Comment by dhermes** [comment]
Ya'll got me feeling crazy now :grinning: 

1ro4rx

**Comment by dhermes** [comment]
So this discussion shouldn't block the "bad dep" we currently have in the source tree.

Shall I file an issue to move the discussion and then merge this issue?

**Comment by lukesneeringer** [comment]
If removing the dep does not break anything, I have no objection.

**Comment by dhermes** [comment]
SGTM @lukesneeringer, just amended the commit so that it's just a removal. Fingers crossed.

**Comment by dhermes** [comment]
Aw man, no packages to test:

```
#!/bin/bash -eo pipefail
python3.6 test_utils/scripts/get_target_packages.py > ~/target_packages
cat ~/target_packages
```

**Comment by dhermes** [comment]
I'm just going to merge this and if there is carnage we can roll it back ASAP.

**Pull request merged**
