### PR TITLE
Removing vendored in google.cloud.streaming.

### PR DESCRIPTION
**Pull request by dhermes**
Done simply via:

```
$ git rm -fr core/google/cloud/streaming/
$ git rm -fr core/tests/unit/streaming/
```

Towards #1998.

### CODE REVIEW

**Comment by jonparrott** [comment]
This LGTM - if any test failures arise can we address those in separate PRs and rebase this one along?

**Comment by jonparrott** [comment]
Also this won't run system tests - can we verify system tests for impact packages?

**Comment by dhermes** [comment]
@jonparrott I just pushed https://github.com/GoogleCloudPlatform/google-cloud-python/tree/remove-streaming so we can run system tests.

FWIW the ["first run"][1] after merging #3555 failed due to BigQuery timeouts (no idea why).

[1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2511

**Comment by dhermes** [comment]
OK https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2515 and https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2511 have failed in the same way, but at `HEAD`, the system tests continue to pass on my local machine (even when setting `CIRCLE_BUILD_NUM`).

I added a "nonsense" commit to force `pytest` to emit **native** Python tracebacks (I have never gotten used to `pytest` tracebacks)

**Comment by dhermes** [comment]
As a small solace, the **unit** tests are all good:

https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/tree/pull%2F3654

**Comment by dhermes** [comment]
I think the BigQuery issue is just some intermittent failures in BigQuery. The latest build (https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2518) only failed in 3.6 and only on one test case.

**Comment by jonparrott** [comment]
Merge. Let's re-validate system tests before release.

**Comment by dhermes** [comment]
Haha OK!

**Comment by dhermes** [comment]
As suspected, BigQuery unit tests are back to passing: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2520

Though those `logging` tests seem determined to never pass

**Comment by jonparrott** [comment]
You mean system tests?

**Comment by dhermes** [comment]
I do mean system tests, thank you

**Comment by jonparrott** [comment]
Good deal. Thanks.

**Pull request merged**
