### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by craigcitro**
Spotted while grepping for "meta". ;)

### CODE REVIEW

**Comment by craigcitro** [comment]
PTAL @dhermes who has suffered many other such CLs from me in the past.

**Comment by jonparrott** [comment]
`timetamp`, classic.

@dhermes @lukesneeringer  docstring only change, merging.

**Comment by dhermes** [comment]
Lulz. Great fake word.

**Comment by lukesneeringer** [comment]
@jonparrott Thanks!

**Pull request merged**
