### PR TITLE
Moving to iterators in DNS.

### PR DESCRIPTION
**Pull request by dhermes**
~~**NOTE**: Has #2531 as diffbase.~~

~~In doing this, I realized it's a bit tedious to have to write two classes (page and iterator) for each method. It may be more user-friendly to collapse back into one class. I think I could do it mostly by just making anything that is accessed via `self.page.foo` as `self.page_foo`.~~

### CODE REVIEW

**Comment by dhermes** [comment]
@daspecster @tseaver @jonparrott PTAL.

There will be about 5 more PRs like this for each package which does page token `list_foo()`.

**Comment by dhermes** [comment]
TRAVIS!

**Comment by jonparrott** [comment]
> TRAVIS!

No travis for you, I used up all of his cycles in `google-auth`. :P

**Comment by tseaver** [comment]
I don't really care for the inheritance-based iterator approach:  would it be better to tackle that first in #2531?  Or merge this and then maybe refactor, killing of the subclasses?

**Comment by dhermes** [comment]
@tseaver Can you weigh in on #2558 ASAP?

**Pull request closed without merging**
