### PR TITLE
Fix for DS client not connecting to DS emulator host via env var.

### PR DESCRIPTION
**Pull request by ziplokk1**
Fix for issue #3920
Updated PR for #4795

Code Example:

```python
# This assumes you have the datastore emulator running on localhost:8081
from google.cloud import datastore

import os
os.environ['DATASTORE_EMULATOR_HOST'] = 'localhost:8081'

ds_client = datastore.Client()
key = ds_client.key('Testing', 'test')
entity = datastore.Entity(key)
entity.update({
    'hello': 'world'
})

ds_client.put(entity)
print(ds_client.get(key))
```

### CODE REVIEW

**Comment by ziplokk1** [comment]
Giving this another go.

I realized after deep diving that the logic was already there to accept the datastore emulator host but wasn't working without the credentials.

Just patched it up a little bit and added a test to make sure that it works without any default credentials.

I think I'm on the right track this time.

Sorry about all the PRs.

**Comment by jonparrott** [comment]
Hi @ziplokk1. Thank you for putting this together, but I don't think we can accept this PR right now. We need to have a more broad conversation about how we want to support emulators. I'm going to keep the referenced issue open for discussion, but I'm going to close this for now.

**Comment by ziplokk1** [comment]
Not a problem! I hope it can help someone out in the future.

**Comment by drmarshall** [comment]
@theacodes -- has the discussion about emulators support taken place or at a clear workaround been documented? This is a pretty major stumbling block for a well-functioning CI and has been visible for 6 months.

**Comment by theacodes** [comment]
Hmmm. Revisting this PR I would be open to merging something like this if it used `google.auth.credentials.AnonymousCredentials` instead of a custom class.

**Comment by ziplokk1** [comment]
The code is merged into master on my fork if someone wants to change that functionality.

**Comment by Saturn-V** [comment]
@theacodes -- Any updates regarding discussion for DS emulator support?

**Pull request closed without merging**
