### PR TITLE
Update reference to bytes signing issue in blob.py

### PR DESCRIPTION
**Pull request by alanyee**
Link to updated issue

### CODE REVIEW

**Comment by alanyee** [comment]
Uh how do I consent?

**Comment by dhermes** [comment]
@alanyee You are good on the CLA (see the original `cla: yes`).

The bot got confused because I pushed a commit to this PR (for the little dedent nit).

**Comment by dhermes** [comment]
@jonparrott This LGTY?

**Comment by lukesneeringer** [comment]
LGTM.

**Pull request merged**
