### PR TITLE
BigQuery: Add system tests for microsecond-level precision datetimes

### LINKED ISSUE #3870: BigQuery: Parsing fails if timestamps or datetimes include microsecond part
In investigating some timestamp handling, I encountered an issue that the timestamp parsing ignores microseconds if present in the timestamp. Per https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#timestamp-type the microsecond portion is optional, but it could be present.

I've updated the system tests to reflect this issue:

https://github.com/tswast/google-cloud-python/blob/5a40bf02eba937097e90bc260da2d72e16d51213/bigquery/tests/system.py#L649

This test fails with

```
$ pytest tests/system.py::TestBigQuery::test_sync_query_w_standard_sql_types
============================================================================================== test session starts ==============================================================================================
platform darwin -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /Users/swast/src/google-cloud-python, inifile: setup.cfg
plugins: timeout-1.2.0
collected 1 item

tests/system.py F

=================================================================================================== FAILURES ====================================================================================================
_______________________________________________________________________________ TestBigQuery.test_sync_query_w_standard_sql_types _______________________________________________________________________________
Traceback (most recent call last):
  File "/Users/swast/src/google-cloud-python/bigquery/tests/system.py", line 747, in test_sync_query_w_standard_sql_types
    self.assertEqual(query.rows[0][0], example['expected'])
  File "/Users/swast/.pyenv/versions/3.6.2/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/swast/.pyenv/versions/3.6.2/lib/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: datetime.datetime(2016, 12, 5, 12, 41, 9, tzinfo=<UTC>) != datetime.datetime(2016, 12, 5, 12, 41, 9, 250000, tzinfo=<UTC>)
=========================================================================================== 1 failed in 5.47 seconds ============================================================================================
```

### PR DESCRIPTION
**Pull request by tswast**
Follow-up to #3901.

Closes #3870.

### CODE REVIEW

**Comment by dhermes** [comment]
@tswast Fix the lint error? Then push your branch to the `GoogleCloudPlatform` remote so we can verify the system tests pass?

**Comment by tswast** [comment]
Lint error fixed. Also pushed to branch on this repo. Build running at https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3175

**Comment by dhermes** [comment]
```
nox > * system_tests(python_version='2.7'): passed
nox > * system_tests(python_version='3.6'): passed
```

LGTM! (You **can** wait until the `logging` tests go green to squash and merge, but you probably don't need to.)

**Comment by dhermes** [comment]
Also, don't forget to delete the branch once you've merged it.

**Pull request merged**
