### PR TITLE
Revert "Fix make_report_error_api usage of Client._project."

### PR DESCRIPTION
**Pull request by DizzeePascall**

### CODE REVIEW

**Comment by DizzeePascall** [comment]
To fix https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3233

**Comment by dhermes** [comment]
@DizzeePascall see my response on #3233, this issue should be fixed / the PR does not need to be reverted (though I may be mistaken).

**Comment by DizzeePascall** [comment]
This PR is filed on behalf of Spotify, which I believe has filed the CLA as a corporation

**Comment by dhermes** [comment]
This LGTM. It's nice that reverting did exactly what was needed.

@lukesneeringer @jonparrott Any idea where the CLA check went?

@DizzeePascall Once this is merged I can push `0.23.3` today. SG?

**Comment by DizzeePascall** [comment]
@dhermes I hadn't joined the Google group until just now, which explains why the CLA check failed. It'd be absolutely great if you could get this merged and pushed by the end of the day 👍

**Comment by dhermes** [comment]
I will push a tag (which automatically pushes to PyPI) once https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1413 passes

**Comment by dhermes** [comment]
This is finally going out (as `0.24.0`) and will be pushed by this build:
https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1575

Thanks for the patience!

**Pull request merged**
