### PR TITLE
firestore: cross-language tests

### PR DESCRIPTION
**Pull request by jba**
Copied the cross-language tests from GoogleCloudPlatform/google-cloud-common
to this repo.

Generated the Python _pb2.py file for the test proto. This required some
path renaming, so I added a Makefile.

Added a unit test that reads and runs the test protos.

Sorted transform paths in get_transform_pb to make some tests pass.

Renamed tests that fail.

TODOs:
- Fix failing tests.

- Support tests of the set() method.

- Find a better place to put test_pb2.py. I don't understand
  how import paths work so I couldn't figure this out.

### CODE REVIEW

**Comment by lukesneeringer** [comment]
Hmm. Thought: I am uncomfortable with having a file called `Makefile` at the project root that just for a side thing.

**Comment by dhermes** [comment]
> I am uncomfortable with having a file called `Makefile` at the project root that just for a side thing.

As am I. Though I am **totally** fine with it in the package root for `firestore`.

**Comment by jba** [comment]
@dhermes So I should move the Makefile to `firestore/google/cloud/firestore_v1beta1`?

**Comment by dhermes** [comment]
@jba No, I have egg on my face. I assumed based on Luke's comment that you had it in the root of the project, rather than at `firestore/Makefile`. Disregard :grinning: :fried_egg:

**Comment by jba** [comment]
@lukesneeringer Now that you understand what's going on here, can you approve or request changes?

**Comment by jba** [comment]
@lukesneeringer ping

**Comment by jba** [comment]
@lukesneeringer ping

**Comment by chemelnucfin** [comment]
I'm going to pull the trigger on this.  Please let me know if there are objections.

**Pull request merged**
