### PR TITLE
Update index.html back to sphinx version.

### PR DESCRIPTION
**Pull request by daspecster**
Update navigation and glcoud references.

### CODE REVIEW

**Comment by dhermes** [comment]
Can you give a preview of the new homepage?

**Comment by daspecster** [comment]
Site: http://daspecster.github.io/google-cloud-python

I just noticed that when you click "Read the docs" the dropdown for switching languages has the wrong links in it.

**Comment by daspecster** [comment]
@dhermes, how does this look?

**Comment by dhermes** [comment]
LGTM, maybe squash commits?

ASIDE: Could you explain what happened to `home.html` / how much of it remains / what did it do eventually?

**Comment by daspecster** [comment]
Squshed!

`home.html` is for the gcloud-common doc site. It's location and name are defined in the `manifest.json`. 

The `src` and `json` folders are all that's left from the gcloud-common site.
I can remove those as well if you want but I'll need to get our repo removed from ['deploy-docs.sh`](https://github.com/GoogleCloudPlatform/gcloud-common/blob/2f993baaae156fed8c885d788d8d84b0195c7ac0/deploy-docs.sh#L80).

**Comment by dhermes** [comment]
@daspecster I'd say you should proceed as follows:

1. First remove our repo from `deploy-docs.sh`
1. Then remove the `src` and `json` folders (and anything else that's dead) from `gh-pages` and do it in this PR

**Comment by daspecster** [comment]
1. Done: https://github.com/GoogleCloudPlatform/gcloud-common/pull/183
2: Done!

**Comment by dhermes** [comment]
@daspecster It seems that `versions.html` should stick around for old docsets:
https://googlecloudplatform.github.io/google-cloud-python/versions.html

**Comment by daspecster** [comment]
@dhermes I added `versions.html` back and updated the links.
I'll squash before merging if this looks good?

**Comment by dhermes** [comment]
LGTM. No need to squash, in that it could be painful.

Regarding the updating of `versions.html`, it's kind of the same idea as old docs versions. If they break, they break and that's OK.

**Pull request merged**
