### PR TITLE
Spanner 1.0.0 Release

### PR DESCRIPTION
**Pull request by chemelnucfin**
Thanks @jonparrott.

### CODE REVIEW

**Comment by jonparrott** [comment]
Updated the changelog slightly, as the gapic changes happened during the last release.

**Comment by chemelnucfin** [comment]
@jonparrott Should I squash it on my end and repush?  otherwise it'd be hard to tag?

**Comment by jonparrott** [comment]
nah we'll squash on merge.

**Comment by jonparrott** [comment]
@chemelnucfin the system tests in the tag build failed https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/5408

this seems to just be due to flakiness considering it passed on Python 3.6, so I'm going to manually push the library to pypi, but could you take a look at the test?

**Comment by chemelnucfin** [comment]
on it.

**Comment by chemelnucfin** [comment]
It might be a server issue as my tests pass.  I'll see if it can be retried on that error.

**Comment by jonparrott** [comment]
sounds good. thank you.

**Comment by chemelnucfin** [comment]
looks like the test retries on ServerErrors, which does not retry on ClientError which 409 is...

**Pull request merged**
