### PR TITLE
Fix broken pandas based tests

### PR DESCRIPTION
**Pull request by supriyagarg**

### CODE REVIEW

**Comment by supriyagarg** [comment]
@jonparrott Looks like the 2 lines not covered are the ones that check if pandas exists, and sets it to None otherwise: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/monitoring-autogen/monitoring/google/cloud/monitoring_v3/_dataframe.py#L21

What is a reasonable way to test this?

**Comment by tseaver** [comment]
@supriyagarg you can just add `  #pragma: NO COVER` to the `except ImportError:` line.

Also, the `lint` failures are:

```python
google/cloud/monitoring_v3/__init__.py:22:80: E501 line too long (80 > 79 characters)
google/cloud/monitoring_v3/__init__.py:44:80: E501 line too long (90 > 79 characters)
```

**Comment by supriyagarg** [comment]
@tseaver: thanks for your comments!
Fixed the coverage and lint errors.

**Comment by jonparrott** [comment]
Thank you, @supriyagarg.

**Pull request merged**
