### PR TITLE
Adding HappyBase to the umbrella package.

### PR DESCRIPTION
**Pull request by dhermes**
Also

- Updating umbrella README to also point out the HappyBase support
- Make distinction in umbrella README between Homepage and API Documentation (they used to point to the same place)
- Updating some HTTP links to HTTPS in README and CONTRIBUTING (I was surprised to find out that semver.org and Flask docs don't have HTTPS support.)

### CODE REVIEW

**Comment by dhermes** [comment]
See https://github.com/dhermes/google-cloud-python/blob/add-happybase-refs/README.rst for preview of the changes

**Comment by daspecster** [comment]
@dhermes does this mess with that whole licensing thing a while ago?

**Comment by dhermes** [comment]
I don't think so?

**Comment by daspecster** [comment]
After re-reading that issue and noting https://github.com/GoogleCloudPlatform/google-cloud-python-happybase/blob/master/LICENSE I think I'm just being paranoid.

**Comment by dhermes** [comment]
@jonparrott You think we're good to merge here?

**Comment by jonparrott** [comment]
Merge away.

**Pull request merged**
