### PR TITLE
Allow datastore client to connect to emulator host.

### PR DESCRIPTION
**Pull request by ziplokk1**
Fix for issue #3920 
Updated PR for #4794 

Code Example:

```python
# This assumes you have the datastore emulator running on localhost:8081
from google.cloud import datastore

import os
os.environ['DATASTORE_EMULATOR_HOST'] = 'localhost:8081'

ds_client = datastore.Client()
key = ds_client.key('Testing', 'test')
entity = datastore.Entity(key)
entity.update({
    'hello': 'world'
})

ds_client.put(entity)
print(ds_client.get(key))
```

### CODE REVIEW

**Comment by ziplokk1** [comment]
Not quite sure why the tests are failing.

Everything works fine on my end with the exception of py3.4 since I dont have it installed.

Failed Tests From CircleCI:
```
 TestClient.test_can_instantiate_without_project_when_datastore_emulator_host_is_set 
Traceback (most recent call last):
  File "/var/code/gcp/datastore/tests/unit/test_client.py", line 1161, in test_can_instantiate_without_project_when_datastore_emulator_host_is_set
    client = Client()
  File "/var/code/gcp/datastore/google/cloud/datastore/client.py", line 212, in __init__
    project=project, credentials=credentials, _http=_http)
  File "/var/code/gcp/.nox/default/lib/python3.6/site-packages/google/cloud/client.py", line 216, in __init__
    Client.__init__(self, credentials=credentials, _http=_http)
  File "/var/code/gcp/.nox/default/lib/python3.6/site-packages/google/cloud/client.py", line 129, in __init__
    credentials, _ = google.auth.default()
  File "/var/code/gcp/.nox/default/lib/python3.6/site-packages/google/auth/_default.py", line 283, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or
explicitly create credential and re-run the application. For more
information, please see
https://developers.google.com/accounts/docs/application-default-credentials.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/code/gcp/datastore/tests/unit/test_client.py", line 1163, in test_can_instantiate_without_project_when_datastore_emulator_host_is_set
    raise AssertionError('datastore client failed to instantiate. {}'.format('DefaultCredentialsError'))
AssertionError: datastore client failed to instantiate. DefaultCredentialsError
------------------------------ Captured log call -------------------------------
_http_client.py            101 DEBUG    Making request: GET http://169.254.169.254
_metadata.py                81 INFO     Compute Engine Metadata server unavailable.
_____ TestClient.test_can_instantiate_without_project_when_gcd_host_is_set _____
Traceback (most recent call last):
  File "/var/code/gcp/datastore/tests/unit/test_client.py", line 1173, in test_can_instantiate_without_project_when_gcd_host_is_set
    client = Client()
  File "/var/code/gcp/datastore/google/cloud/datastore/client.py", line 212, in __init__
    project=project, credentials=credentials, _http=_http)
  File "/var/code/gcp/.nox/default/lib/python3.6/site-packages/google/cloud/client.py", line 216, in __init__
    Client.__init__(self, credentials=credentials, _http=_http)
  File "/var/code/gcp/.nox/default/lib/python3.6/site-packages/google/cloud/client.py", line 129, in __init__
    credentials, _ = google.auth.default()
  File "/var/code/gcp/.nox/default/lib/python3.6/site-packages/google/auth/_default.py", line 283, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or
explicitly create credential and re-run the application. For more
information, please see
https://developers.google.com/accounts/docs/application-default-credentials.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/code/gcp/datastore/tests/unit/test_client.py", line 1175, in test_can_instantiate_without_project_when_gcd_host_is_set
    raise AssertionError('datastore client failed to instantiate. {}'.format('DefaultCredentialsError'))
AssertionError: datastore client failed to instantiate. DefaultCredentialsError
------------------------------ Captured log call -------------------------------
_http_client.py            101 DEBUG    Making request: GET http://169.254.169.254
_metadata.py                81 INFO     Compute Engine Metadata server unavailable.
2 failed, 352 passed in 9.23 seconds
```

All Tests Passed On My Local Machine:
```
Required test coverage of 97% reached. Total coverage: 99.98%
354 passed in 4.31 seconds
nox > Session unit(py='3.6') was successful.
nox > Ran multiple sessions:
nox > * unit(py='2.7'): success
nox > * unit(py='3.4'): failed
nox > * unit(py='3.5'): success
nox > * unit(py='3.6'): success
```

**Comment by chemelnucfin** [comment]
Hello, it seems like you left a line to `_make_credentials` for the test that fails.  And pass in the credentials and the `project=None` to the `make_one` function.  Please let me know if that solves the problem.

Thanks.

**Comment by ziplokk1** [comment]
Ok, I got it all figured out. Please see #4818 .

```
Giving this another go.

I realized after deep diving that the logic was already there to accept the datastore emulator host but wasn't working without the credentials.

Just patched it up a little bit and added a test to make sure that it works without any default credentials.

I think I'm on the right track this time. I ran the tests in a docker container so that my default creds wouldn't interfere with the testing and everything passed. So hopefully all the circle.ci tests will pass.

Sorry about all the PRs.
```

**Comment by ziplokk1** [comment]
Closed because fix is in another branch.

**Pull request closed without merging**
