### PR TITLE
Storage release 0.23.1

### PR DESCRIPTION
**Pull request by daspecster**
# Storage 0.23.1

- #2991 (de5d8e1) Add 'Blob.update_storage_class' API method.

### CODE REVIEW

**Comment by daspecster** [comment]
Release tag: https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/storage-0.23.1

**Comment by tseaver** [comment]
I'm still sad about releasing features in a third-dot.

**Comment by daspecster** [comment]
So this didn't really qualify as a patch?

**Comment by tseaver** [comment]
It adds a method / exposes a new API feature (assigning a storage class to a blob).  The issue is that cod written to use the feature will break if used with an earlier version of the same 0.23 release line.

**Comment by daspecster** [comment]
So you're saying it should have been 0.24?

**Comment by tseaver** [comment]
That would've been my preference.  @lukesneeringer has a different take on it, though.

**Pull request merged**
