### PR TITLE
Removing support for API_KEY auth in translate.

### LINKED ISSUE #2734: Remove support for API_KEY in translation
See #2731

### PR DESCRIPTION
**Pull request by dhermes**
Fixes #2734.

/cc @jonparrott @jgeewax

### CODE REVIEW

**Comment by lukesneeringer** [comment]
Hey folks -- what was the reason why we did this? I went down the rabbit hole and I can see that everyone agreed it was a good idea, but nowhere can I find an explanation as to why.

Cards on table: I had a "bug" filed on this recently, and so I need to grok what the appropriate answer is (e.g. whether to put this support back, or say that we are not going to do it because ______).

**Comment by daspecster** [comment]
@lukesneeringer, as I recall, it was mostly because the API key auth was outside of the normal authentication methods and I believe it was said that API key based auth was going away..or they(backend) were trying to not support it in the future.

**Comment by tseaver** [comment]
@lukesneeringer the description @daspecster gave matches my memory. Sort of an extension of "Special cases aren't special enough to break the rules."

**Comment by jonparrott** [comment]
API keys are strongly being discouraged for Cloud APIs, especially for client libraries targeting backend languages. Omar has more details. :)

**Comment by lukesneeringer** [comment]
Thanks. :-)

**Pull request merged**
