### PR TITLE
Re-enable pylint in info-only mode for all packages

### PR DESCRIPTION
**Pull request by jonparrott**

### CODE REVIEW

**Comment by dhermes** [comment]
A cursory scan looks fine, though ISTM we should have a single `pylint.config.py` at the project root and then every package points at that?

**Comment by jonparrott** [comment]
I'd do that but @lukesneeringer is planning on splitting packages into their own repos.

**Comment by dhermes** [comment]
Yeah in that context it totally makes sense.

**Comment by tseaver** [comment]
@jonparrott I'm missing what makes running pylint this way "advisory only":  can you elaborate?

**Comment by jonparrott** [comment]
@tseaver nox is ignoring its return value, so pylint can fail but the lint session will still pass.

**Comment by jonparrott** [comment]
@dhermes @lukesneeringer y'all got any more of them LGTMs?

**Comment by dhermes** [comment]
LGTM

**Pull request merged**
