### PR TITLE
Closes #4319 - shorten test names

### LINKED ISSUE #4319: Shorten nox session names
Suggestions:

- `nox -s "unit_tests(python_version='3.6')"` becomes `nox -s "unit(py='3.6')"`
- `nox -s "system_tests(python_version='3.6')"` becomes `nox -s "system(py='3.6')"`

This is not important, but should be able to do in a few minutes.

### PR DESCRIPTION
**Pull request by chemelnucfin**
Ok yeah, this didn't take a lot of manual editing (j/k).  If this is the way we go, that should do it.

### CODE REVIEW

**Comment by dhermes** [comment]
Some things that still need to be changed:

-   `CONTRIBUTING.rst` references to these names
-   Any test config file that refers to `python_version`. Checking out your branch and running `git grep python_version` I see:
    ```
    ...
    appveyor.yml:      NOX_ENV: "unit_tests(python_version='2.7')"
    appveyor.yml:      NOX_ENV: "unit_tests(python_version='3.5')"
    ...
    ```

(Also, your branch seems to be a bit behind, I'd recommend a rebase.)

> this didn't take a lot of manual editing (j/k)

Sorry for that. I typically use `sed` in situations like this, e.g.

```
git ls-files '*nox.py' | xargs sed -i s/python_version/py/g
```

**Comment by chemelnucfin** [comment]
yes, I used sed.  ;)
thanks though.

I'll do a grep for the config files.

**Comment by chemelnucfin** [comment]
Are these part of the nox configuration or are they for something else?

api_core/setup.py:    ':python_version<"3.2"': ['futures >= 3.0.0'],
appveyor/install.ps1:function ParsePythonVersion ($python_version) {
language/setup.py:    ':python_version<"3.4"': ['enum34'],
vision/setup.py:    ':python_version<"3.4"': ['enum34'],

All the other instances of python_version doesn't seem like it's relevant
to nox (I could be wrong)

**Comment by dhermes** [comment]
`appveyor/install.ps1` is no longer in `master` (as of #4313), `rebase` is your friend.

The other 3 are configuration and don't have direct impact on `nox`.

**Comment by dhermes** [comment]
LGTM

**Pull request merged**
