### PR TITLE
Speech Release 0.23.1.

### PR DESCRIPTION
**Pull request by daspecster**
# Speech 0.23.1

- #3084 Added missing method documentation and added tests for Result class.

-----------------------
Specifically:
- 8e5cd1e Clean up formatting and docstrings.
- 9f7e1ac Add test file for Result class.

### CODE REVIEW

**Comment by dhermes** [comment]
@daspecster Can you write "release notes for humans"?

**Comment by daspecster** [comment]
@dhermes the ones with the commit hash are just for the review. The release notes are above the horizontal line I just added.

**Comment by lukesneeringer** [comment]
Looks good.

**Comment by dhermes** [comment]
Those commits both come from #3084. 95+% of the changes in that PR are unit test only, and don't warrant a release.

Also, if you were going to do a release, you should include a link to the PR in the notes (see many of our previous release notes for a template).

**Comment by daspecster** [comment]
⚖️  :bowtie:

**Comment by lukesneeringer** [comment]
I am fine with just letting these sit in master and waiting until there is an actual feature.

**Pull request closed without merging**
