### PR TITLE
Release BigQuery O.30.0

### PR DESCRIPTION
**Pull request by jonparrott**

### CODE REVIEW

**Comment by chemelnucfin** [comment]
what about /docs/bigquery/releases.rst?

I was going to push it myself, but that might mess up the tagging and stuff
The line is here for C&P though:
* ``0.30.0`` (`PyPI <https://pypi.org/project/google-cloud-bigquery/0.30.0/>`__, `Release Notes <https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/bigquery-0.30.0>`__)

**Comment by jonparrott** [comment]
ugh we have got to find a way to stop doing that manually. I've forgotten it several times now.

**Comment by chemelnucfin** [comment]
I wrote a python script to do it, but it's very crude.  Should work on setup and releases.  I'll email it to you if you want.  Or is there a tool place to put such things?

Was thinking of pulling out the issues with the tags between releases also, but didn't get to it yet.

**Comment by jonparrott** [comment]
you can send a pr to put it in testing/scripts for the time being.

**Comment by jonparrott** [comment]
if we do want to keep these long-term, I'd like to just write a sphinx plugin to do it.

**Comment by lukesneeringer** [comment]
> ugh we have got to find a way to stop doing that manually. I've forgotten it several times now.

I am not really a fan of these. I am not sure why we started doing them or what problem they solve, and I frequently forget.

**Pull request merged**
