### PR TITLE
Move bigtable code into a subpackage

### PR DESCRIPTION
**Pull request by dhermes**
Towards #2404. See #2367 for a reference point.

### CODE REVIEW

**Comment by dhermes** [comment]
For reference, the 2nd commit is essentially these 3 (from `core`) mushed together:

- https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2367/commits/ea0e291095944931217a420ce5964247c378b191
- https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2367/commits/9a70f16fdc925edf0eddf85fb09bbcc135e4ba6f
- https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2367/commits/8643a914cf949c563a1c2e3f5a3cb269b9ad2639

**Comment by dhermes** [comment]
Just occurred to me that I didn't move the system test.

**Comment by tseaver** [comment]
@dhermes Before merging, what did you decide to do about the system tests?

**Comment by dhermes** [comment]
I punted to #2404 on system tests.

**Comment by tseaver** [comment]
LGTM

**Pull request merged**
