### PR TITLE
Do not attempt to acknowledge 0 messages

### LINKED ISSUE #2878: If AutoAck pull returns empty then exception raised on context exit
If the subscription pull returns 0 messages in the __enter__ method in the AutoAck class then on __exit__ the acknowledge call raises an exception on the HTTP call: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/pubsub-0.22.0/pubsub/google/cloud/pubsub/subscription.py#L512

Currently the way a deal with this is to wrap the context manager in try/except or override __exit__ to check for an empty list. The former is messy and the latter can just be fixed at source.

### PR DESCRIPTION
**Pull request by quom**
Closes #2878

### CODE REVIEW

**Comment by quom** [comment]
I signed it!

**Comment by daspecster** [comment]
@quom I tried to change the title of the PR to be more descriptive but I may have missed the mark. If you have better wording feel free to update!

**Comment by quom** [comment]
Updated it a bit - should have done something similar first time

**Comment by tseaver** [comment]
@quom Thanks very much for the patch!

**Pull request merged**
