### PR TITLE
Storage: Fix coverage issue

### PR DESCRIPTION
**Pull request by chemelnucfin**
Not sure if this is "desired", but it does make the coverage to be 100%.

### CODE REVIEW

**Comment by dhermes** [comment]
@chemelnucfin This is not needed. `nox -s cover` combines coverage from the `nox -s unit` runs for **ALL** versions, so it will hit both branches.

**Comment by chemelnucfin** [comment]
But when you test just a single version, you will wonder what you are missing.

**Comment by dhermes** [comment]
That's not the point?

**Comment by chemelnucfin** [comment]
But it does require extra time to confirm that it wasn't what you did that lowered the coverage, right?

**Comment by dhermes** [comment]
@chemelnucfin I don't follow. Run `nox -s unit cover`?

**Comment by chemelnucfin** [comment]
Is there something wrong with the test though?  It does fix the coverage issue.

**Comment by dhermes** [comment]
> Is there something wrong with the test though?

It's the tail wagging the dog. We (our code) shouldn't work around our tools / language versions, they should work around us.

> It does fix the coverage issue.

There is no coverage issue to fix.

**Pull request closed without merging**
