### PR TITLE
Getters for row key and row table

### PR DESCRIPTION
**Pull request by skyfox**
Pulling out non-controversial part of #3401 for #2411.

### CODE REVIEW

**Comment by dhermes** [comment]
@skyfox This LGTM, I [restarted][1] your build, that failure seems spurious. Fingers crossed.

[1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1863

**Comment by dhermes** [comment]
@skyfox I manually rebased your branch onto the latest version of `master` (sorry if it caused any confusion).

**Comment by dhermes** [comment]
@skyfox Some lines had trailing whitespace and it [failed the `lint` part of the build][1]. I sent a follow-up commit to your branch to resolve (sorry if that was not OK).

I have my editor configured to just strip any trailing whitespace from lines on save.

[1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1866

**Comment by skyfox** [comment]
Thank you for merging!
Going to fix comments for the second part.

**Pull request merged**
