### PR TITLE
BigQuery: missing return value in LoadJobConfig.from_api_repr and LoadJobConfig Tests

### LINKED ISSUE #4726: BigQuery: LoadJobConfig.from_api_repr does not return config
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/63b7245699510259f584bc3ca328a72af8c2120f/bigquery/google/cloud/bigquery/job.py#L677
misses `return config`. Hence cannot build based on a JSON schema file.

### PR DESCRIPTION
**Pull request by chemelnucfin**
Closes #4726

### CODE REVIEW

**Comment by chemelnucfin** [comment]
cover said 100%  I'll take a look.

**Comment by jonparrott** [comment]
Sure, but, clearly there was a bug here that no test caught before. Some test, some where, should be updated to make sure that this returns the right object.

**Comment by dhermes** [comment]
Also @chemelnucfin please make your PR descriptions actually describe what they do (this is **much** more important than the `BigQuery: ` prefix, which is largely irrelevant since we have labels).

**Comment by chemelnucfin** [comment]
@jonparrott @dhermes I'm more curious why cover is not catching it.  Seems like the whole class is missing.
Ok to merge it and then open another issue?

**Comment by jonparrott** [comment]
> Ok to merge it and then open another issue?

No, I'd prefer we take care of this here, especially considering how small this patch is.

**Comment by chemelnucfin** [comment]
ok.

**Comment by chemelnucfin** [comment]
@jonparrott PTAL

@dhermes changed title

Any idea why cover wasn't working?

**Comment by jonparrott** [comment]
> Any idea why cover wasn't working?

Because coverage doesn't have a way of knowing whether you checked the return value.

**Pull request merged**
