### PR TITLE
Upgrading all versions for umbrella release.

### PR DESCRIPTION
**Pull request by dhermes**
I will start working on release notes, but others can feel free to pitch in.

---

To get it started (moved to [Datastore post][1])

- [x] [Umbrella][7]
- [ ] [BigQuery][8]
- [ ] [Bigtable][9]
- [x] [HappyBase][19]
- [x] [Core][10]
- [x] [Datastore][1]
- [x] [DNS][11]
- [x] [Error Reporting][12]
- [ ] [Language][4]
- [x] [Logging][13]
- [x] [Monitoring][14]
- [x] [Pub / Sub][15]
- [x] [Resource Manager][16]
- [ ] [Runtime Config][17]
- [x] [Spanner][18]
- [ ] [Speech][2]
- [ ] [Storage][6]
- [ ] [Translate][5]
- [ ] [Vision][3]

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3068#issuecomment-282403830
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3068#issuecomment-282394076
[3]: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3068#issuecomment-282395889
[4]: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3068#issuecomment-282397227
[5]: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3068#issuecomment-282397899
[6]: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3068#issuecomment-282398602
[7]: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3068#issuecomment-282404762
[8]: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3068#issuecomment-282404969
[9]: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3068#issuecomment-282405084
[10]: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3068#issuecomment-282405139
[11]: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3068#issuecomment-282405179
[12]: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3068#issuecomment-282405227
[13]: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3068#issuecomment-282405252
[14]: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3068#issuecomment-282405308
[15]: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3068#issuecomment-282405342
[16]: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3068#issuecomment-282405667
[17]: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3068#issuecomment-282405715
[18]: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3068#issuecomment-282405825
[19]: https://github.com/GoogleCloudPlatform/google-cloud-python-happybase/pull/20

### CODE REVIEW

**Comment by daspecster** [comment]
# Speech

```bash
git log speech-0.22.0..umbrella-release-0.23.0 -- speech
```

yields

- 9ebef22	Danny Hermes	2017-02-23	Isolating speech Connection in _http module.
- 2c608f9	Luke Sneeringer	2017-02-22	Speech Client Library Header (#3048)
- 08785e4	Danny Hermes	2017-02-22	Adding GCCL header for HTTP APIs. (#3046)
- 5e2300f	Danny Hermes	2017-02-16	Renaming all remaining connection.py modules as _http.py.
- 635f439	Thomas Schultz	2017-02-16	Update core dependency to google-cloud-core >= 0.23.0, < 0.24dev. (#3028)
- d6a51d9	Thomas Schultz	2017-02-15	Update Beta classifiers to Alpha for specified services.
- e4661b0	Thomas Schultz	2017-02-14	Fix build failing with float precision mismatch (#3002)
- a6bf059	Thomas Schultz	2017-02-06	Rename and move _JSONSpeechAPI to HTTPSpeechAPI. (#2979)
- de65409	Thomas Schultz	2017-02-06	Fix Speech LRO handling and add HTTP side for multiple results.  (#2965)
- 45d81a0	Danny Hermes	2017-01-26	Fix-up docstrings after Connection() signature change.
- f0adea3	Danny Hermes	2017-01-26	Changing speech Connection to only accept client.
- a70815d	Luke Sneeringer	2017-01-25	Cloud Speech Veneer does not raise for > 1 result. (#2962)
- 89e6056	Luke Sneeringer	2017-01-25	Remove default sample_rate.
- 163d578	Thomas Schultz	2017-01-17	Update import spacing in tests.
- cf7378f	Thomas Schultz	2016-12-09	Make sample.content handle bytes and files.
- 2c42b7c	Danny Hermes	2016-12-14	Manually creating Client._connection in subclasses.
- 8d3bcde	Thomas Schultz	2016-12-12	Fix versions badge image url.


## Release Notes:

- #3048 (2c608f9), #3046 (08785e4) Add Speech Client Library Header.
- #3028 (635f439) Update core dependency to google-cloud-core >= 0.23.0, < 0.24dev.
- #3027 (d6a51d9) Update Beta classifiers to Alpha for specified services.
- #2965 (de65409) Fix Speech LRO handling and add HTTP side for multiple results.
- #2963 (89e6056) Remove default sample_rate.
- #2850 (cf7378f) Make sample.content handle bytes and files.

**Comment by daspecster** [comment]
# Vision

```bash
git log vision-0.22.0..umbrella-release-0.23.0 -- vision
```

yields

- 1542e97	Danny Hermes	2017-02-23	Isolating vision Connection in _http module.
- c525b44	Luke Sneeringer	2017-02-22	GAPIC Header Consistency: Vision (#3050)
- 08785e4	Danny Hermes	2017-02-22	Adding GCCL header for HTTP APIs. (#3046)
- 5e2300f	Danny Hermes	2017-02-16	Renaming all remaining connection.py modules as _http.py.
- 635f439	Thomas Schultz	2017-02-16	Update core dependency to google-cloud-core >= 0.23.0, < 0.24dev. (#3028)
- d6a51d9	Thomas Schultz	2017-02-15	Update Beta classifiers to Alpha for specified services.
- e4661b0	Thomas Schultz	2017-02-14	Fix build failing with float precision mismatch (#3002)
- db0dc85	Thomas Schultz	2017-02-09	Vision: Add batch processing (#2978)
- f822e44	Thomas Schultz	2017-01-30	Fix KeyError for unsupported annotation types. (#2961)
- 3584917	Danny Hermes	2017-01-30	Merge pull request #2970 from dhermes/cnxn-client-hygiene
- f8ceb94	Thomas Schultz	2017-01-30	Vision support for batch processing part one. (#2967)
- 45d81a0	Danny Hermes	2017-01-26	Fix-up docstrings after Connection() signature change.
- a65f754	Danny Hermes	2017-01-26	Changing vision Connection to only accept client.
- b53be84	Danny Hermes	2017-01-26	Renaming JSONClient -> ClientWithProject.
- 1086bc4	Thomas Schultz	2017-01-17	Add GAPIC support for safe search.
- c9b6732	Thomas Schultz	2017-01-06	Add GAPIC support for image properties detection.
- 04517cd	Thomas Schultz	2017-01-06	Add GAPIC support for face detection.
- 7ff033d	Thomas Schultz	2017-01-04	Add gax support for entity annotations.
- 7d42de8	Thomas Schultz	2017-01-03	Add gRPC conversion helper functions.
- aa5bce5	Thomas Schultz	2016-12-27	Add a starter class for _gax.
- 74e537b	Thomas Schultz	2016-12-08	Separate HTTP client.
- 2c42b7c	Danny Hermes	2016-12-14	Manually creating Client._connection in subclasses.

## Release Notes

- #3046 (08785e4), #3050 (c525b44) Adding GCCL header for HTTP APIs.
- #3028 (635f439) Update core dependency to google-cloud-core >= 0.23.0, < 0.24dev.
- #3027  (d6a51d9) Update Beta classifiers to Alpha for specified services.
- #2961 (f822e44) Fix KeyError for unsupported annotation types.
- #2967 (f8ceb94), #2978 (db0dc85) Vision support for batch processing.
- a65f754	Danny Hermes	2017-01-26	Changing vision Connection to only accept client.
- #2938 (1086bc4), #2937 (c9b6732), #2922 (04517cd),  #2918 (7ff033d)  Add GAPIC/gRPC support to Vision.

**Comment by daspecster** [comment]
# Language

```bash
git log language-0.22.2..umbrella-release-0.23.0 -- language
```
yields

- bba3c86	Luke Sneeringer	2017-02-24	Send back the complete API responses. (#3059)
- 08785e4	Danny Hermes	2017-02-22	Adding GCCL header for HTTP APIs. (#3046)
- 5e2300f	Danny Hermes	2017-02-16	Renaming all remaining connection.py modules as _http.py.
- 635f439	Thomas Schultz	2017-02-16	Update core dependency to google-cloud-core >= 0.23.0, < 0.24dev. (#3028)
- d6a51d9	Thomas Schultz	2017-02-15	Update Beta classifiers to Alpha for specified services.
- 4d2a7d1	Luke Sneeringer	2017-02-07	Rename `document_from_url` to `document_from_gcs_url`. (#2986)
- 65213a1	Luke Sneeringer	2017-02-06	Do not include a default language. (#2985)
- 45d81a0	Danny Hermes	2017-01-26	Fix-up docstrings after Connection() signature change.
- 725b4f0	Danny Hermes	2017-01-26	Changing language Connection to only accept client.
- f25cfdc	Thomas Schultz	2017-01-18	Update import spacing part 2.
- 2c42b7c	Danny Hermes	2016-12-14	Manually creating Client._connection in subclasses.

## Release Notes

- #3059 (bba3c86) Send back the complete API responses.
- #3046 (08785e4) Adding GCCL header for HTTP APIs.
- #3028 (635f439) Update core dependency to google-cloud-core >= 0.23.0, < 0.24dev.
- #3027 (d6a51d9) Update Beta classifiers to Alpha for specified services.
-  #2986 (4d2a7d1) Rename `document_from_url` to `document_from_gcs_url`.
- #2985 (65213a1) Do not include a default language.

**Comment by daspecster** [comment]
# Translate

```bash
git log translate-0.22.0..umbrella-release-0.23.0 -- translate/
```

yields

- 08785e4 Adding GCCL header for HTTP APIs. (#3046)
- 5e2300f Renaming all remaining connection.py modules as _http.py.
- 635f439 Update core dependency to google-cloud-core >= 0.23.0, < 0.24dev. (#3028)
- d6a51d9 Update Beta classifiers to Alpha for specified services.
- 45d81a0 Fix-up docstrings after Connection() signature change.
- 683ce71 Changing translate Connection to only accept client.
- 163d578 Update import spacing in tests.
- 2c42b7c Manually creating Client._connection in subclasses.
- 2f75184 Update Translation API branding.

## Release Notes

- #3046 (08785e4) Adding GCCL header for HTTP APIs.
- #3028 (635f439) Update core dependency to google-cloud-core >= 0.23.0, < 0.24dev.
- #3027 (d6a51d9) Update Beta classifiers to Alpha for specified services.

**Comment by daspecster** [comment]
# Storage

```bash
git log storage-0.22.0..umbrella-release-0.23.0 -- storage/
```
yields

- 08785e4 Adding GCCL header for HTTP APIs. (#3046)
- 3da453c Adding ability to send version info header on HTTP requests.
- 0a311f7 Add generate_upload_policy (#2998)
- 635f439 Update core dependency to google-cloud-core >= 0.23.0, < 0.24dev. (#3028)
- 9619004 Add create_resumable_upload_session (#2989)
- ed0698f Updates for pycodestyle. (#2973)
- 111c7ef Changing storage Connection to only accept client.
- b53be84 Renaming JSONClient -> ClientWithProject.
- 163d578 Update import spacing in tests.
- 40fd881 Add storage.blob property time_created (timeCreated) (#2933)
- 2c42b7c Manually creating Client._connection in subclasses.

## Release Notes

- #3046 (08785e4), #3035 (3da453c) Adding GCCL header for HTTP APIs.
- #2998 (0a311f7) Add generate_upload_policy.
- #3028 (635f439) Update core dependency to google-cloud-core >= 0.23.0, < 0.24dev.
- #2989 (9619004) Add create_resumable_upload_session. Thanks @jonparrott!
- #2933 (40fd881) Add storage.blob property time_created (timeCreated)

**Comment by dhermes** [comment]
## Datastore

```
$ git log datastore-0.22.0..umbrella-release-0.23.0 -- datastore/
```

yields

- `google.cloud.datastore.__version__` attribute added (#3046)
- On HTTP requests, sending `X-Goog-API-Client` header with value `gl-python/x.y.z gccl/a.b.c` where `x.y.z` is the version of Python that is running and `a.b.c` is the version of the datastore package being used (#3035)
- Storing all connection data on `Client` instead of on private `Connection` (#2970)
- Removing `__all__` from `google.cloud.datastore.helpers` (previously wasn't exposing `entity_to_protobuf` / `GeoPoint`) (#2916)
- #3064 - impl. only, not for release notes
- #3066 - impl. only, not for release notes
- #3036 - impl. only, not for release notes
- #3028 - deps only, not for release notes
- #3008 - docs collision (with Spanner), made short names more explicit, not for release notes
- #2973 - hygiene, not for release notes
- #2946 - hygiene, not for release notes
- #2911 for some reason never got a `datastore-0.22.1` tag, not for release notes
- #2876 (in `0.22.1`)
- #2870 (in `0.22.1`)

**Comment by dhermes** [comment]
# Umbrella

Placeholder

**Comment by dhermes** [comment]
# BigQuery

Placeholder

**Comment by dhermes** [comment]
# Bigtable

Placeholder

**Comment by dhermes** [comment]
# Core

Placeholder

**Comment by dhermes** [comment]
# DNS

Placeholder

**Comment by dhermes** [comment]
# Error Reporting

Placeholder

**Comment by dhermes** [comment]
# Logging

Placeholder

**Comment by dhermes** [comment]
# Monitoring

Placeholder

**Comment by dhermes** [comment]
# Pub / Sub

Placeholder

**Comment by dhermes** [comment]
# Resource Manager

Placeholder

**Comment by dhermes** [comment]
# Runtime Config

Placeholder

**Comment by dhermes** [comment]
# Spanner

Placeholder

**Comment by dhermes** [comment]
Also updated and used https://gist.github.com/dhermes/a4e097f2f80fd490b256fc3aa2b4a46b to release https://pypi.python.org/pypi/google-cloud-natural-language/0.23.0

**Pull request merged**
