### PR TITLE
Re-enable 'Bucket.requester_pays' feature

### LINKED ISSUE #3474: Add support for "requester pays" operations
The storage docs don't really explain this, but the JSON API methods have begun to accept a `userProject' query parameter (or is it a header?  only its yak-shaver knows for sure). The point of it looks to be to bill any charges associated with the request to a different project than the one which owns the bucket in which it takes place.  I can't tell how a bucket owner is supposed to configure things such that foreign projects can *only* access objects by passing this parameter/header.

See the [g-c-dotnet PR](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/pull/1085) implementing preliminary support.

And hre is the [g-c-php PR](https://github.com/GoogleCloudPlatform/google-cloud-php/pull/527).

### PR DESCRIPTION
**Pull request by tseaver**
Closes #3474.

Needs extra system tests which pass `user_project` to the various APIs which take it, in the context of a bucket which is created with `requester_pays` enabled.

### CODE REVIEW

**Comment by dhermes** [comment]
@tseaver How much of this has been reviewed and how much is new? (Sorry if that is a question I should know the answer to.)

**Comment by tseaver** [comment]
@dhermes This was all reviewed back in June:  I just re-built the branch because the reversion made it hard to see what would be landed this time.

**Comment by dhermes** [comment]
@tseaver Great. So no review needed?

**Comment by tseaver** [comment]
@dhermes Not until we resolve whether / how we will implement the additional system tests.

**Comment by tseaver** [comment]
@lukesneeringer I believe that this branch is ready to merge to `master`.  Two open issues:

- The known back-end incompatibility between `objects.rewrite` and `user_project` (#4125).
- Enabling CI for the new features via an environment variable (we need to decide the target project). (#4126)

**Comment by tseaver** [comment]
Unrelated Appveyour failure (see #4128).

**Comment by tseaver** [comment]
@lukesneeringer AFAIK, this branch is ready to merge.

**Pull request merged**
