### PR TITLE
Test commit: inspect the env. vars. Travis uses.

### PR DESCRIPTION
**Pull request by dhermes**
This is sniffing around towards #2277, to see how much info we can use to restrict the tests we run.

---

Context: I tried to build a similar feature in late 2014 / early 2015 and the env. vars. weren't very useful. Hoping that has changed in the last two years.

### CODE REVIEW

**Comment by dhermes** [comment]
FWIW I'm [expecting these vars][1]:

```
TRAVIS_SECURE_ENV_VARS
TRAVIS_PULL_REQUEST
TRAVIS
TRAVIS_BRANCH
TRAVIS_BUILD_DIR
TRAVIS_BUILD_ID
TRAVIS_BUILD_NUMBER
TRAVIS_COMMIT
TRAVIS_COMMIT_RANGE
TRAVIS_EVENT_TYPE
TRAVIS_JOB_ID
TRAVIS_JOB_NUMBER
TRAVIS_OS_NAME
TRAVIS_PULL_REQUEST
TRAVIS_REPO_SLUG
TRAVIS_SECURE_ENV_VARS
TRAVIS_TEST_RESULT
TRAVIS_TAG
TRAVIS_PYTHON_VERSION
```

[1]: https://docs.travis-ci.com/user/environment-variables#Default-Environment-Variables

**Comment by dhermes** [comment]
`TRAVIS_COMMIT` (https://github.com/GoogleCloudPlatform/google-cloud-python/commit/07128f1ff0a3930c837728e39d9453984a75efbb) seems to be a temporary merge commit of `HEAD` in this branch merged into `HEAD` of `master`, and those are the first and last (respectively) in `TRAVIS_COMMIT_RANGE`

**Comment by dhermes** [comment]
I rebased on top master (#2305 was merged) and adding another commit on top to see how it changes `TRAVIS_COMMIT_RANGE`

**Comment by dhermes** [comment]
In the [latest build][1], the only env. var. changes were:

```
TRAVIS_BUILD_ID: 159472570
TRAVIS_BUILD_NUMBER: 4810
TRAVIS_COMMIT: c9e955423f57e99a6be2fda7e4b73ff1a9f5beac
TRAVIS_COMMIT_RANGE: 397014a17d80225526b86d5894780e1544a67175...dfbf929a6ca8426c6afeeccd2e587a34d65cb3e7
TRAVIS_JOB_ID: 159472571
TRAVIS_JOB_NUMBER: 4810.1
```

After the rebase the `HEAD` commit in master moved to 397014a17d80225526b86d5894780e1544a67175 and the 2 commits in this PR became:

1. b6f6ed47ca8bc5d58f9fd9e4519105667db86926
1. dfbf929a6ca8426c6afeeccd2e587a34d65cb3e7

As before c9e955423f57e99a6be2fda7e4b73ff1a9f5beac is a hidden commit that merges my branch into `HEAD` (i.e. dfbf929a6ca8426c6afeeccd2e587a34d65cb3e7 into 397014a17d80225526b86d5894780e1544a67175)

[1]: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/159472570

**Comment by dhermes** [comment]
From [How-Pull-Requests-are-Tested][1]

> Rather than test the commits that have been pushed to the branch the pull request is from, we test the merge between the origin and the upstream branch. To only build on push events, you can disable Build on Pull Requests from your repository settings.

[1]: https://docs.travis-ci.com/user/pull-requests#How-Pull-Requests-are-Tested

**Comment by dhermes** [comment]
I'm going to push this `dont-merge-2277-sleuthing` into https://github.com/GoogleCloudPlatform/google-cloud-python/ to see what the differences are there:
https://github.com/GoogleCloudPlatform/google-cloud-python/tree/dont-merge-2277-sleuthing

**Comment by dhermes** [comment]
ENV VARS: In the [pull request build][1] the usual players changed. In the ["push" build][2], there are some differences:

```
# These ones seem to change with each PR / push
TRAVIS_SECURE_ENV_VARS: true               # vs. false
TRAVIS_BRANCH: dont-merge-2277-sleuthing   # vs. master
TRAVIS_EVENT_TYPE: push                    # vs. pull_request
TRAVIS_PULL_REQUEST: false                 # vs. 2309
```

Also `TRAVIS_COMMIT` is the actual commit at the tip of the branch (i.e. the one that was pushed, c274f02461c82627cc10a71185df46e6091f97a8) and `TRAVIS_COMMIT_RANGE` covers a range I can't quite parse. The beginning commit (7147a65354d1905b225dc4ab96487cfa17746bed) isn't in the branch history while the 2nd (c274f02461c82627cc10a71185df46e6091f97a8) is just the final commit in that branch. The mystery commit seems to have the same parent and to be the same commit, so I'm not sure what the difference is (maybe worth digging into the [GitHub hooks API][3]):

```
$ git log -1 7147a65354d1905b225dc4ab96487cfa17746bed^ --pretty=%H
58ef62114a8f38295be5fa93311593c8eeb66683
$ git log -1 c274f02461c82627cc10a71185df46e6091f97a8^ --pretty=%H
58ef62114a8f38295be5fa93311593c8eeb66683
```

Also, the commit hashes in `TRAVIS_COMMIT_RANGE` are 12 chars instead of the full 40 as we've seen in pull request builds (this is also different than the `--pretty=%h` length, which is 7).

----

As for the state of the `git` checkout in each, the PR is checked out at [`FETCH_HEAD`][4] which is just the result of running

```
$ git fetch origin +refs/pull/2309/merge:
$ git checkout -qf FETCH_HEAD
```

while the "push" build is checked out at a detached `HEAD` for the lead commit in the branch (c274f02461c82627cc10a71185df46e6091f97a8). This is done explicitly

```
$ git checkout -qf c274f02461c82627cc10a71185df46e6091f97a8
```

In either case, there is only one `git` remote (I was curious in a pull request if the originating fork could be found anywhere).

Finally, a limited checkout is in place, making sure `master` is the only fetched branch in the PR build and `dont-merge-2277-sleuthing` is the only branch in the "push" build:

```
$ git clone --depth=50                                    ...
$ git clone --depth=50 --branch=dont-merge-2277-sleuthing ...
```

[1]: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/159705869
[2]: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/159705857
[3]: https://developer.github.com/v3/repos/hooks/
[4]: http://stackoverflow.com/a/9237511/1068170

**Comment by dhermes** [comment]
It looks like some new vars like `TRAVIS_PULL_REQUEST_BRANCH` and `TRAVIS_PULL_REQUEST_SHA` have been added so I triggered a [new build][1].

[1]: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/165102067

**Comment by dhermes** [comment]
I just pushed a [tag][2] to trigger a [tag build][1]. Have already deleted tag, but the build remains.

The changes we see are as follows

```
TRAVIS_TAG: dont-tag-sleuth     | TRAVIS_TAG:
TRAVIS_BRANCH: dont-tag-sleuth  | TRAVIS_BRANCH: master
TRAVIS_EVENT_TYPE: push         | TRAVIS_EVENT_TYPE: pull_request
TRAVIS_PULL_REQUEST: false      | TRAVIS_PULL_REQUEST: 2309
TRAVIS_PULL_REQUEST_BRANCH:     | TRAVIS_PULL_REQUEST_BRANCH: dont-merge-2277-sleuthing
TRAVIS_PULL_REQUEST_SHA:        | TRAVIS_PULL_REQUEST_SHA: d4bc9d575e95146071b9892edf0b467a91f49f4c
```

- It's not surprising to see `TRAVIS_TAG` get populated nor is it surprising to see `TRAVIS_PULL_REQUEST` be false or `TRAVIS_PULL_REQUEST_BRANCH` / `TRAVIS_PULL_REQUEST_SHA` be empty
- It is somewhat surprising that `TRAVIS_EVENT_TYPE` is `push` rather than something more specialized (like `tag`)
- It **IS** surprising that the `TRAVIS_BRANCH` is given, since a `tag` doesn't have any real branch

[1]: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/165104254
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/dont-tag-sleuth

**Comment by lukesneeringer** [comment]
Superceded by #3146.

**Pull request closed without merging**
