### PR TITLE
Model/parse 'job.cancel' API response correctly.

### LINKED ISSUE #2377: '_AsyncQuery.cancel' fails to update from returned resource
E.g.:

```python
Traceback (most recent call last):
  File ...
    job.cancel()
  File ".../google/cloud/bigquery/job.py", line 378, in cancel
    self._set_properties(api_response)
  File ".../google/cloud/bigquery/job.py", line 262, in _set_properties
    self._scrub_local_properties(cleaned)
  File ".../google/cloud/bigquery/job.py", line 1050, in _scrub_local_properties
    configuration = cleaned['configuration']['query']
KeyError: 'configuration'
```

The [docs for `job.cancel`](https://cloud.google.com/bigquery/docs/reference/v2/jobs/cancel#response) show that the job resource is in a `job` subkey of the response.

### PR DESCRIPTION
**Pull request by tseaver**
Closes #2377.

### CODE REVIEW

**Comment by dhermes** [comment]
@tseaver mostly looks good but there is still creep due to #2315 being open. Can we pretty please fix that?

Sorry I didn't comment inline, mobile web version not as easy to use in a pinch

**Comment by tseaver** [comment]
@dhermes I'd argue that the redundancy here is more tolerable:  asserting that the job is in `done` state is the only really useful check on the outcome of `job.cancel()`.

**Comment by dhermes** [comment]
Right but it's already been checked so it's redundant (as you said) to check it again

**Comment by tseaver** [comment]
It is redundant, but kind of hidden from the user:  asserting it again is for clarity, not correctness.

**Comment by dhermes** [comment]
Do as you wish. The statement is just a few lines up if a future maintainer seeks clarity

**Comment by tseaver** [comment]
@dhermes 14b8cc4 replaces the redundant assert with a comment explaining why not assertions are made.

**Pull request merged**
