### PR TITLE
Release Logging 0.23.2.

### PR DESCRIPTION
**Pull request by daspecster**
# Logging 0.23.2

- 09ae157 Removing overly broad mock.Mock() in logging.

### CODE REVIEW

**Comment by dhermes** [comment]
We're doing a release based on unit test changes?

**Comment by daspecster** [comment]
@lukesneeringer wanted to do releases for non-breaking changes but I may have taken that definition too broadly.

WDYT @lukesneeringer?

**Comment by dhermes** [comment]
This is beyond a non-breaking change, it's a non-change.

**Comment by lukesneeringer** [comment]
You can hold off on this one.

**Pull request closed without merging**
