### PR TITLE
Fix packaging of tests and resources

### PR DESCRIPTION
**Pull request by jonparrott**
- Don't include tests in the binary (wheel) distribution.
- Include tests in the source distribution.
- Include only .json and .proto package resources.
- Include a LICENSE with every package (extremely important for downstream packagers).
(From #3182)

### CODE REVIEW

**Comment by jonparrott** [comment]
I need to rebase on top of `ci`, will do shortly.

**Comment by jonparrott** [comment]
@lukesneeringer @dhermes rebased, should be good to review now.

**Comment by lukesneeringer** [comment]
LGTM once I get `ci` in.

**Comment by jonparrott** [comment]
Since `ci` is already in review and this won't pass while targeting that branch, do we want to go ahead and merge this into `ci`?

**Comment by dhermes** [comment]
:+1: to what @jonparrott said

**Comment by lukesneeringer** [comment]
Yep, doing it.

**Pull request merged**
