### PR TITLE
Adding check that **all** setup.py README's are valid RST.

### LINKED ISSUE #2246: Broken links abound in SD docs
I'm trying to read the docs for the SD monitoring API. Broken links abound.

I'm starting at: https://googlecloudplatform.github.io/gcloud-python/#/docs/master/gcloud/monitoring

I click on the link for details about "Monitored Resource Descriptors" which hover says will go to https://googlecloudplatform.github.io/gcloud-python/#/docs/master/gcloud/monitoring/index/resourcedescriptor but my browser actually ends up at https://googlecloudplatform.github.io/gcloud-python/#/docs/master/gcloud which has no content.

I hit back and figure I'll just look at the source since the docs are broken, so I hit "Source Code" down the bottom of the original page, which takes me to https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/ which is a complete 404 served by github.

### LINKED ISSUE #2446: [QUESTION] Check validity of `setup.py` in build
H/T to http://inre.dundeemt.com/2014-05-17/pypi-setup-py-keeping-a-dry-long_description/ (I was Googling around for DRY in `setup.py`)

```
python setup.py check --restructuredtext --strict
```

---

For example, running it on the post #2442 version gives:

```
$ python setup.py check --restructuredtext --strict
running check
warning: check: Duplicate implicit target name: "contributing".

warning: check: Duplicate implicit target name: "license".

error: Please correct your package.
```

because we have sections named license and contributing as well as links with those names. This could be fixed via

``` diff
diff --git a/README.rst b/README.rst
index 715368b..bbf0f72 100644
--- a/README.rst
+++ b/README.rst
@@ -96,16 +96,16 @@ Contributing

 Contributions to this library are always welcome and highly encouraged.

-See `CONTRIBUTING`_ for more information on how to get started.
+`See CONTRIBUTING`_ for more information on how to get started.

-.. _CONTRIBUTING: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/CONTRIBUTING.rst
+.. _See CONTRIBUTING: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/CONTRIBUTING.rst

 License
 -------

-Apache 2.0 - See `LICENSE`_ for more information.
+Apache 2.0 - `See LICENSE`_ for more information.

-.. _LICENSE: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/LICENSE
+.. _See LICENSE: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/LICENSE

 .. |build| image:: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python.svg?branch=master
    :target: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python
```

### PR DESCRIPTION
**Pull request by dhermes**
Follow up to #3316. Fixes #2446.

### CODE REVIEW

**Comment by dhermes** [comment]
Nice! This revealed an issue with the Logging README!

**Comment by tseaver** [comment]
@dhermes Are you planning to update the PR with a commit fixing the logging README?

**Comment by dhermes** [comment]
Yes, just been cranking on https://github.com/GoogleCloudPlatform/google-resumable-media-python, will do now.

**Comment by tseaver** [comment]
LGTM pending CI.

**Comment by dhermes** [comment]
Also found an issue with monitoring's README, hopefully we can go green on the 3rd run. Good thing we re-open #2446!

**Pull request merged**
