### PR TITLE
Update upstream URI.

### PR DESCRIPTION
**Pull request by daspecster**
- Fixes upstream URL in `CONTRIBUTING.rst`.

@dhermes, this is the real issue anyway. If you think any of the other stuff from #2501 was worth while, let me know and I can add it.

Redux from #2501

### CODE REVIEW

**Comment by daspecster** [comment]
[image](https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/165483428#L201)

**Comment by daspecster** [comment]
@dhermes, if the "bump" commit is removed then travis: tox -e lint goes haywire. I'm guessing it's something to do with the caches on travis.  My next thought is to just clear the caches on travis anyway since there have been some huge changes and it might be good to have a fresh start. LMKWYT.

**Comment by dhermes** [comment]
@daspecster The problem is that there were no Python files to lint, [so when building the command][1]:

```
pycodestyle_command = ['pycodestyle'] + python_files
```

It just runs a bare

```
$ pycodestyle
```

I'll dump a fix in #2503.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/8c50e41f2562c345ccaa8228984af4f51ca1df4d/scripts/pycodestyle_on_repo.py#L38

**Comment by daspecster** [comment]
Ah thank you! I wish I would have pieced that together this morning :/

**Comment by dhermes** [comment]
@daspecster Remove the bogus 2nd commit and just merge away? Clearly editing `CONTRIBUTING.rst` will have no impact on any of our code.

**Pull request merged**
