### PR TITLE
Move google.cloud.future to google.api.core

### PR DESCRIPTION
**Pull request by jonparrott**

### CODE REVIEW

**Comment by lukesneeringer** [comment]
Ack, I should not have done that.

**Comment by jonparrott** [comment]
nose

**Comment by jonparrott** [comment]
If the build on master breaks, I'll send follow up PRs to fix.

**Comment by jonparrott** [comment]
Actually nvm, it looks like circle got a full build in https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2798?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Should be good. Thanks for being trigger happy, @lukesneeringer

**Pull request merged**
