### PR TITLE
BigQuery: Exclude PyArrow from Windows Python 2.7 tests

### PR DESCRIPTION
**Pull request by tswast**
Closes https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5441

### CODE REVIEW

**Comment by theacodes** [comment]
Could you try using `sys.platform != windows` in the extras in setup.py?

**Comment by tswast** [comment]
> Could you try using sys.platform != windows in the extras in setup.py?

We don't want to exclude all Windows installs, just those for Python 2.7. Do [platform-specific dependencies](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies) "and" together?

**Comment by theacodes** [comment]
yes

**Comment by tswast** [comment]
Hmm, I guess `extras_require` doesn't allow exclusions? I tried

```
extras = {
    'pandas': 'pandas>=0.17.1',
    # Exclude PyArrow dependency from Windows Python 2.7.
    'pyarrow': 'pyarrow>=0.4.1; platform_system!=Windows or python_version>2.7',
}
```

and got "error in google-cloud-bigquery setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers."

**Comment by theacodes** [comment]
Does it work with just one platform specifier?

**Comment by tswast** [comment]
Update: the syntax is different than I expected, but I still haven't figured out how to and/or multiple markers.

```
extras = {
    'pandas': 'pandas>=0.17.1',
    # Exclude PyArrow dependency from Windows Python 2.7.
    'pyarrow: platform_system!=Windows or python_version>2.7': 'pyarrow>=0.4.1',
}
```

"error in google-cloud-bigquery setup command: Invalid environment marker:  platform_system!=Windows or python_version>2.7"

**Comment by theacodes** [comment]
https://www.python.org/dev/peps/pep-0496/#examples

**Comment by tswast** [comment]
I've confirmed that the previously failing unit tests pass on my Windows machine.

**Pull request merged**
