### PR TITLE
Revert "Spanner: Make sure **exactly** one of `start_*`/`end_*` are p…

### LINKED ISSUE #4694: KeyRange arguments change is backward-incompatible
FYC, @dhermes / @chemelnucfin / @lukesneeringer .

PR #4618 introduced a backward-incompatible change to the way arguments to the `KeyRange` constructor are validated:

- Prior to the PR, the constructor required that the caller pass at least one of `start_open`, `start_closed`, `end_open`, or `end_closed`.  It verified that the caller passed at most one of `start_open` / `start_closed`, and at most one of `end_open` / `end_closed`.  If the caller passed a `start_*` argument, she could omit passing an `end_*` argument to indicate all keys greater than the start;  likewise she could omit passing a `start_*` argument if she passed an `end_*` argument to indicate all keys less than the end.
- After the PR, the constructor requires that the caller pass exactly one of `start_open` / `start_closed` *and* exactly one of `end_open` / `end_closed`.  If the caller wants to include all keys lower / greater than the passed `end_*` / `start_*`, the new implementation requires that she pass an empty key for the other end.

I would argue that the new surface is inferior:  the `KeyRange` is perfectly capable of divining the intent when only one of the four arguments is passed, and could assign the now-required-to-be-passed value itself.

### PR DESCRIPTION
**Pull request by jonparrott**
…assed to KeyRange (#4618)"

This reverts commit 4d6cd26c32ede99afd36ec96558c54d6120791f4.

Towards #4694

### CODE REVIEW

**Comment by dhermes** [comment]
This LGTM but I don't think you should close #4694. Or if you do, you should re-open the issue that #4618 seeked to fix.

**Comment by jonparrott** [comment]
Fair enough, will leave it open.

**Comment by jonparrott** [comment]
@tseaver can you shed some light on the failure here: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/5141?

**Comment by jonparrott** [comment]
nvm, @dhermes helped me figure it out.

**Comment by dhermes** [comment]
And [Chuck Norris][1]!

[1]: http://iruntheinternet.com/lulzdump/images/nunchucks-nuns-chuck-norris-nun-12593488599.jpg?id=

**Comment by jonparrott** [comment]
Is that linked in the contributing guide? If not, it should be. P0.

**Comment by jonparrott** [comment]
Ignoring conflict error as it's just due to noise from another spanner system tests (I will not release this without a green build on the release PR).

**Comment by chemelnucfin** [comment]
I think there was a bug fix in the commit that you reverted.  I have to
take a look in detail to check.


On Wed, Jan 10, 2018 at 4:08 PM, Jon Wayne Parrott <notifications@github.com

**Comment by tseaver** [comment]
Rather than raising a ValueError if the caller passes a `start_open` / `start_closed` but neither `end_open` / `end_closed`, the constructor should just assign the empty list to `end_open` (this was the documented workaround for the caller in #4618:  we can just do it on the caller's behalf).

Likewise for the case where the caller passes an `end_open` / `end_closed` but neither of `start_open` / `start_closed`:  the constructor should just assign `start_open = []`.

**Comment by chemelnucfin** [comment]
For the first case, I think assigning it to `end_closed` is a better choice, as I believe that `end_open` excludes everything.

**Comment by chemelnucfin** [comment]
Likewise for the `end_closed`.  Should I make the change?

**Comment by jonparrott** [comment]
Go for it, if you're faster than CI I'll rebase it into #4732.

**Pull request merged**
