### PR TITLE
Change acceptance test to contain timstamps

### PR DESCRIPTION
**Pull request by vkedia**
This should *NOT* be merged.

### CODE REVIEW

**Comment by vkedia** [comment]
@tseaver @chemelnucfin This should demonstrate #4184 . Note this should not be merged. It is just for demonstrating the bug. I will later add a separate test case for this.

**Comment by chemelnucfin** [comment]
@vkedia Did you try that?  I tried something like that and it was working.  But I started working on something else before I fully convinced myself...

**Comment by vkedia** [comment]
No i did not try it.

**Comment by chemelnucfin** [comment]
Since the other issue has not been seen again, I made the assumption that this bug was somehow fixed and I will close this.

**Pull request closed without merging**
