### PR TITLE
Suppress new pytest warnings spew.

### PR DESCRIPTION
**Pull request by tseaver**
See: https://docs.pytest.org/en/latest/warnings.html

### CODE REVIEW

**Comment by tseaver** [comment]
Our tests actually trap for the warnings and assert they are raised.  This issue is suppressing new pytest behavior which injects the warnings into test run output even though we handle them.

**Comment by dhermes** [comment]
Can you give an example of what you're referring to?

**Comment by tseaver** [comment]
```bash
$ nox -e unit_tests
nox > Running session unit_tests(python_version='2.7')
nox > The virtualenv name was hashed to avoid being too long.
nox > virtualenv /home/tseaver/projects/agendaless/Google/src/google-cloud-python/core/.nox/695fcb8e -p python2.7
nox > chdir /home/tseaver/projects/agendaless/Google/src/google-cloud-python/core
nox > pip install --upgrade mock pytest pytest-cov grpcio >= 1.0.2
nox > pip install --upgrade -e .
nox > py.test --quiet --cov=google.cloud --cov=tests.unit --cov-append --cov-config=.coveragerc --cov-report= --cov-fail-under=97 tests/unit
....................................................................................................................................................................................................................................................................................................................................................................................................


Required test coverage of 97% reached. Total coverage: 100.00%
=============================== warnings summary ===============================
tests/unit/test_iam.py::TestPolicy::test_editors_setter
  /home/tseaver/projects/agendaless/Google/src/google-cloud-python/core/google/cloud/iam.py:110: DeprecationWarning: Assigning to 'editors' is deprecated.  Replace with 'policy[roles/editor] = members.
    DeprecationWarning)

tests/unit/test_iam.py::TestPolicy::test_owners_setter
  /home/tseaver/projects/agendaless/Google/src/google-cloud-python/core/google/cloud/iam.py:93: DeprecationWarning: Assigning to 'owners' is deprecated.  Replace with 'policy[roles/owner] = members.
    DeprecationWarning)

-- Docs: http://doc.pytest.org/en/latest/warnings.html
388 passed, 2 warnings in 1.68 seconds
nox > Session unit_tests(python_version='2.7') successful. :)
nox > Running session unit_tests(python_version='3.4')
nox > The virtualenv name was hashed to avoid being too long.
nox > virtualenv /home/tseaver/projects/agendaless/Google/src/google-cloud-python/core/.nox/3069abf7 -p python3.4
nox > chdir /home/tseaver/projects/agendaless/Google/src/google-cloud-python/core
nox > pip install --upgrade mock pytest pytest-cov grpcio >= 1.0.2
nox > pip install --upgrade -e .
nox > py.test --quiet --cov=google.cloud --cov=tests.unit --cov-append --cov-config=.coveragerc --cov-report= --cov-fail-under=97 tests/unit
....................................................................................................................................................................................................................................................................................................................................................................................................


Required test coverage of 97% reached. Total coverage: 100.00%
=============================== warnings summary ===============================
tests/unit/test_iam.py::TestPolicy::test_editors_setter
  /home/tseaver/projects/agendaless/Google/src/google-cloud-python/core/google/cloud/iam.py:110: DeprecationWarning: Assigning to 'editors' is deprecated.  Replace with 'policy[roles/editor] = members.
    DeprecationWarning)

tests/unit/test_iam.py::TestPolicy::test_owners_setter
  /home/tseaver/projects/agendaless/Google/src/google-cloud-python/core/google/cloud/iam.py:93: DeprecationWarning: Assigning to 'owners' is deprecated.  Replace with 'policy[roles/owner] = members.
    DeprecationWarning)

tests/unit/test_iam.py::TestPolicy::test_viewers_setter
  /home/tseaver/projects/agendaless/Google/src/google-cloud-python/core/google/cloud/iam.py:127: DeprecationWarning: Assigning to 'viewers' is deprecated.  Replace with 'policy[roles/viewer] = members.
    DeprecationWarning)

-- Docs: http://doc.pytest.org/en/latest/warnings.html

```

That is for these tests:

- https://github.com/GoogleCloudPlatform/google-cloud-python/blob/b0abcb295fde5bbab3b2f5793c8d5a8465113364/core/tests/unit/test_iam.py#L86
- https://github.com/GoogleCloudPlatform/google-cloud-python/blob/b0abcb295fde5bbab3b2f5793c8d5a8465113364/core/tests/unit/test_iam.py#L105
- https://github.com/GoogleCloudPlatform/google-cloud-python/blob/b0abcb295fde5bbab3b2f5793c8d5a8465113364/core/tests/unit/test_iam.py#L124

**Comment by dhermes** [comment]
@tseaver Are you sure "always" is the filter we want? Isn't it "ignore"?

**Comment by tseaver** [comment]
We want `always` so that the underlying "skip DeprecationWarnings and PendingDeprecationWarnings" default doesn't interfere with our ability to catch them in the test.

**Comment by dhermes** [comment]
@tseaver We can just use `mock.patch` to verify the warning gets called in the test.

**Comment by tseaver** [comment]
@dhermes `warnings.catch_warnings` is the clear-and-simple ways to verify that warnings are issued:  that is what that API is *for*.

In the wider scope:  the new py.test warning-nannyism is an opinion, and one which has caused grief elsewhere in the Python ecosystem (e.g., it broke the SQLAlchemy build).  Enabling it by default was a bad decision on their part.

**Comment by lukesneeringer** [comment]
I think you are both right.

It definitely strikes me as odd that py.test made such a major change (particularly in an incremental release). Additionally, there are warnings that you do not want to fail your build (e.g. `PendingDeprecationWarning`).

That said, I think @dhermes is right on the solution in this case. The `warnings.catch_warnings` API is for catching warnings, yes, but its purpose is for ignoring warnings _in production_, not in your test suite, and not if the thing you are trying to test is whether a warning happened. The `catch_warnings` context manager, for example, will not bomb out if it _does not_ get a warning.

`mock.patch.object(warnings, 'warn')` seems to me to be the correct way to trap a warning _in a test_, in particular because not only do you not want to get the warning, but you _also_ want to assert that the warning was called (e.g. `warn.assert_called_once()`). Your test should fail if the warning did not happen.

**Pull request closed without merging**
