### PR TITLE
Bucket logging: use bucket name as default prefix

### LINKED ISSUE #4228: bucket.enable_logging should use bucket.name as default prefix
It matches [`gsutil`](https://cloud.google.com/storage/docs/access-logs#delivery) and is probably what most users want by default.
> By default, the object prefix is the name of the bucket for which the logs are enabled.

Currently it sets an [empty prefix](https://googlecloudplatform.github.io/google-cloud-python/latest/_modules/google/cloud/storage/bucket.html#Bucket.enable_logging).

If someone stores logs from multiple buckets in a common *logs-bucket*, without explicitly setting a prefix, they can overwrite each other.

### PR DESCRIPTION
**Pull request by chemelnucfin**
@tseaver My first pull request as a test, so please feel free to look through it and scrutinize it!

Fixes #4228.

### CODE REVIEW

**Comment by tseaver** [comment]
@chemelnucfin In the future, please use `Closes #4228` in your commit message, so that the issue is closed when the commit is merged.

@lukesneeringer Does this commit suit you?  It doesn't answer my [backward-compatibility question](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4228#issuecomment-338054022) in #4228.

**Comment by lukesneeringer** [comment]
Oh, I see the concern. I _think_ I agree that this is more of a bugfix. Am I correct in understanding that for most users, this change would be invisible, and the caveat would be if anyone was _relying on_ two bucket names to match (which seems unlikely)?

I think I am okay with saying "this is a bugfix" but also documenting that you can send `prefix=''` if you wanted the old behavior. But I am also not passionate about it if you think it is unwise.

**Comment by tseaver** [comment]
The docstring change seems reasonable, given that we want the change (I find the pattern, "let's change a default to suit *my* case, thereby making everybody else change to accommodate it" a bit questionable, but I'm willing to be overruled).

**Comment by lukesneeringer** [comment]
I am pretty hesitant to overrule you here. :-) (As in, I am probably flatly unwilling to do so.)

Is there a more-backwards-compatible change, or is the docstring recommendation the best we can do?

**Comment by lukesneeringer** [comment]
Also, if we make this change, is there concern that _new_ logs would suddenly go to a new bucket? (I think there is that concern.)

**Comment by tseaver** [comment]
@lukesneeringer The prefix is applied to the names of the *blobs* created by logging, not the target bucket.

**Comment by tseaver** [comment]
The choice comes down to deciding how prevalent / important the "store logs from mutiple buckets into one bucket" usecase is, versus leaving existing / working cases alone.  Users who have that usecase can already satisfy it, by supplying an explicit prefix:  so the choice is about convenience for new users who want that, versus backward-compatibilty.

**Comment by lukesneeringer** [comment]
Okay, in that case, back-compat needs to win, unless we can make a compelling case that we need to follow `gsutil`. We should update the documentation to make it clear what to do if one is worried about bucket collision.

Sound right, @tseaver and @chemelnucfin?

**Comment by chemelnucfin** [comment]
For me, it depends on how users use this call.  If it's not a critical
issue for old users, it might be better to make it convenient for future
users and to standardize calls more.

I'd imagine there might be more chances of accidental collision if there
was no prefix for all new users, but if it broke things for old users,
collisions might not be that big a deal (since they might have just
prefixed with the same default name if they didn't want to use the empty
string)

But I don't know enough about the use cases to determine.  I'm only putting
my thoughts out there.  There might be some annoying bugs if they had an
empty string before and now they had a default name.

**Comment by lukesneeringer** [comment]
@tseaver So, if I understand correctly, new blobs will come in with a new pattern. Correct? And, if someone was using the old pattern to read stuff, they might run into issues?

In other words, say someone logs their blobs with `prefix=''`, `name='foo.bar.20171030'`, and we start calling them `bucketname-foo.bar.20171030`, all of the sudden _some other thing_ they wrote to pull out those logs on the other end stops working, and they have to specify `prefix=''` to get the old behavior back.

If that is a correct understanding then yes, that's a back-compat break, and we can not do it on a GA library.

**Pull request closed without merging**
