### PR TITLE
Updating 10 packages after google-cloud-core==0.27.0

### PR DESCRIPTION
**Pull request by dhermes**
- dns
- error_reporting
- language
- logging
- monitoring
- resource_manager
- runtimeconfig
- speech
- translate
- vision

Also updating bounds on these in `google-cloud` uber-package.

Release notes will be forthcoming as comments on this PR.

### CODE REVIEW

**Comment by dhermes** [comment]
# DNS

## Docs

- Stop referring to `stable/` docs, they are defunct (#3766)

## Dependencies

- Updating `google-cloud-core ~= 0.27` (#3864)
- `google.cloud.iterator` moved to `google.api.core.page_iterator` (#3770)

PyPI: https://pypi.org/project/google-cloud-storage/1.3.2/

**Comment by dhermes** [comment]
# Error Reporting

## Docs

- Stop referring to `stable/` docs, they are defunct (#3766)

## Dependencies

- Updating `google-cloud-core ~= 0.27` (#3864)
- Updating `google-cloud-logging ~= 1.3` (#3866)

PyPI: https://pypi.org/project/google-cloud-error-reporting/0.27.0/

**Comment by dhermes** [comment]
# Language

## Docs

- Stop referring to `stable/` docs, they are defunct (#3766)
- Using wikipedia links to HTTPS in docs (#3732)

## Dependencies

- Updating `google-cloud-core ~= 0.27` (#3864)
- Bump `google-gax >= 0.15.14`. (#3752)

PyPI: https://pypi.org/project/google-cloud-language/0.28.0/

**Comment by dhermes** [comment]
# Logging

## Feature

- Use metadata server to detect GKE environment, h/t to @liyanhui1228 (#3856)

## Docs

- Stop referring to `stable/` docs, they are defunct (#3766)

## Dependencies

- Updating `google-cloud-core ~= 0.27` (#3864)
- `google.cloud.iterator` moved to `google.api.core.page_iterator` (#3770)

PyPI: https://pypi.org/project/google-cloud-logging/1.3.0/

**Comment by dhermes** [comment]
# Logging

## Feature

- Make `__eq__` and `__ne__` work correctly with "unknown" types. (#3765)

## Docs

- Stop referring to `stable/` docs, they are defunct (#3766)

## Dependencies

- Updating `google-cloud-core ~= 0.27` (#3864)

PyPI: https://pypi.org/project/google-cloud-monitoring/0.27.0/

----

Excluded from release notes:

Increase backoff to fix monitoring system test (#3769) (Thanks @liyanhui1228)

**Comment by dhermes** [comment]
# Resource Manager

## Docs

- Stop referring to `stable/` docs, they are defunct (#3766)

## Dependencies

- Updating `google-cloud-core ~= 0.27` (#3864)
- `google.cloud.iterator` moved to `google.api.core.page_iterator` (#3770)

PyPI: https://pypi.org/project/google-cloud-resource-manager/0.27.0/

**Comment by dhermes** [comment]
# Runtime Config

## Dependencies

- Updating `google-cloud-core ~= 0.27` (#3864)
- `google.cloud.iterator` moved to `google.api.core.page_iterator` (#3770)

PyPI: https://pypi.org/project/google-cloud-runtimeconfig/0.27.0/

**Comment by dhermes** [comment]
# Speech

## Docs

- Stop referring to `stable/` docs, they are defunct (#3766)
- Fix broken link in Speech README, h/t to @jybaek (#3821)

## Dependencies

- Updating `google-cloud-core ~= 0.27` (#3864)
- Bump `google-gax >= 0.15.14`. (#3752)

PyPI: https://pypi.org/project/google-cloud-speech/0.29.0/

**Comment by dhermes** [comment]
# Translate

## Docs

- Stop referring to `stable/` docs, they are defunct (#3766)

## Dependencies

- Updating `google-cloud-core ~= 0.27` (#3864)

PyPI: https://pypi.org/project/google-cloud-translate/1.2.0/

----

Not in release notes:

- Make system tests not care about case. (#3860)

**Comment by dhermes** [comment]
# Vision

## Docs

- Stop referring to `stable/` docs, they are defunct (#3766)

## Dependencies

- Updating `google-cloud-core ~= 0.27` (#3864)
- Bump `google-gax >= 0.15.14`. (#3752)

PyPI: https://pypi.org/project/google-cloud-vision/0.27.0/

**Comment by lukesneeringer** [comment]
I can go back and make my release notes look like yours.

**Comment by dhermes** [comment]
@lukesneeringer It's up to you, I have no preference

**Comment by dhermes** [comment]
1. https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/dns-0.27.0
1. https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/error-reporting-0.27.0
1. https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/language-0.28.0
1. https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/logging-1.3.0
1. https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/monitoring-0.27.0
1. https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/resource-manager-0.27.0
1. https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/runtimeconfig-0.27.0
1. https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/speech-0.29.0
1. https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/translate-1.2.0
1. https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/vision-0.27.0

**Comment by dhermes** [comment]
## Builds

1. [`dns`][1] (green)
1. [`error-reporting`][2] (green)
1. [`language`][3] (green)
1. [`logging`][4]
1. [`monitoring`][5]
1. [`resource-manager`][6]
1. [`runtimeconfig`][7]
1. [`speech`][8]
1. [`translate`][9] (green)
1. [`vision`][10]

[1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3074
[2]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3075
[3]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3076
[4]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3077
[5]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3078
[6]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3079
[7]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3080
[8]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3081
[9]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3082
[10]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3083

**Comment by dhermes** [comment]
Pushed https://pypi.org/project/google-cloud-vision/0.27.0/ from the command line:

```
cd vision/
python setup.py sdist bdist_wheel
twine upload dist/*
```

**Pull request merged**
