### PR TITLE
Incorrect error creating empty partitioned table

### PR DESCRIPTION
**Pull request by richkadel**
I moved the partitioning_type check into the if/elif block to avoid a ValueError that should not have been thrown.

See: https://cloud.google.com/bigquery/docs/creating-partitioned-tables#creating_a_partitioned_table and the "API" example.

Before my change, the following code failed with the ValueError thrown by this function, but with my change, I was able to successfully create the partitioned table:

    destination_table = dataset.table(table_shortname)
    destination_partition = dataset.table(table_shortname+'$'+partition_date)
    
    if not destination_table.exists():
      destination_table.partitioning_type = 'DAY'
      destination_table.create()

### CODE REVIEW

**Comment by richkadel** [comment]
I'm a Google engineer, but used my personal github account to commit this small fix. Do I need to do the CLA personally, or is there something else I should do?

**Comment by dhermes** [comment]
@richkadel RE: CLA you should be fine, as long as a Googler can verify for us. Though you might want to go through the CLA just so your account is associated with the right email address within the tool? (The tool **might** have an option for Googlers, I don't recall.)

**Comment by dhermes** [comment]
@richkadel Are the unit tests passing locally for you? Your mock `_Connection()` needs a response for the `table.create()` call to succeed.

**Comment by jonparrott** [comment]
@richkadel highly prefer you to amend your commits to use your @google.com email.

**Comment by richkadel** [comment]
@dhermes - No tests were also failing for me but I had to step away from this for a while. I fixed the errors and everything is passing now.

**Comment by richkadel** [comment]
@jonparrott How do I do that? I started this by trying to just make a "quick edit" within github rather than cloning to my machine. (In retrospect, not the best idea, but it's done now.) So all edits are from the web based github editor. I have added my @google.com email account to my github account and made it the primary account. I don't know how to amend the commits with that email address. Is there an easy way or should I just start a whole new branch, copy my changes over, and drop this one? (Or can this one be accepted as-is and I'll use @google.com next time?)

**Comment by richkadel** [comment]
This is ridiculous. I tried many ways to update my email address but it looks like I just ended up with the entire history rewritten... :-(

I think I will just create a new patch from scratch

**Comment by richkadel** [comment]
I'm closing and withdrawing this and resubmitting as pull #3381

**Pull request closed without merging**
