### PR TITLE
Firestore: __add__ function for FieldPaths

### PR DESCRIPTION
**Pull request by chemelnucfin**

### CODE REVIEW

**Comment by tseaver** [comment]
I'm not sure of the utility here.  Can @jba or @schmidt-sebastian comment on how / when concatenating `FieldPath` instances would be used?

**Comment by chemelnucfin** [comment]
@tseaver For something like this:
[concat](https://github.com/GoogleCloudPlatform/google-cloud-python/commit/dd4b6465af550deb642733c3e52b9ed131141bdb#diff-a51c85bccc259f5cd6e5be357ae159ceR834)

It's just for convenience, not necessity.

**Comment by schmidt-sebastian** [comment]
I don't have any concerns if this internal only.  Note that this is called `append` in the Node/Java clients.

**Comment by jba** [comment]
I have no objections to overloading `+` to mean append. But in Go I decided to make FieldPaths immutable, because I thought the extra cost was worth avoiding aliasing bugs.

**Comment by schmidt-sebastian** [comment]
> I have no objections to overloading + to mean append. But in Go I decided to make FieldPaths immutable, because I thought the extra cost was worth avoiding aliasing bugs.

The Node and Java implementations return new copies, so maybe that's the route we should go down everywhere?

**Comment by jba** [comment]
LGTM.

**Pull request merged**
