### PR TITLE
Fix load_keys() in YCSB-like benchmark for cloud spanner.

### PR DESCRIPTION
**Pull request by haih-g**

### CODE REVIEW

**Comment by chemelnucfin** [comment]
@haih-g Could you rebase against master?  
`git pull --rebase upstream master`

**Comment by haih-g** [comment]
I recently reinstalled my linux desktop and wiped out the old github directory. I guess that's the reason we saw all those discrepancy. 

I've done "git pull --rebase upstream master". But I've "git rebase --skip" a few times to avoid painful manual merge. Also did a git pull and git push at the end. Not sure if I'm doing the right thing. Now I have

$ git status
On branch haih
Your branch is ahead of 'origin/haih' by 3 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

**Comment by chemelnucfin** [comment]
I'll just squash and merge it.  I don't think it matters much.

**Comment by haih-g** [comment]
Thx a lot!

**Pull request merged**
