### PR TITLE
BigQuery: Can iterate over QueryJob results without explicitly calling result()

### PR DESCRIPTION
**Pull request by alixhami**

### CODE REVIEW

**Comment by jonparrott** [comment]
I'd like @tswast or @jba to take a look from a BigQuery perspective as well.

**Comment by jba** [comment]
LGTM, but I will defer to Tim.

**Comment by alixhami** [comment]
@tswast If the purpose of `Client.query_rows()` was just to get query results without calling `result()`, then it would be unnecessary. Are there other uses for it, or should I remove it in another PR?

**Comment by tswast** [comment]
Talked in person. Let's remove `query_rows` in another PR. I can think of no other uses for it.

**Pull request merged**
