### PR TITLE
Add Pub/Sub snapshot and seek functionality

### PR DESCRIPTION
**Pull request by geigerj**
Notes:
- cloud.google.com links do not yet work
- SeekResponse exists but is empty; the corresponding methods return
  None instead
- It's not documented whether the deleted topic path applies to
  snapshots analogous to how it applies to subscriptions, but it seems
  logical to assume so.
- The new Subscription fields are part of this release but will come
  shortly as a separate PR. (They can be done independently of the
  snap-seek work.)

### CODE REVIEW

**Comment by geigerj** [comment]
@lukesneeringer CI is failing because it thinks [this branch doesn't have test coverage](https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3303/files#diff-c15e14c96ae7c1e14ebdff735c3080e6R492). There is a actually [a test intended to exercise this branch](https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3303/files#diff-1c9cda78cbe922973ded9e01cc466698R866). I checked raising an exception in the allegedly uncovered lines of code causes the test to fail, so not sure exactly why codecov doesn't like this.

**Comment by lukesneeringer** [comment]
This looks fine other than figuring out the CI failure. I can look at that first thing tomorrow morning.

**Comment by lukesneeringer** [comment]
The reason you are not getting full coverage is because of the `if`/`elif`:

```python
if time is not None:
    data['time'] = time
elif snapshot is not None:
    data['snapshot'] = snapshot
```

You have a test for `time` being set, and one for `snapshot` being set, but the only way that the `elif` will evaluate to `False` is if _neither_ is set.

I am assuming that setting neither option is an error case. (I assume this is also true if you set both.)

Your current logic basically makes `time` win over `snapshot` if both are set. This is probably arbitrary. I suggest making both clauses simple `if` statements and letting the API itself handle the validation if both (or neither) is set. That will also cause all branches to be covered with your current tests.

**Comment by geigerj** [comment]
Thanks for figuring this out, @lukesneeringer. That makes sense, and I agree with your changes.

**Comment by tseaver** [comment]
@geigerj, @lukesneeringer  I'm curious:  why did we rush in support for a feature which is not yet public (i.e., it requires whitelisting, has no public docs, etc., even a month later).

**Comment by lukesneeringer** [comment]
Because it was pushed for by the Pub/Sub team. They claimed at the time that support was imminent. (I raised the non-public issue and was told we were making an exception in this case.)

**Comment by tseaver** [comment]
@lukesneeringer Seems like your concern was well-founded.  I think our normal protocol (develop and review the client-side support in a private fork, push to public at launch) is more sensible.

**Comment by lukesneeringer** [comment]
For features like this, I would prefer not develop them at all until they go public. :-)

**Pull request merged**
