### PR TITLE
BigQuery: replaces table.create() with client.create_table()

### PR DESCRIPTION
**Pull request by alixhami**

### CODE REVIEW

**Comment by tswast** [comment]
Any idea what the circle failure is? Logs aren't loading for me.

**Comment by tswast** [comment]
LGTM once we figure out Circle.

**Comment by jba** [comment]
The failure is from cover:
```
google/cloud/bigquery/table.py                404      0    171      1    99%   589->592
```
BTW, I find that if I close the wedge icon next to the failing item on the Circle page, then re-open it, the logs load immediately.

**Comment by tswast** [comment]
Re: wedge. Good trick!

Looks like we need to add a "view with legacy SQL" property to a unit test to make coverage happy.

**Pull request merged**
