### PR TITLE
Correctly specifies path to WriteDisposition

### PR DESCRIPTION
**Pull request by justinwhite**
Minor doc update

### CODE REVIEW

**Comment by tseaver** [comment]
`from google.cloud.bigquery import WriteDisposition` works of last week's `google-cloud-bigquery 0.32.0` release, and is actually the "preferred" location for the docs (AFAIK).  @tswast can you confirm?

**Comment by tswast** [comment]
@tseaver That's correct. The `job` module isn't quite private, but it's better to use the explicitly public (as in used in all samples) `bigquery` module.

**Comment by tswast** [comment]
And yes, this class is imported correctly into the `bigquery` module in 0.32.0 https://github.com/GoogleCloudPlatform/google-cloud-python/blob/bigquery-0.32.0/bigquery/google/cloud/bigquery/__init__.py#L111

**Comment by tswast** [comment]
@justinwhite [`google-cloud`](https://pypi.org/project/google-cloud/) != [`google-cloud-bigquery`](https://pypi.org/project/google-cloud-bigquery/)

**Comment by tswast** [comment]
The `google-cloud` package includes all Google Cloud packages, but was last updated in 2017.

**Comment by justinwhite** [comment]
Ah, I see. Upgraded and everything looks good now. Thanks.

**Pull request closed without merging**
