### PR TITLE
Updating CONTRIBUTING doc with a contents tree at top.

### PR DESCRIPTION
**Pull request by dhermes**
Updated the syntax used for headings according to:
http://documentation-style-guide-sphinx.readthedocs.io/en/latest/style-guide.html#headings

----

See it live: https://github.com/dhermes/google-cloud-python/blob/local-contents-in-contrib/CONTRIBUTING.rst

### CODE REVIEW

**Comment by daspecster** [comment]
Pretty cool!

Are the
```
*****************
Wrapped Headers
*****************
```

required to make that work?

**Comment by dhermes** [comment]
@daspecster No, it's the `.. contents` directive

**Comment by daspecster** [comment]
Yeah I realize that but I didn't know if that directive required any special formatting to be supported.

**Comment by dhermes** [comment]
No

**Comment by daspecster** [comment]
There's no assignees for this but it LGTM.

**Comment by dhermes** [comment]
My bad on the assigned

**Pull request merged**
