### PR TITLE
Remove None & NoneType from parameter types in docstrings.

### PR DESCRIPTION
**Pull request by tswast**
Based on comment: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2580#pullrequestreview-5178193

Uses this script:
https://gist.github.com/tswast/fa8bd1cbdf84e0777109d217c2271622

I manually adjusted whitespace to fix lint errors.

### CODE REVIEW

**Comment by tswast** [comment]
@dhermes Okay to merge? Travis looks happy.

**Comment by dhermes** [comment]
@tswast Am I crazy:

```
$ git grep -l NoneType
bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/dataset.py
bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/query.py
bigquery/google/cloud/bigquery/table.py
bigtable/google/cloud/bigtable/client.py
bigtable/google/cloud/bigtable/column_family.py
bigtable/google/cloud/bigtable/table.py
core/google/cloud/_helpers.py
core/google/cloud/client.py
core/google/cloud/connection.py
datastore/google/cloud/datastore/client.py
datastore/google/cloud/datastore/key.py
datastore/google/cloud/datastore/query.py
dns/google/cloud/dns/changes.py
dns/google/cloud/dns/client.py
dns/google/cloud/dns/zone.py
error_reporting/google/cloud/error_reporting/client.py
logging/google/cloud/logging/client.py
logging/google/cloud/logging/logger.py
logging/google/cloud/logging/metric.py
logging/google/cloud/logging/sink.py
monitoring/google/cloud/monitoring/client.py
pubsub/google/cloud/pubsub/client.py
pubsub/google/cloud/pubsub/subscription.py
pubsub/google/cloud/pubsub/topic.py
resource_manager/google/cloud/resource_manager/client.py
resource_manager/google/cloud/resource_manager/project.py
scripts/rewrite_imports.py
speech/google/cloud/speech/client.py
storage/google/cloud/storage/_helpers.py
storage/google/cloud/storage/acl.py
storage/google/cloud/storage/blob.py
storage/google/cloud/storage/bucket.py
storage/google/cloud/storage/client.py
vision/google/cloud/vision/client.py
$ git log -1 --pretty=%H
1fab75689b56bc67d08e4726175b4a41a82fbef7
```

**Comment by tswast** [comment]
Not crazy, I noticed a few, too, since sending that PR. Most are `:rtype:` which I didn't remove (waiting until we decide how to document these) and some are where the ``NoneType`` spilled onto a second line from the parameter type.

**Comment by tswast** [comment]
Ouch, I see some lines like `:type message: Protobuf message or :class:`NoneType`` I'm somewhat surprise the script didn't catch these. Although, I guess this one is because the first type has a space in it.

**Comment by dhermes** [comment]
No worries, at least we made it some of the way to the finish line?

**Comment by tswast** [comment]
Yeah 407 lines of progress. :-)

**Pull request merged**
